---
date: 2024-11-07
title: "Homework - Seasonal Models and Superposition"
subtitle: Time Series Analysis
description: "Normal Dynamic Linear Models (NDLMs) are a class of models used for time series analysis that allow for flexible modeling of temporal dependencies."
categories: 
  - Bayesian Statistics
  - Time Series
keywords: 
  - Time Series
  - Filtering
  - Kalman filtering
  - Smoothing
  - NDLM
  - Normal Dynamic Linear Models
  - Polynomial Trend Models
  - Regression Models
  - Superposition Principle
  - R code
fig-caption: Notes about ... Bayesian Statistics
title-block-banner: images/banner_deep.jpg
---

::::: {.content-visible unless-profile="HC"}

::: {.callout-caution}
Section omitted to comply with the Honor Code
:::

:::::

::::: {.content-hidden unless-profile="HC"}





:::::

::: {#exr-1}
Consider a full seasonal Fourier DLM with fundamental period $p=3.$
Which of the choices below  corresponds to the specification of $F$ and $G$ for such model?
:::

::: {.solution}

- [x] 

$$
\begin{aligned}
  F = \begin{pmatrix} 1 & 0  \end{pmatrix}^\top, && 
  G = \begin{pmatrix} 
        -\frac{1}{2} & \frac{\sqrt{3}}{2} \\ 
        -\frac{\sqrt{3}}{2} & -\frac{1}{2} \end{pmatrix}
\end{aligned}
$$

- [ ]

$$
\begin{aligned}
  F = \begin{pmatrix} 1 & 0 & 1  \end{pmatrix}^\top, && 
  G = \begin{pmatrix} 
        0 & 1 & 0 \\ 
        -1 & 0 & 0 \\ 
        0 & 0 & -1 \end{pmatrix}        
\end{aligned}
$$

- [ ]

$$
\begin{aligned}
  F = \begin{pmatrix} 1 & 0  \end{pmatrix}^\top, && 
  G = \begin{pmatrix} 
        \frac{1}{2} & \frac{\sqrt{3}}{2} \\ 
        -\frac{\sqrt{3}}{2} & \frac{1}{2} \end{pmatrix}
\end{aligned}
$$

- [ ]

$$
\begin{aligned}
  F = \begin{pmatrix} 1 & 0  \end{pmatrix}^\top, && 
  G = \begin{pmatrix} 
        1 & 1 \\ 
        0 & 1 \end{pmatrix}
\end{aligned}
$$


notes:

For a full seasonal Fourier NDLM with fundamental period $p=3$, you represent the seasonal component using Fourier harmonics. A full seasonal model uses $\lfloor p/2 \rfloor = 1$ harmonic (since $p=3$). 


Regarding the Design Matrix $F$

$$
\begin{aligned}
F &= 
  \begin{pmatrix} 
    cos(\frac{2\pi t}{p}) & sin(\frac{2\pi t}{p}) 
 \end{pmatrix} ^\top \\ &= 
  \begin{pmatrix} 
    cos(\frac{2\pi t}{3}) & sin(\frac{2\pi t}{3}) 
 \end{pmatrix} ^\top \\ &= 
 \begin{pmatrix} 
    1 & 0  
 \end{pmatrix}^\top,  
\end{aligned}
$$

Regarding the transition matrix $G$

$$
\begin{aligned}
  G &=   \begin{pmatrix} 
          cos(\frac{2\pi}{p}) & sin(\frac{2\pi}{p}) \\ 
          -sin(\frac{2\pi}{p})  & cos(\frac{2\pi}{p})
        \end{pmatrix}  \\ &=
        \begin{pmatrix} 
          cos(\frac{2\pi}{3}) & sin(\frac{2\pi}{3}) \\ 
          -sin(\frac{2\pi}{3})  & cos(\frac{2\pi}{3})
        \end{pmatrix}  \\ &=
  \begin{pmatrix} 
        -\frac{1}{2} & \frac{\sqrt{3}}{2} \\ 
        -\frac{\sqrt{3}}{2} & -\frac{1}{2} \end{pmatrix}
\end{aligned}
$$

:::

::: {#exr-2}
Assume monthly data have an annual cycle and so the fundamental period is $p=12$. Further assume that we want to fit a model with a linear trend and seasonal component to this dataset.  For the seasonal component, assume we only consider the fourth harmonic, i.e., we only consider the Fourier component for the frequency $\omega = \frac{2\pi 4}{12} = \frac{2\pi}{3}$.

What is the forecast function $f_t(h)$, $h \geq 0$, for a DLM with this linear trend and a seasonal component that considers only the fourth harmonic?
:::

::: {.solution}

- [ ] $f_t(h)=a_{t,0} + a_{t,1} h + a_{t,3} \cos( \frac{2\pi h}{3}) + a_{t,4} \sin( \frac{2\pi h}{3}) + a_{t,5} (-1)^h$
- [ ] $f_t(h)= a_{t,1} \cos( \frac{2\pi h}{3}) + a_{t,2} \sin( \frac{2\pi h}{3})$​
- [ ] $f_t(h)=a_{t,0} + a_{t,1} h$
- [x] $f_t(h)=a_{t,0} + a_{t,1} h + a_{t,3} \cos( \frac{2\pi h}{3}) + a_{t,4} \sin( \frac{2\pi h}{3})$
​
:::

::: {#exr-3}
Question 3
A DLM $\{F_t, G_t, \cdot, \cdot\}$ with the following forecast function:
$f_t(h) = a_{t,1} x_{t+h} + (-1)^h a_{t,2}.$ 
What are the corresponding $F_t$ and $G_t$  matrices?
:::

::: {.solution}

- [ ]
$$
\begin{aligned}
  F = \begin{pmatrix} 1 & 0  \end{pmatrix}^\top, && 
  G = \begin{pmatrix} 
        1 & x_t \\ 
        0 & 1 \end{pmatrix}
\end{aligned}
$$

- [ ]

$$
\begin{aligned}
  F = \begin{pmatrix} 1 & x_t  \end{pmatrix}^\top, && 
  G = \begin{pmatrix} 
        1 & 0 \\ 
        0 & 1 \end{pmatrix}
\end{aligned}
$$

- [x]
$$
\begin{aligned}
  F = \begin{pmatrix} 1 & x_t  \end{pmatrix}^\top, && 
  G = \begin{pmatrix} 
        1 & 0 \\ 
        0 & -1 \end{pmatrix}
\end{aligned}
$$


:::
