
## Geometric distribution - Counting failures before first success {#sec-geometric-distribution}

::: {#vid-geometric-distribution .column-margin .content-hidden when-format="pdf"}
{{< video https://youtu.be/-vvtrsS4rkA >}}

The Geometric Distribution
:::

### Stories

::: {.callout-note}
#### Geometric Distribution Failures before success

Consider a sequence of independent Bernoulli trials, each with the same success probability $p \in (0, 1)$, with trials performed until a success occurs. Let X be the number of failures before the first successful trial. Then X has the Geometric distribution with parameter $p$

For example, if we flip a fair coin until it lands Heads for the first time, then the number of Tails before the first occurrence of Heads is distributed as Geom(1/2).

To get the Geometric PMF from the story, imagine the Bernoulli trials as a string of 0's (failures) ending in a single 1 (success). Each 0 has probability $q = 1 − p$ and the final 1 has probability $p$, so a string of $k$ failures followed by one success has probability $q^kp$.
:::

we denote this by 
$$
X \sim \mathcal{Geom}(p)
$$ {#eq-geom-rv-notation}

::: {.callout-note}
#### Geometric distribution Failures and success

Consider a sequence of independent Bernoulli trials, each with the same success probability $p \in (0, 1)$, with trials performed until a success occurs. Let X be the number of failures before the first successful trial. Then $X$ has the Geometric distribution with parameter $p$; 

We denote this by: 

$$
X \sim \mathcal{Geom}(p)
$$ {#eq-geom-rv-notation}

For example, if we flip a fair coin until it lands Heads for the first time, then the number of Tails before the first occurrence of Heads is distributed as $\mathcal{Geom}(1/2)$.

To get the Geometric PMF from the story, imagine the Bernoulli trials as a string of 0's (failures) ending in a single 1 (success). Each 0 has probability $q = 1 − p$ and the final 1 has probability p, so a string of k failures followed by one success has probability $q^kp$
:::


### Conditions

::: {.callout-tip}

-   Discrete data
-   Two possible outcomes for each trial
-   Each trial is independent and
-   The probability of success/failure is the same in each trial
-   The outcome is the count of failures before the first success
:::

### Examples

-   Consider polymerization of an actin filament. At each time step, an actin monomer may add to the end of the filament ("failure"), or an actin monomer may fall off the end ("success") with (usually very low) probability \theta. The length of actin filaments, measured in a number of constitutive monomers, is Geometrically distributed.

The **Geometric distribution** arises when we want to know "What is the number of Bernoulli trials required to get the first success?", i.e., the number of Bernoulli events until a success is observed, such as the probability of getting the first head when flipping a coin. It takes values on the positive integers starting with one (since at least one trial is needed to observe a success).

### Moments

$$
\mathbb{M}_X[t] = \frac{pe^t}{1-(1-p)e^t} \qquad t<-ln(1-p)
$$ {#eq-geom-mgf}

$$
\mathbb{E}[X] = \frac{1}{p}
$$ {#eq-geom-expectation}

$$
\mathbb{V}ar[X]=\frac{1-p}{p^2}
$$ {#eq-geom-variance}

### PMF & CDF

| | |
|------------------------------------------------------------|------------------|
| $X\sim\mathcal{Geom}(p)$| RV|
| $f_X(k,p)=\mathbb{P}r(X = k \mid p) = (1-p)^{k-1}\;p \qquad \forall x \in N;\quad 0\le p \le 1$ | PMF
| $F_X(k,p)=\mathbb{P}r(X < k \mid p)=1-(1-p)^{\lfloor x\rfloor } \qquad x<1$ |CDF|
| $\mathbb{E}[X] = \frac{1}{p}$ | Exception |
| $\mathbb{V}ar[X]=\frac{1-p}{p^2}$ | Variance |
| $\mathbb{M}_X[t] = \frac{pe^t}{1-(1-p)e^t} \qquad t<-ln(1-p)$ | MGF |
| $\varphi_X(t) =  _{X}(t)={\frac {pe^{it}}{1-(1-p)e^{it}}}$ | Characteristic function |
| $\mathbb{H}(X) = -\frac{(1-p)\log(1-p)}{p} - \log(p)$ | Entropy |
| $\mathbb{I}_X(p) = \frac{1}{p^{2}(1-p)}$ | Fisher Information |
| $\mathcal{L}(p;X)=(1-p)^{X}p$| Likelihood fn |


### Memoryless property

\index{memoryless property}

The Geometric distribution is based on geometric series.

The Geometric distribution has the memoryless property: 

$$
P (X > s \mid X >  t) = P (X > s − t)
$$ {#eq-geom-memoryless}

One can say that the distribution "forgets" what has occurred, so that The probability of getting an additional $s − t$ failures, having already observed t failures, is the same as the probability of observing $s − t$ failures at the start of the sequence. In other words, the probability of getting a run of failures depends only on the length of the run, not on its position.

$Y=X-1$ is the $\text{negative binomial}(1,p)$

### Worked out Examples

The Geometric distribution \index{distribution!geometric} arises when we consider how long we will have to "wait for a success" during repeated Bernoulli trials.

::: {#exm-geometric}
### Geometric Distribution
[4 coin flips with no heads]{.column-margin}
What is the probability that we flip a fair coin four times and don't see any heads?
:::

::: {.callout-tip}
### Solution
This is the same as asking what is $\mathbb{P}r(X > 4)$ where $X ∼ Geo(1/2)$.

$$
\begin{aligned}
\mathbb{P}r(X > 4) &= 1 − \mathbb{P}r(X =1)−\mathbb{P}r(X = 2)−\mathbb{P}r(X = 3)−\mathbb{P}r(X = 4) \\
&= 1−(\frac{1}{2})−(\frac{1}{2})(\frac{1}{2})−(\frac{1}{2})(\frac{1}{2})^2−(\frac{1}{2})(\frac{1}{2})^3  \\
&= \frac{1}{16}
\end{aligned}
$$

We could also have just computed it directly, but here we see an example of using the Geometric distribution and we can also see that we got the right answer.
:::

### Plots

```{python}
#| label: A02-4
import numpy as np
from scipy.stats import geom
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1)

p = 0.5
mean, var, skew, kurt = geom.stats(p,moments='mvsk')
print(f'{mean=:1.2f}, {var=:1.2f}, {skew=:1.2f}, {kurt=:1.2f}')

x = np.arange(geom.ppf(0.01, p),
              geom.ppf(0.99, p))
ax.plot(x, geom.pmf(x, p), 'bo', ms=8, label='geom pmf')
ax.vlines(x, 0, geom.pmf(x, p), colors='b', lw=5, alpha=0.5)

rv = geom(p)
ax.vlines(x, 0, rv.pmf(x), colors='k', linestyles='-', lw=1,
        label='frozen pmf')
ax.legend(loc='best', frameon=False)
plt.show()

r = geom.rvs(p,size=10)
r
```