
## Beta Binomial {#sec-beta-binomial-distribution}

::: { .callout-note}
### Story 1 - Polya Urn Model

The Beta-Binomial distribution with parameters $\alpha$ success rate and $\beta$ failure and $n$ the number of trials can be motivated by an Pólya urn model.

Imagine an urn containing $\alpha$ red balls and $\beta$ black balls, where random draws are made. If a red ball is observed, then two red balls are returned to the urn. Likewise, if a black ball is drawn, then two black balls are returned to the urn. If this is repeated n times, then the probability of observing x red balls follows a beta-binomial distribution with parameters $n$, $\alpha$ and $\beta$.

If the random draws are with simple replacement (no balls over and above the observed ball are added to the urn), then the distribution follows a binomial distribution and if the random draws are made without replacement, the distribution follows a hypergeometric distribution.
:::

::: {.callout-tip}
### Story 2 Compound Distribution

The Beta distribution is a conjugate distribution of the binomial distribution. This fact leads to an *analytically tractable* compound distribution constructed in a hierarchical fashion where one can think of the $p$ parameter in the $binomial$ distribution as being randomly drawn from a $beta$ distribution.

Suppose we were interested in predicting the number of heads, $X$ in $n$ future trials. This is given by

$$
\begin{aligned}
f(x\mid n,\alpha ,\beta )&=\int _{0}^{1}\mathcal{Bin} (x \mid n,p)\mathcal {Beta} (p\mid \alpha ,\beta )\,dp\\
    &={n \choose x}{\frac {1}{\mathcal {B} (\alpha ,\beta )}}\int _{0}^{1}p^{x+\alpha -1}(1-p)^{n-x+\beta -1}\,dp \\
    &={n \choose x}{\frac {\mathcal {B} (x+\alpha ,n-x+\beta )}{\mathcal {B} (\alpha ,\beta )}}.
\end{aligned}
$$ {#eq-beta-binomial-compound}

$$
f(x\mid n,\alpha ,\beta )={\frac {\Gamma (n+1)}{\Gamma (x+1)\Gamma (n-x+1)}}{\frac {\Gamma (x+\alpha )\Gamma (n-x+\beta )}{\Gamma (n+\alpha +\beta )}}{\frac {\Gamma (\alpha +\beta )}{\Gamma (\alpha )\Gamma (\beta )}}
$$ {#eq-beta-binomial-compound-gamma}
:::


### Moments

$$
\mathrm{E}(X) = \frac{n\alpha}{\alpha+\beta}
$$ {#eq-beta-binomial-expectation}

$$
var(X) = \frac{n\alpha\beta(\alpha+\beta+n)}{(\alpha+\beta)^2(\alpha+\beta+1)}
$$ {#eq-beta-binomial-variance}

### Probability mass function (PMF)

$$
f(x \mid n,\alpha,\beta) = \binom{n}{x}\frac{B(x+\alpha,n-x+\beta)}{B(\alpha,\beta)}
$$ {#eq-beta-binomial-pmf}

$$
\text{where } B(u,v)=\int_{0}^{1}t^{u-1}(1-t)^{v-1}\mathrm{d}t \text{ is the (complete) beta function }
$$ {#eq-beta-function}

### Cumulative distribution function (CDF)

$$
F(x\mid n,\alpha,\beta) = \begin{cases}
    0, & x<0 \\ 
    \binom{n}{x}\frac{B(x+\alpha,n-x+\beta)}{B(\alpha,\beta)} {}_{3}F_2(1,-x,n-x+\beta;n-x-1,1-x-\alpha;1), & 0\leq x \leq n \\
    1, & x>n 
\end{cases}
$$ {#eq-beta-binomial-cdf}

where

$$
{}_{3}F_2(a,b,x) \text{ is the generalized hypergeometric function}
$$ {#eq-gen-hypergeometric-function}