## Discrete Uniform Distribution {#sec-discrete-uniform}

### Stories

::: {.callout-note}

#### Discrete Uniform Finite set Parametrization

Let $C$ be a finite, nonempty set of numbers and $X$ *random variable* associated with the event of *choosing one of these numbers uniformly at random*, that is all values being equally likely $X(x=c)$

Then $X$ is said to have the Discrete Uniform distribution with parameter $C$.

We denote this by $X \sim \mathcal{Unif}(a,b)$.
:::



::: {.callout-note}

#### Discrete Uniform with Lower and Upper bound Parametrization

When the set $C$ above is $C=\{c \in \mathbb{Z} \mid a \le c \le b\ \}$.

Then $X$ is said to have the Discrete Uniform distribution with lower bound parameter $a$ and upper bound parameter $b$.
:::



::: {.callout-note}

#### Urn Model

Suppose we have an Urn with n balls labeled with the numbers a $1, \dots, a_n$ . 
One drawing from the urn produces a discrete uniform random variable on the set $\{a_1, \dots, a_n \}$.
:::

### Probability mass function (PMF)

$$
f(x \mid a, b) = \frac{1}{b - a + 1}
$$ {#eq-uniform-PMF}

### Cumulative distribution function (CDF)

$$
F(x \mid a, b) = \frac{\lfloor x \rfloor - a - 1}{b - a + 1} \\
$$ {#eq-uniform-CDF}

- where
    - $\lfloor x \rfloor$ is the floor function (rounds down reals to nearest smaller integer)

<!-- TODO: plot pdf and cdf -->



### Moments

$$
\begin{aligned}
    \phi_X(t)&= {\frac {e^{at}-e^{(b+1)t}}{n(1-e^{t})}}  && \text{(MGF)}
\end{aligned}
$$ {#eq-uniform-MGF}

$$
\begin{aligned}
    \mathbb{E}[X] &= \frac{a + b}{2} && \text{(Expectation)}
\end{aligned}
$$ {#eq-uniform-expectation} 

$$
\begin{aligned}
\mathbb{V}ar[X] &= \frac{(b - a + 1)^2 - 1}{12} && \text{(Variance)}
\end{aligned}
$$ {#eq-uniform-MGF}


### Prior

Since a number of families have the uniform as a special case we can use them as priors when we want a uniform prior:
