project:
  type: website
  preview:
    port: 4200
  output-dir: _site

highlight-style: a11y

website:
  title: "Bayesian Statsistics"
  sidebar:
      style: "docked"
      search: true
      contents:
        - section: "Intro"
          contents:
          - about.qmd
          - index.qmd
          - intro.qmd
        - section: "1. From Concept to Data Analysis"
          contents:
          - C1-L01.qmd
          - C1-L01-Ex1.qmd
          - C1-L02.qmd
          - C1-L02-Ex1.qmd
          - C1-L02-Ex2.qmd
          - C1-L03.qmd
          - C1-L03-Ex1.qmd
          - C1-L03-Ex2.qmd    
          - C1-L04.qmd
          - C1-L04-Ex1.qmd
          - C1-L05.qmd
          - C1-L05-Ex1.qmd
          - C1-L05-Ex2.qmd
          - C1-L06.qmd
          - C1-L06-Ex1.qmd
          - C1-L07.qmd
          - C1-L07-Ex1.qmd    
          - C1-L08.qmd
          - C1-L08-Ex1.qmd    
          - C1-L08-Ex2.qmd
          - C1-L09.qmd
          - C1-L09-Ex1.qmd    
          - C1-L10.qmd
          - C1-L10-Ex1.qmd    
          - C1-L11.qmd
          - C1-L11-Ex1.qmd  
          - C1-L12.qmd
          - C1-L12-Ex1.qmd    
          - C1-L12-Ex2.qmd
        - section: "2. Techniques and Models"
          contents:
          - C2-L01.qmd
          - C2-L02.qmd
          - C2-L03.qmd
          - C2-L04.qmd
          - C2-L04-Ex1.qmd
          - C2-L05.qmd
          - C2-L05-Ex1.qmd
          - C2-L06.qmd
          - C2-L06-Ex1.qmd
          - C2-L06-Ex2.qmd
          - C2-L07.qmd
          - C2-L07-Ex1.qmd
          - C2-L07-Ex2.qmd    
          - C2-L08.qmd
          - C2-L08-Ex1.qmd
          - C2-L08-Ex2.qmd
          - C2-L09.qmd    
          - C2-L09-Ex1.qmd
          - C2-L10.qmd
          - C2-L10-Ex1.qmd
          - C2-L11.qmd
          - C2-L11-Ex1.qmd
          - C2-L11-Ex2.qmd
          - C2-L12.qmd
          - C2-L12-Ex1.qmd
        - section: "3. Mixture Models"
          contents:
          - C3-L01.qmd
          - C3-L01-Ex1-Basic-Definitions.qmd
          - C3-L01-Ex2-Gaussian-mixtures.qmd
          - C3-L01-Ex3-Zero-Inflated-distribution.qmd
          - C3-L01-Ex4-Def-mixture-models.qmd
          - C3-L01-Ex5.qmd # Simulating from a Mixture Model -  Poisson
          - C3-L01-Ex6.qmd # Likelihood function for mixture models - exponential
          - C3-L02.qmd
          - C3-L02-Ex1.qmd # The EM algorithm for zero-inflated mixtures - netsize.csv
          - C3-L02-Ex2.qmd # The EM algorithm for Mixture Models - fuses.csv
          - C3-L03.qmd
          - C3-L04.qmd
          - C3-L05.qmd
        - section: "4. Time series Models"
          contents:
          - C4-L01.qmd
        - section: "5. Capstone Project"
          contents:
          - C5-L01.qmd
        - section: "6. Appendices"
          contents:
          - A01.qmd
          - A02.qmd
          - A03.qmd
          - A04.qmd
          - A05.qmd
          - A06.qmd
          - A07.qmd    
          - A08.qmd
          - A09.qmd
          - A10.qmd
          - A11.qmd
          - A12.qmd
          - summary.qmd

bibliography: references.bib
format:
  html:
    from: "markdown+emoji"
    lightbox: 
      match: auto
      effect: fade
      desc-position: bottom
      loop: true
      css-class: "my-css-class"


    respect-user-color-scheme: true
    toc: true
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
  
execute:
  freeze: auto  # re-render only when source changes
