project:
  type: book
  preview:
    port: 4200
  output-dir: docs
  execute-dir: project

  

book:
  page-footer: 
    background: light
    left: "Copyright 2025, Oren Bochman" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 

  title: "Bayesian Statistics"
  chapters:
      - index.qmd
      #- intro.qmd
      # bayesian-statistics by Herbert Lee
      - part: C1-L00.qmd     
        chapters:
          - C1-L01.qmd
          - C1-L01-Ex1.qmd
          - C1-L02.qmd
          - C1-L02-Ex1.qmd
          - C1-L02-Ex2.qmd
          - C1-L03.qmd
          - C1-L03-Ex1.qmd
          - C1-L03-Ex2.qmd    
          - C1-L04.qmd
          - C1-L04-Ex1.qmd
          - C1-L05.qmd
          - C1-L05-Ex1.qmd
          - C1-L05-Ex2.qmd
          - C1-L06.qmd
          - C1-L06-Ex1.qmd
          - C1-L07.qmd
          - C1-L07-Ex1.qmd    
          - C1-L08.qmd
          - C1-L08-Ex1.qmd    
          - C1-L08-Ex2.qmd
          - C1-L09.qmd
          - C1-L09-Ex1.qmd    
          - C1-L10.qmd
          - C1-L10-Ex1.qmd    
          - C1-L11.qmd
          - C1-L11-Ex1.qmd  
          - C1-L12.qmd
          - C1-L12-Ex1.qmd    
          - C1-L12-Ex2.qmd
      # mcmc-bayesian-statistics by Matthew Heiner
      - part: C2-L00.qmd       # mcmc-bayesian-statistics
        chapters:
          - C2-L01.qmd
          - C2-L02.qmd
          - C2-L03.qmd
          - C2-L04.qmd
          - C2-L04-Ex1.qmd
          - C2-L05.qmd
          - C2-L05-Ex1.qmd
          - C2-L06.qmd
          - C2-L06-Ex1.qmd
          - C2-L06-Ex2.qmd
          - C2-L07.qmd
          - C2-L07-Ex1.qmd
          - C2-L07-Ex2.qmd    
          - C2-L08.qmd
          - C2-L08-Ex1.qmd
          - C2-L08-Ex2.qmd
          - C2-L09.qmd    
          - C2-L09-Ex1.qmd
          - C2-L10.qmd
          - C2-L10-Ex1.qmd
          - C2-L11.qmd
          - C2-L11-Ex1.qmd
          - C2-L11-Ex2.qmd
          - C2-L12.qmd
          - C2-L12-Ex1.qmd 
      # mixture-models by Abel Rodriguez
      - part: C3-L00.qmd      # mixture-models
        chapters:
          - C3-L01.qmd
          - C3-L01-Ex1-Basic-Definitions.qmd
          - C3-L01-Ex2-Gaussian-mixtures.qmd
          - C3-L01-Ex3-Zero-Inflated-distribution.qmd
          - C3-L01-Ex4-Def-mixture-models.qmd
          - C3-L02.qmd
          - C3-L02-Ex1.qmd
          - C3-L02-Ex2.qmd 
          - C3-L02-Ex3.qmd 
          - C3-L02-Ex4.qmd 
          - C3-L02-Ex5.qmd 
          - C3-L02-Ex6.qmd 
          - C3-L03.qmd
          - C3-L03-Ex1.qmd # The EM algorithm for zero-inflated mixtures - nestsize.csv
          - C3-L03-Ex2.qmd # The EM algorithm for Mixture Models - fuses.csv
          - C3-L04.qmd
          - C3-L04-Ex1.qmd # The MCMC algorithm for zero-inflated mixtures - nestsize.csv
          - C3-L04-Ex2.qmd # The MCMC algorithm for Mixture Models - fuses.csv          
          - C3-L05.qmd
          - C3-L06.qmd
          - C3-L07.qmd
          - C3-L07-Ex1.qmd
          - C3-L07-Ex2.qmd
          - C3-L07-Ex3.qmd         
          - C3-L08.qmd
          - C3-L08-Ex1.qmd
          - C3-L09.qmd
          - C3-L09-Ex1.qmd
          - C3-L09-Ex2.qmd
          - C3-L09-Ex3.qmd
          - C3-L09-Ex4.qmd
      # bayesian-statistics-time-series-analysis By Raquel Prado
      - part: C4-L00.qmd    # introduction to the bayesian-statistics-time-series-analysis
        chapters:          
          # 01_week-1-introduction-to-time-series-and-the-ar-1-process
          - C4-L01.qmd      # 02_stationarity-the-acf-and-the-pacf
          - C4-L02.qmd      # 03_the-ar-1-process-definition-and-properties
          - C4-L03.qmd      # 04_the-ar-1-maximum-likelihood-estimation-and-bayesian-inference
          # 02_week-2-the-ar-p-process
          - C4-L04.qmd      # 01_the-general-ar-p-process
          - C4-L05.qmd      # 02_bayesian-inference-in-the-ar-p
          - C4-L05-Ex1.qmd  # Exercise 1
          - C4-L05-Ex2.qmd  # Exercise 2
          # 3 03_week-3-normal-dynamic-linear-models-part-i
          - C4-L06.qmd      # 01_the-normal-dynamic-linear-model-definition-model-classes-and-the-superposition 
          - C4-L07.qmd      # 02_bayesian-inference-in-the-ndlm-part-i 
          # 04_week-4-normal-dynamic-linear-models-part-ii
          - C4-L08.qmd      # 01_seasonal-ndlms
          - C4-L09.qmd      # 02_bayesian-inference-in-the-ndlm-part-ii
          - C4-L09-Ex1.qmd  # Exercise 1
          - C4-L10.qmd      #  capstone-project
          # - C4-L11.qmd    # A Feynman Notebook
      # bayesian-statistics-capstone by Jizhou Kang
      - part: C5-L00.qmd
        chapters:
          - C5-L01.qmd  
          - C5-L01-Ex1.qmd
          - C5-L01-Ex2.qmd
          - C5-L02.qmd
          - C5-L02-Ex1.qmd
          - C5-L02-Ex2.qmd
          #- C5-L03.qmd 
          - C5-L03.1.qmd 
          - C5-L03.2.qmd 
          - C5-L03.3.qmd 
      # bayesian-nonparametrics by Tilda 
      - part: C6-L00.qmd 
        chapters:  
          - C6-L01.qmd
          - C6-L02.qmd
          - C6-L03.qmd
      #- part: C7-L00.qmd 
      #  chapters:  
      #    - C7-L01.qmd
  appendices:
      - A01.qmd
      - A02.qmd
      - A03.qmd
      - A05.qmd
      - A07.qmd    
      - A08.qmd
      - A09.qmd
      - A10.qmd
      - A11.qmd
      - A12.qmd
      - A13.qmd
      - A14.qmd
      - A15.qmd
      - A16.qmd
      - references.qmd
  #   - summary.qmd

format:
  pdf:
    #engine: xelatex  # or lualatex
    engine: lualatex
    emoji: true
    #mainfont: "Times New Roman"
    toc: true
    toc-depth: 3
    toc-title: "Table of contents"
    lof: true
    lot: true
    mainfont: "EB Garamond"
    sansfont: "Open Sans"
    monofont: "Roboto Mono"
    mathfont: "TeX Gyre Termes Math"
    mainfontfallback:
      - "NotoColorEmoji:mode=harf" # for emojis
    from: "markdown+emoji"
    number-sections: true
    number-depth: 2
    papersize: a4
    #margin-right: 80mm
    geometry:
      - left=20mm
      - right=70mm
      - marginparwidth=65mm
      - marginparsep=5mm
      - top=20mm
      - bottom=20mm
      - heightrounded
    #  - outer=40mm
    #  - inner=30mm
      #- headsep=22pt
      #- headheight=11pt
      #- footskip=33pt
      #- ignorehead
      #- ignorefoot
      #- total={170mm,257mm}
    hyperrefoptions:
      - linktoc=all
      - pdfwindowui
      - pdfpagemode=FullScreen
    html-math-method: katex
    documentclass: scrreprt
    include-in-header:
      - text: |
          \usepackage{amsmath}
          \usepackage{cancel}
          \usepackage{undertilde}
          \usepackage{imakeidx}
          \usepackage{gensymb}
          \usepackage[x11names]{xcolor}
          \definecolor{grey}{rgb}{0.5,0.5,0.5}
          \usepackage[export]{adjustbox} 
          \makeindex[intoc=true, columns=3, columnseprule=true]
    #\includegraphics[max width=\linewidth]{image.png}
    #\hbadness=10000      
    #\geometry{a4paper, total={170mm,257mm}, left=20mm, top=20mm, bottom=20mm, right=20mm, marginparwidth=60mm }
    #\geometry{a4paper, total={170mm,257mm}, left=20mm, top=20mm, bottom=20mm, right=50mm}
    #\makeindex[intoc=true, columns=3, columnseprule=true, options=-s latex/indexstyles.ist]
    include-after-body: 
      - text: |
          \printindex
  # epub is too big for GitHub, so we need to add it as a local build profile.
  # epub:
  #   cover-image: cover.png
  html: 
    css: styles.css
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    include-after-body: js.html
    from: "markdown+emoji"

    toc: true
    toc_float: true
    respect-user-color-scheme: true

    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px    

    title-block-banner: images/banner_deep.jpg
    fig-caption: Notes about ... Bayesian Statistics
    #bibliography: bibliography.bib
    number-sections: true
    html-math-method: katex
    code-fold: false
    code-tools: true
    code-copy: true
    code-overflow: wrap
    code-annotations: hover
    lightbox: 
      match: auto
      effect: fade
      desc-position: bottom
      loop: true
      css-class: "my-css-class"
    sidebar:
        style: "docked"
        search: true
bibliography: references.bib

profile:
  default: development

highlight-style: a11y

crossref:
  custom:
    - kind: float
      reference-prefix: Video
      key: vid
      latex-env: video
  
knitr:
  opts_chunk:
    cache.path: _output/cache/


execute:
  freeze: auto  # re-render only when source changes
