project:
  title: "book (basic)"
  output-dir: _book_basic
  type: book

format:
  pdf:
    #mainfont: "Times New Roman"
    mainfont: "EB Garamond"
    sansfont: "Open Sans"
    monofont: "Roboto Mono"
    from: "markdown+emoji"
    number-sections: true
    html-math-method: katex
    documentclass: scrreprt
    include-in-header:
      - text: |
          \usepackage{cancel}
          \usepackage{undertilde}
          \usepackage{imakeidx}
          \usepackage{gensymb}
          \makeindex[intoc=true, columns=3, columnseprule=true]
    #\makeindex[intoc=true, columns=3, columnseprule=true, options=-s latex/indexstyles.ist]
    include-after-body: 
      - text: |
          \printindex
book:
  title: "Bayesian Specialization Notes"
  date: "7/6/2025"
  chapters:
    - about.qmd
    - index.qmd
    - intro.qmd
    - C1-L01.qmd
    - C1-L02.qmd
    - C1-L03.qmd
    - C1-L04.qmd
    - C1-L05.qmd
    - C1-L06.qmd
    - C1-L07.qmd
    - C1-L08.qmd
    - C1-L09.qmd
    - C1-L10.qmd
    - C1-L11.qmd
    - C1-L12.qmd
    - C2-L01.qmd
    - C2-L02.qmd
    - C2-L03.qmd
    - C2-L04.qmd
    - C2-L05.qmd
    - C2-L06.qmd
    - C2-L07.qmd
    - C2-L08.qmd
    - C2-L09.qmd
    - C2-L10.qmd
    - C2-L11.qmd
    - C2-L12.qmd
    - C3-L01.qmd
    - C3-L02.qmd
    - C3-L03.qmd
    - C3-L04.qmd
    - C3-L05.qmd
    - C3-L06.qmd
    - C3-L07.qmd
    - C3-L08.qmd
    - C3-L09.qmd  
    - A01.qmd
    - A02.qmd
    - A03.qmd
    - A05.qmd
    - A07.qmd
    - A08.qmd
    - A09.qmd
    - A10.qmd
    - A11.qmd
    - A12.qmd
    - references.qmd