project:
  type: book
  preview:
    port: 4200
  output-dir: docs
  execute-dir: project
book:
  sharing: [twitter, facebook]
  page-navigation: true
  google-analytics: 
    tracking-id: "G-GYZ17VPVEJ"
    anonymize-ip: true
  favicon: images/favicon.ico
  comments:
    hypothesis: true
  search: true

  page-footer: 
    background: light
    left: "Copyright 2025, Oren Bochman" 
    right: 
      - icon: bi-house 
        href: https://orenbochman.github.io/blog/
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/orenbochman
      - icon: linkedin 
        href: https://www.linkedin.com/li/orenbochman/

  title: "Bayesian Statistics"
  chapters:
      - index.qmd
      #- intro.qmd
      # bayesian-statistics by Herbert Lee
      - part: C1/C1-L00.qmd     
        chapters:
          - C1/C1-L01.qmd
          - C1/C1-L01-Ex1.qmd
          - C1/C1-L02.qmd
          - C1/C1-L02-Ex1.qmd
          - C1/C1-L02-Ex2.qmd
          - C1/C1-L03.qmd
          - C1/C1-L03-Ex1.qmd
          - C1/C1-L03-Ex2.qmd    
          - C1/C1-L04.qmd
          - C1/C1-L04-Ex1.qmd
          - C1/C1-L05.qmd
          - C1/C1-L05-Ex1.qmd
          - C1/C1-L05-Ex2.qmd
          - C1/C1-L06.qmd
          - C1/C1-L06-Ex1.qmd
          - C1/C1-L07.qmd
          - C1/C1-L07-Ex1.qmd    
          - C1/C1-L08.qmd
          - C1/C1-L08-Ex1.qmd    
          - C1/C1-L08-Ex2.qmd
          - C1/C1-L09.qmd
          - C1/C1-L09-Ex1.qmd    
          - C1/C1-L10.qmd
          - C1/C1-L10-Ex1.qmd    
          - C1/C1-L11.qmd
          - C1/C1-L11-Ex1.qmd  
          - C1/C1-L12.qmd
          - C1/C1-L12-Ex1.qmd    
          - C1/C1-L12-Ex2.qmd
      # mcmc-bayesian-statistics by Matthew Heiner
      - part: C2/C2-L00.qmd       # mcmc-bayesian-statistics
        chapters:
          - C2/C2-L01.qmd
          - C2/C2-L02.qmd
          - C2/C2-L03.qmd
          - C2/C2-L04.qmd
          - C2/C2-L04-Ex1.qmd
          - C2/C2-L05.qmd
          - C2/C2-L05-Ex1.qmd
          - C2/C2-L06.qmd
          - C2/C2-L06-Ex1.qmd
          - C2/C2-L06-Ex2.qmd
          - C2/C2-L07.qmd
          - C2/C2-L07-Ex1.qmd
          - C2/C2-L07-Ex2.qmd    
          - C2/C2-L08.qmd
          - C2/C2-L08-Ex1.qmd
          - C2/C2-L08-Ex2.qmd
          - C2/C2-L09.qmd    
          - C2/C2-L09-Ex1.qmd
          - C2/C2-L10.qmd
          - C2/C2-L10-Ex1.qmd
          - C2/C2-L11.qmd
          - C2/C2-L11-Ex1.qmd
          - C2/C2-L11-Ex2.qmd
          - C2/C2-L12.qmd
          - C2/C2-L12-Ex1.qmd 
      # mixture-models by Abel Rodriguez
      - part: C3/C3-L00.qmd      # mixture-models
        chapters:
          - C3/C3-L01.qmd
          - C3/C3-L01-Ex1-Basic-Definitions.qmd
          - C3/C3-L01-Ex2-Gaussian-mixtures.qmd
          - C3/C3-L01-Ex3-Zero-Inflated-distribution.qmd
          - C3/C3-L01-Ex4-Def-mixture-models.qmd
          - C3/C3-L02.qmd
          - C3/C3-L02-Ex1.qmd
          - C3/C3-L02-Ex2.qmd 
          - C3/C3-L02-Ex3.qmd 
          - C3/C3-L02-Ex4.qmd 
          - C3/C3-L02-Ex5.qmd 
          - C3/C3-L02-Ex6.qmd 
          - C3/C3-L03.qmd
          - C3/C3-L03-Ex1.qmd # The EM algorithm for zero-inflated mixtures - nestsize.csv
          - C3/C3-L03-Ex2.qmd # The EM algorithm for Mixture Models - fuses.csv
          - C3/C3-L04.qmd
          - C3/C3-L04-Ex1.qmd # The MCMC algorithm for zero-inflated mixtures - nestsize.csv
          - C3/C3-L04-Ex2.qmd # The MCMC algorithm for Mixture Models - fuses.csv          
          - C3/C3-L05.qmd
          - C3/C3-L06.qmd
          - C3/C3-L07.qmd
          - C3/C3-L07-Ex1.qmd
          - C3/C3-L07-Ex2.qmd
          - C3/C3-L07-Ex3.qmd         
          - C3/C3-L08.qmd
          - C3/C3-L08-Ex1.qmd
          - C3/C3-L09.qmd
          - C3/C3-L09-Ex1.qmd
          - C3/C3-L09-Ex2.qmd
          - C3/C3-L09-Ex3.qmd
          - C3/C3-L09-Ex4.qmd
      # bayesian-statistics-time-series-analysis By Raquel Prado
      - part: C4/C4-L00.qmd    # introduction to the bayesian-statistics-time-series-analysis
        chapters:          
          # 01_week-1-introduction-to-time-series-and-the-ar-1-process
          - C4/C4-L01.qmd      # 02_stationarity-the-acf-and-the-pacf
          - C4/C4-L01-Ex1.qmd  # Exercise 1 - stationarity-the-acf-and-the-pacf (Graded)
          - C4/C4-L02.qmd      # 03_the-ar-1-process-definition-and-properties
          - C4/C4-L02-Ex1.qmd  # Exercise 1 - stationarity-the-acf-and-the-pacf (Graded)
          - C4/C4-L03.qmd      # 04_the-ar-1-maximum-likelihood-estimation-and-bayesian-inference
          - C4/C4-L03-Ex1.qmd  # Exercise 1 - MLE and Bayesian inference in the AR(1) (Graded)
          - C4/C4-L03-Ex2.qmd  # Exercise 2 - MLE and Bayesian inference in the AR(1) (Graded)
          # C4\02_week-2-the-ar-p-process
          - C4/C4-L04.qmd      # 01_the-general-ar-p-process
          - C4/C4-L04-Ex1.qmd  # Exercise 1 - Properties of AR processes (Graded)
          - C4/C4-L05.qmd      # 02_bayesian-inference-in-the-ar-p
          - C4/C4-L05-Ex1.qmd  # Exercise 1 - the-ar-1-definitions-and-properties
          # C4\3 03_week-3-normal-dynamic-linear-models-part-i
          - C4/C4-L06.qmd      # 01_the-normal-dynamic-linear-model-definition-model-classes-and-the-superposition 
          - C4/C4-L07.qmd      # 02_bayesian-inference-in-the-ndlm-part-i 
          # C4\04_week-4-normal-dynamic-linear-models-part-ii
          - C4/C4-L08.qmd      # 01_seasonal-ndlms
          - C4/C4-L09.qmd      # 02_bayesian-inference-in-the-ndlm-part-ii
          - C4/C4-L09-Ex1.qmd  # Exercise 1
          - C4/C4-L10.qmd      #  capstone-project
          # - C4-QA-HW-ch2.qmd  # QA from Bayesian Forecasting and Dynamic Models
          # - C4-QA-HW-ch3.qmd  # QA from Bayesian Forecasting and Dynamic Models
          # - C4-QA-HW-ch4.qmd  # QA from Bayesian Forecasting and Dynamic Models
          # - C4-QA-PFW-ch1.qmd # QA from Prado
          # - C4-QA-PFW-ch2.qmd # QA from Prado
          # - C4-QA-PFW-ch3.qmd # QA from Prado
          # - C4-QA-PFW-ch4.qmd # QA from Prado
          # - C4-L11.qmd    # A Feynman Notebook
          - C4/C4-L12.qmd     #  NDLM faq
      # bayesian-statistics-capstone by Jizhou Kang
      - part: C5/C5-L00.qmd
        chapters:
          - C5/C5-L01.qmd  
          - C5/C5-L01-Ex1.qmd
          - C5/C5-L01-Ex2.qmd
          - C5/C5-L02.qmd
          - C5/C5-L02-Ex1.qmd
          - C5/C5-L02-Ex2.qmd
          #- C5/C5-L03.qmd 
          - C5/C5-L03.1.qmd 
          - C5/C5-L03.2.qmd 
          - C5/C5-L03.3.qmd 
      # bayesian-nonparametrics - Gaussian Processes by Tamara Broderick etc
      - part: C6/C6-L00.qmd 
        chapters:  
          - C6/C6-L01.qmd
          - C6/C6-L01.1-Surrogates-summary.qmd
          - C6/C6-L01.2-GPML-summary.qmd
      # bayesian-nonparametrics by Tamara Broderick and Larry Wasserman
      - part: C7/C7-L00.qmd 
        chapters:  
          - C7/C7-L01.qmd
          - C7/C7-L02.qmd       
      - part: C8/C8-L00.qmd 
      #- part: C7-L00.qmd 
      #  chapters:  
      #    - C7-L01.qmd
      - part: C90/L00.qmd # Gregory Plett's Kalman filtering bootcamp from Coursera.
        chapters:
          - C90/L111.qmd 
          - C90/L112.qmd 
          - C90/L113.qmd 
          - C90/L114.qmd 
          - C90/L115.qmd 
          - C90/L116.qmd 
          - C90/L121.qmd 
          - C90/L122.qmd 
          - C90/L123.qmd 
          - C90/L124.qmd 
          - C90/L125.qmd 
          - C90/L126.qmd 
          - C90/L127.qmd 
          - C90/L128.qmd 
          - C90/L131.qmd
          - C90/L132.qmd
          - C90/L133.qmd
          - C90/L134.qmd
          - C90/L135.qmd
          - C90/L136.qmd
          - C90/L137.qmd
          - C90/L138.qmd
          - C90/L141.qmd
          - C90/L142.qmd
          - C90/L143.qmd
          - C90/L144.qmd
          - C90/L145.qmd
          - C90/L146.qmd          
      - part: C99/L00.qmd # Jen Corcoran's course on Youtube
        chapters:
          - C99/L01.qmd 
          - C99/L02.qmd 
          - C99/L03.qmd 
  appendices:
      - A/A01.qmd
      - A/A02.qmd
      - A/A03.qmd
      - A/A05.qmd
      - A/A07.qmd    
      - A/A08.qmd
      - A/A09.qmd
      - A/A10.qmd
      - A/A11.qmd
      - A/A12.qmd
      - A/A13.qmd
      - A/A15.qmd
      - A/A16.qmd
      - A/A17.qmd
      - A/A18.qmd
      - A/A19.qmd
      - A/A20.qmd
      - references.qmd
  #   - summary.qmd

format:
  pdf:
    #engine: xelatex  # or lualatex
    engine: lualatex
    emoji: true
    #mainfont: "Times New Roman"
    toc: true
    toc-depth: 3
    toc-title: "Table of contents"
    lof: true
    lot: true
    mainfont: "Libertinus Serif"        # main text
    #mainfont: "EB Garamond"
    sansfont: "Libertinus Sans"          # sans serif
    #sansfont: "Open Sans"
    #monofont: "Noto Mono"
    monofont: "Libertinus Mono"          # monospaced font
    #mathfont: "TeX Gyre Termes Math"
    mathfont: "Libertinus Math"
    #mathfont: "Noto Sans Math"
    mainfontfallback:
      - "NotoColorEmoji:mode=harf" # for emojis
    from: "markdown+emoji"
    number-sections: true
    number-depth: 2
    papersize: a4
    #margin-right: 80mm
    geometry:
      - left=20mm
      - right=70mm
      - marginparwidth=65mm
      - marginparsep=5mm
      - top=20mm
      - bottom=20mm
      - heightrounded
    #  - outer=40mm
    #  - inner=30mm
      #- headsep=22pt
      #- headheight=11pt
      #- footskip=33pt
      #- ignorehead
      #- ignorefoot
      #- total={170mm,257mm}
    hyperrefoptions:
      - linktoc=all
      - pdfwindowui
      - pdfpagemode=FullScreen
    html-math-method: katex
    documentclass: scrreprt
    include-in-header:
      - text: |
          \usepackage{amsmath}
          \usepackage{cancel}
          \usepackage{undertilde}
          \usepackage{imakeidx}
          \usepackage{gensymb}
          \usepackage[x11names]{xcolor}
          \definecolor{grey}{rgb}{0.5,0.5,0.5}
          \usepackage[export]{adjustbox} 
          \makeindex[intoc=true, columns=3, columnseprule=true]
    #\includegraphics[max width=\linewidth]{image.png}
    #\hbadness=10000      
    #\geometry{a4paper, total={170mm,257mm}, left=20mm, top=20mm, bottom=20mm, right=20mm, marginparwidth=60mm }
    #\geometry{a4paper, total={170mm,257mm}, left=20mm, top=20mm, bottom=20mm, right=50mm}
    #\makeindex[intoc=true, columns=3, columnseprule=true, options=-s latex/indexstyles.ist]
    include-after-body: 
      - text: |
          \printindex
  # epub is too big for GitHub, so we need to add it as a local build profile.
  # epub:
  #   cover-image: cover.png

  html:



    #page-layout: custom
    grid:
      sidebar-width: 250px
      #body-width: 1200px
      #body-width: 600px
      margin-width: 300px
      #margin-width: 450px
      gutter-width: 1.5rem
    css: styles.css
    theme:
      light: [cosmo, theme.scss, custom.scss]
      dark: [cosmo, theme-dark.scss, custom.scss]
    include-after-body: js.html
    from: "markdown+emoji"

    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css" />
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>


    toc: true
    toc_float: true
    respect-user-color-scheme: true




    title-block-banner: images/banner_deep.jpg
    fig-caption: Notes about ... Bayesian Statistics
    #bibliography: bibliography.bib
    number-sections: true
    html-math-method: katex
    code-fold: false
    code-tools: true
    code-copy: true
    code-overflow: wrap
    code-annotations: hover
    lightbox: 
      match: auto
      effect: fade
      desc-position: bottom
      loop: true
      css-class: "my-css-class"
    sidebar:
        style: "docked"
        search: true
bibliography: references.bib

profile:
  default: development

highlight-style: a11y

crossref:
  custom:
    - kind: float
      reference-prefix: Video
      key: vid
      latex-env: video
  
knitr:
  opts_chunk:
    cache.path: _output/cache/


execute:
  freeze: auto  # re-render only when source changes


filters:
  - shinylive
  - pseudocode

pseudocode:
  caption-prefix: "Algorithm"
  reference-prefix: "Algorithm"
  caption-number: true
  caption-align: "left"
