---
title: "Appendix: Overview of Probability Theory and Linear Algebra"
---

This is a meta appendix.

I want to :

1. migrate and expand the material on foundations of probability theory into appendix.
1. add an appendix on multidimensional normal distributions based on the final chapter of [@west2013bayesian].
1. summarize operation on factors - based on material from coursera course on graphical models. (operations like marginalization, conditioning, etc. that we frequently meet in this specialization)
1. Create a shiny/gradio app for exploring:
    - distribution playground: the relationship between different types of probability distributions, sliders and graphs.
    - parameterization playground: different parameterizations of common distributions with copy paste code for use with PyMC/R etc.
1. Some results from linear algebra:
    - svd for PCA and dimensionality reduction
    - matrix decompositions and factorization
    - Jordan form
    - eigenvalues and eigenvectors
    - spectral theorem
    - matrix exponentiation
    - matrix factorization
    - linear operators
1. Some results for markov chains
    - stationary distributions
    - ergodic theorem
    - convergence of markov chains
    - doubly stochastic matrices
1. Some useful inequalities
    - Jensen's inequality
    - Cauchy-Schwartz inequality
    - triangle inequality
    - convexity and concavity
1. Proofs and explanation of the law of large numbers and the central limit theorem
1. Finally it would be great to create an interactive quiz app to keep the material fresh over time. The quiz should be independent of the course material  and ideally dynamic so that it may be published without honor code issues. There are lots of good questions on probability theory that can be used to deepen one's knowledge. I envision questions from books etc but answers in a polyglot environment R and Python and a unit test grading system!

also it would be best to have a list of examples, models, datasets we used in the specialization.

It would be neat to connect the discussion prompts to an LLM like chatGPT, so as to engage in a deeper discussion those topics.



