# Exponents & Logarithms {#sec-exponents--logarithms}

## Exponents {#sec-exponents}

Exponents are of the form $a^x$ where:

-   a (called the base) and
-   x (called the exponent) is any real number.

Recall that $a^0 = 1$. Exponents have the following useful properties

1.  $a^x· a^y = a^{x+y}$
2.  $(a^x)^y = a^{x·y}$

Note: that the first property requires that both terms have the same base a.

We cannot simplify $a^x ·b^y$ if $a \ne b$.

-   One common base is the number e which is approximately equal to 2.7183.
-   The function $e^x$ is so common in mathematics and has its own symbol $e^x = \exp(x)$.
-   Because $e > 0$ we have $e^x > 0$ for all real numbers x
-   $\lim_{x \to \infty} x = e^{−x} = 0$.

## Natural Logarithms {#sec-natural-logarithms}

We will need to manipulate long products of probabilities. Since there often comprise small fractions, their calculation on computers can be problematic due to the underflow of floats. We will therefore prefer to convert these products into sums of logarithms.

::: {#def-log-exp}
### The Logarithm

A log is the inverse of a power. We can use (@eq-log-def).

$$
y = a^x \implies log_a(y) = x
$$ {#eq-log-def}
:::

::: {#def-natural-log}
### The Natural log

The natural logarithm function has base e and is written without the subscript

$$
log_e(y) = log(y)
$$ {#eq-ln-def}
:::

::: {#thm-log-positive}
### Logs take positive values

logs only exist for values greater than 0

$$
\forall x(e^x > 0) \implies \exists \log(y) \iff {y > 0}
$$
:::

We can use the properties of exponents from the previous section to obtain some important properties of logarithms:

::: {#def-log-product}
### Log of a product

we can use @eq-log-product to convert a log of a product to a sum of logs.

$$
    log(x·y) = log(x) + log(y)
$$ {#eq-log-product}
:::

::: {#def-log-quotient}
### Log of a quotient

we can use @eq-log-quotient to convert a log of a quotient to a difference of logs. $$
    \log(\frac{x}{y}) = log(x) − log(y)
$$ {#eq-log-quotient}
:::

::: {#def-log-power}
### Log of a power

we can use @eq-log-power to convert a log of a variable raised to a power into the product.

$$
    \log(x^b) = b \cdot log(x)
$$ {#eq-log-power}
:::

::: {#def-log-one}
### Log of one

we can use (@eq-log-one) to replace a log of 1 with zero since \$\forall x(x\^0 = 1) \$

$$
    \log(1)=0
$$ {#eq-log-one}
:::

### Log of exponent

we can use (@eq-log-exp) to cancel a log of an exponent since the log is the inverse function of the exponent.

$$
exp(log(y)) = log(exp(y)) = y
$$ {#eq-log-exp}

::: {#exm-log}
### Logarithm

$$
    \begin{aligned}
    log \frac{5^2}{10}= 2 log(5) − log(10) ≈ 0.916.
    \end{aligned}
$$
:::

::: {#def-log-bases}
### Change of base for a log

we can use (@eq-log-bases) to change the base of a logarithm.

$$
    \log_b(a)=\frac{\log_c(a)}{\log_c(n)}
$$ {#eq-log-bases}
:::

::: {#def-log-derivative}
### Derivative of a Log

we can use (@eq-log-derivative) to differentiate a log.

$$
    \frac{d}{dx} \log_(x)=\frac{1}{x}
$$ {#eq-log-derivative}
:::

-   Because the natural logarithm is a monotonically increasing one-to-one function, finding the x which maximizes any (positive-valued function) $f(x)$ is equivalent to maximizing $log(f(x))$.
-   This is useful because we often take derivatives to maximize functions.
-   If $f(x)$ has product terms, then $log(f(x))$ will have summation terms, which are usually simpler when taking derivatives.
