---
title: "Appendix: Conjugate Priors"
---

## Conjugate Priors {#sec-conjugate-priors}



------------------------------------------------------------------------

| Likelihood                           | Conjugate prior                          | Posterior                                                                                                                                         | Posterior predictive                                                                                                                                                        |
|--------------------------------------|------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| $\text{Bernoulli}(p)$                | $\text{Beta}(\alpha,\beta)$              | ${\displaystyle \text{Beta}\left( \alpha +\sum _{i=1}^{n}x_{i},\,\beta +n-\sum _{i=1}^{n}x_{i}\right)}$                                           | ${\displaystyle \mathbb{P}r({\tilde {x}}=1)={\frac {\alpha '}{\alpha '+\beta '}}}$                                                                                                    |
| $\text{Binomial}(trials=m,p)$        | $\text{Beta}(\alpha,\beta)$              | ${\displaystyle \text{Beta}\left(\alpha +\sum _{i=1}^{n}x_{i},\,\beta +\sum _{i=1}^{n}N_{i}-\sum _{i=1}^{n}x_{i}\right)}$                         | ${\displaystyle \operatorname {BetaBin} ({\tilde {x}}|\alpha ',\beta ')}$                                                                                                   |
| $\text{NegBinomial}(fails=r)$        | $\text{Beta}(\alpha,\beta)$              | ${\displaystyle \text{Beta}\left( \alpha +rn,\beta + \sum _{i=1}^{n} x_{i}\right)}$                                                               | ${\displaystyle \operatorname {BetaNegBin} ({\tilde {x}}|\alpha ',\beta ')}$                                                                                                |
| $\text{Poisson}(rate=\lambda)$       | $\text{Gamma}(k,\theta)$                 | ${\displaystyle \text{Gamma}\left( k+\sum _{i=1}^{n}x_{i},\ {\frac {\theta }{n\theta +1}}\!\right)}$                                              | ${\displaystyle \operatorname {NB} \left({\tilde {x}}\mid k',{\frac {1}{\theta '+1}}\right)}$                                                                               |
| $\text{Poisson}(rate=\lambda)$       | $\text{Gamma}(\alpha,\beta)$             | ${\displaystyle\text{Gamma}\left( \alpha +\sum _{i=1}^{n}x_{i},\ \beta +n\!\right)}$                                                              | ${\displaystyle \operatorname {NB} \left({\tilde {x}}\mid \alpha ',{\frac {\beta '}{1+\beta '}}\right)}$                                                                    |
| $\text{Categorical}(probs=p,cats=k)$ | $\text{Dir}(\alpha_k)\mathbb{I}_{k\ge1}$ | ${\displaystyle \text{Dir}\left({ {\boldsymbol {\alpha }}+(c_{1},\ldots ,c_{k})}\right)}$                                                         | ${\displaystyle {\begin{aligned}\mathbb{P}r({\tilde {x}}=i)&={\frac {{\alpha _{i}}'}{\sum _{i}{\alpha _{i}}'}} \\ &={\frac {\alpha _{i}+c_{i}}{\sum _{i}\alpha _{i}+n}}\end{aligned}}}$ |
| $\text{Multinomial}(probs=p,cats=k)$ | $\text{Dir}(\alpha_k)\mathbb{I}_{k\ge1}$ | ${\displaystyle \text{Dir}\left({ {\boldsymbol {\alpha }}+\sum _{i=1}^{n}\mathbf {x} _{i}\!}\right)}$                                             | ${\displaystyle \operatorname {DirMult} ({\tilde {\mathbf {x} }}\mid {\boldsymbol {\alpha }}')}$                                                                            |
| $\text{Hypergeometric}(pop=n)$       | $\text{BetaBinomial}(\alpha,\beta,n=N)$  | ${\displaystyle \text{BetaBinomial}\left({\displaystyle \alpha +\sum _{i=1}^{n}x_{i},\,\beta +\sum _{i=1}^{n}N_{i}-\sum _{i=1}^{n}x_{i}}\right)}$ |                                                                                                                                                                             |
| $\text{Geometric}(p)$                | $\text{Beta}(\alpha,\beta)$              | ${\displaystyle\text{Beta}\left( \alpha +n,\,\beta +\sum _{i=1}^{n}x_{i}\right)}$                                                                 |                                                                                                                                                                             |

: Conjugate prior {#tbl-coj-priors .column-page-inset}
