---
title: "Bayesian Books in R & Python"
---

# Additional resources

there are many books in R and Python that can help you learn more about these languages and how to use them for data analysis. 

Here are some of the most popular books on R and Python:

## Books in R

- [R for Data Science](https://r4ds.hadley.nz/) by Hadley Wickham and Garrett Grolemund
- [Advanced R](https://adv-r.hadley.nz/) by Hadley Wickham
- [ggplot2: Elegant Graphics for Data Analysis (3e)](https://ggplot2-book.org/)
- [R Graphics Cookbook, 2nd edition](https://r-graphics.org/)
- [An Introduction to Statistical Learning](https://www.statlearning.com/)
- [Engineering Production-Grade Shiny Apps](https://engineering-shiny.org/)
- [Forecasting: Principles and Practice (3rd ed)](https://otexts.com/fpp3/)
- [Exploratory Data Analysis with R](https://bookdown.org/rdpeng/exdata/) Roger D. Peng
- [Modern R with the tidyverse](https://modern-rstats.eu/) by Bruno Rodrigues
- [Modern Statistics with R](https://www.modernstatisticswithr.com/) by Benjamin S. Baumer, Daniel T. Kaplan, and Nicholas J. Horton
- [Mastering Shiny](https://mastering-shiny.org/) by Hadley Wickham, Winston Chang, and Joe Cheng
- [Learning Statistics with R](https://learningstatisticswithr.com/) by Danielle Navarro
- [Text Mining with R](https://www.tidytextmining.com/) by Julia Silge and David Robinson


## Books in Python

- [An Introduction to Statistical Learning with python](https://www.statlearning.com/) by Gareth James, Daniela Witten, Trevor Hastie, and Robert Tibshirani
-  [Python for Data Analysis](https://wesmckinney.com/book/) by Wes McKinney of Pandas infamy  parquet and Apache Arrow
- [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/) by Jake VanderPlas
- [Think Stats](https://greenteapress.com/thinkstats2/thinkstats2.pdf) by Allen B. Downey
- [Think Bayes](https://greenteapress.com/thinkbayes2/thinkbayes2.pdf) by Allen B. Downey
- [Probabilistic Programming & Bayesian Methods for Hackers
](https://dataorigami.net/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/) by Cameron Davidson-Pilon
