---
subtitle: "Bayesian Statistics: Techniques and Models"
categories:
  - Bayesian Statistics
  - Monte Carlo Estimation
keywords:
  - Notes
---

# Techniques and Models

- In this course we learn to:
    - Efficiently and effectively communicate the results of data analysis.
    - Use statistical modeling results to draw scientific conclusions.
    - Extend basic statistical models to account for correlated observations using hierarchical models.
- We will build the following skills:
    - R Programming
    - Regression Analysis
    - Probability
    - Bayesian Statistics
    - Statistical Inference
    - Statistical Modeling
    - Statistical Methods
    - Data Analysis
    - Markov Model
    - Statistical Analysis
    - Probability Distribution
    - Simulations
- There are five modules in this course:

  1. **Statistical Modeling**: We will learn about the objectives of statistical models, how to build them, and how to use them to draw conclusions.
  2. **Markov Chain Monte Carlo**: We will learn about the Markov Chain Monte Carlo (MCMC) method, which is a powerful tool for sampling from complex probability distributions.
  3. **Common Statistical Models**: We will learn about common statistical models, such as linear regression, logistic regression, ANOVA, and more.
  4. **Count data and hierarchical models**: We will learn about count data and hierarchical models, which are used to model data that is grouped into different levels.
  5. **Capstone Project**: We will apply the skills we have learned in a capstone project, where we will build a statistical model to analyze a real-world dataset.

    - The course instructor is [Matthew Heiner](mheiner.github.io) UCSC who was a Doctoral Student at the University of California, Santa Cruz at the time of the course creation. He wrote his phd thesis [Bayesian Mixture Modeling and Order Selection for Markovian Time Series](https://escholarship.org/uc/item/7rx134js)

    
