---
title : 'Computational considerations for Mixture Models'
subtitle : 'Bayesian Statistics: Mixture Models'
categories:
  - Bayesian Statistics
keywords:
  - Mixture Models
  - Homework
  - Computational Considerations
  - MCMC  
---

::::: {.content-visible unless-profile="HC"}

::: {.callout-caution}
Section omitted to comply with the Honor Code
:::

:::::

::::: {.content-hidden unless-profile="HC"}

1. Consider a mixture of three Gaussian distribution with common identity covariance matrix and means 

$$
\begin{aligned}
\mu_1 &= (0,0)' \\
\mu_2 &= (1/3,1/3)' \\
\mu_3 &= (-2/3,1/3)'
\end{aligned}
$$

For an observation $x_i = (31,−23)'$ what is the value of $v_{i,2}$, the probability of the observation being generated by the second component (rounded to three decimal places)?

- [x] 0.928
- [ ] 1.000
- [ ] 0.072


2. True or False:  The starting value for the parameters of the mixture model in the EM algorithm could have an impact on the solution you obtain.

- [x] True
- [ ] False


3. True or False:  Consider a  Bayesian formulation of a Mixture Model that uses informative priors for all the parameters.  A Markov chain Monte Carlo (MCMC) algorithm for fitting such model will fail to work if no observations are allocated to a component of the mixture.

- [ ] True
- [x] False


:::::
