---
date: 2025-07-02
title: "Dirichlet Process"
subtitle: "Bayesian Statistics - Nonparametric Methods"
description: "Dirichlet Processes Tutorial"
categories:
  - Bayesian Statistics
  - Bayesian Nonparametric Methods
keywords:
  - Dirichlet Processes


---

::: {.callout-note}
## Credit
the following material is based on the [Gaussian Processes for Regression](https://tamarabroderick.com/tutorial_2024_cps-fr.html) and tutorial and code by Tamara Broderick. [](https://tamarabroderick.com/tutorial_2025_asa_cirs_webinar.html) Note that the [code](https://github.com/tbroderick/gps_tutorial/blob/2025asa_cirs/demos.ipynb) is under the [MIT license]()

:::

## Nonparametric Bayes

- Bayesian Nonparametrics (BNP) = Bayesian + Nonparametric
- The Bayesian part should be familiar to us at this point. Here is how we fuse data and beliefs during an experiment:

$$ 
\underbrace{\mathbb{P}r(parameters \mid data)}_{\substack{\text{our beliefs about the params.} \\ \text{at the end of the experiment}}} \propto \underbrace{\mathbb{P}r(data \mid parameters)}_{\substack{\text{data we collected}\\ \text{in our experiment}}} \underbrace{\mathbb{P}r(parameters)}_{\substack{\text{prior beliefs about params.} \\ \text{going into our experiment}}} \qquad
$$ {#eq-bnp-bayes-theorem} 
<!-- {#eq-bnp-bayes-theorem .column-page-right} -->

- [Non-parametric is a bit of a misnomer, it does not mean we don't have parameters but rather that we reduce our restrictions on parameters]{.mark} like:
   - from independence and identically distributed items to exchangeable^[order does not matter], and 
   - from fixed and finite to a growing and unbounded i.e. a potentially infinite family of parameters

This empowers us to model more complex data and phenomena there complexity grows as data accrues.

- Some Examples:
  - Topic modeling for Wikipedia articles 
  - Classifying/Clustering Species [@jin2012simple] c.f. [DNA Barcoding Reveals Diversity of Parasitoid Wasps in Great Smoky Mountains](https://entomologytoday.org/2024/07/17/dna-barcoding-reveals-diversity-of-parasitoid-wasps-in-great-smoky-mountains)
  - Density Estimation [@Escobar1995bayesian] [@Ghosal1999posterior]
  - Survival analysis curves
  - Fitness exercises [@Fox2014MediationBrainStructure]
  - Genetics [@EWENS197287], [@hartl2006principles]
  - Health issues in newborn babies [@Saria2010IntegrationOfEarly]
  - Social networks [@Lloyd2012RandomFunctionPriors] [@Miller2009NonparametricLatent]
  - Images [@Sudderth2008SharedSegmentation]
  - Time series [@fox2011bayesian], [@fox2009sharing]

## Nonparametric Bayes {#sec-NPB-nonparametric-bayes}

Next The speaker is vehemntly excited about definetti's theorem. This is a key theoretical motivation for BNP. And without the BNP the theorem is not that interesting or as easy to understand.

- A theoretical motivation: [De Finetti's Theorem](https://en.wikipedia.org/wiki/De_Finetti%27s_theorem)
- A data sequence is infinitely exchangeable if the distribution of any N data points doesn't change when permuted
- This is a much weaker assumption than independence and Exchangeability is the prerequisite for De Finetti's theorem:

$$
p(X_1, \ldots , X_N ) = p(X_{\sigma(1)} , \ldots , X_{\sigma(N)} )
$$ {#eq-BNP-exchangeablity}

- De Finetti’s Theorem (roughly): A sequence is infinitely exchangeable $\iff$, for all N and some distribution $P$ over parameters $\theta$,
$$
p(X_1, \ldots , X_N ) = \int_\theta \prod_{}^N p(X_n\mid\theta)P(d\theta)
$$

- Motivates:
  -  Parameters and likelihoods
  -  Priors
  -  "Nonparametric Bayesian" priors

- Note: that De Finetti's proved his theorem in 1931 but for finite exchangeability.
- In [@hewitt1955symmetric] Savage and Hewitt extended the result from finite to infinite exchangeability in 1955. 
- There were also a few other related results by Diaconis and Freedman in the 1970s.
- In [@aldous1983random] Aldous proved a more general for arrays 1983. 

## Generative Model {#sec-NPM-generative-model}

$$ 
  \mathbb{P}r(parameters \mid data) \propto \mathbb{P}r(data \mid parameters) \mathbb{P}r(parameters)
$$

- Finite Gaussian mixture model (K=2 clusters)
$$
z_n \stackrel{iid}{\sim} \text{Categorical}(\rho_1, \rho_2)
$$

$$
x_n \stackrel{indep}{\sim} \mathcal{N}(\mu_0, \Sigma)
$$

-  We don't know $\mu_1 , \mu_2$
$$
\mu_k \stackrel{iid}{\sim} \mathcal{N}(\mu_0, \sigma_0^2) \quad k=1,2
$$
-  Don’t know $\rho_1 , \rho_2$
$$
\rho_1 \sim \text{Beta}(\alpha_0, \beta_0) 
$$

$$
\rho_2 = 1 - \rho_1
$$

Inference goal: assignments of data points to clusters, cluster parameters

## Beta distribution review

\index{distribution!Beta}

$$
\text{Beta}(\rho \mid \alpha_1, \alpha_2) = \frac{\Gamma(\alpha_1 + \alpha_2)}{\Gamma(\alpha_1)\Gamma(\alpha_2)} \rho^{\alpha_1 - 1} (1 - \rho)^{\alpha_2 - 1} 
$$

-  $\alpha_1, \alpha_2 > 0$
-  $\rho \in [0,1]$

-  Gamma function $\Gamma$
  - integer m: $\Gamma(m+1) = m!$
  - for x > 0: $\Gamma(x+1) = x\Gamma(x)$
  - What happens?
    - $a = a_1 = a_2 \to 0$
    - $a = a_1 = a_2 \to \infty$
    - $a_1 > a_2$
- Beta is conjugate to Cat

$$
\rho \sim \text{Beta}(\alpha_1, \alpha_2),\qquad z \sim \text{Cat}(\rho_1, \rho_2)
$$

$$
p(\rho_1 , z) \propto \rho_1^{\mathbb{1}_{z=1}} (1 - \rho_1 )^{\mathbb{1}_{z=2}} \rho_1^{a_1 -1} (1 - \rho_1 )^{a_2 -1}
$$


$$
p(\rho_1 , z) \propto \rho_1^{\mathbb{1}_{z=1-1}} (1 - \rho_1 )^{\mathbb{1}_{z=2}-1} \propto \text{Beta}(\rho_1 \mid a_1 + \mathbb{1}_{z=1}, a_2 + \mathbb{1}_{z=2})
$$
