---
date: 2025-07-02
subtitle: "Bayesian Statistics - Capstone Project"
description: "Capstone Project: Introduction"
categories:
  - Bayesian Statistics
  - Capstone Project
keywords:
  - Time Series
---

# Bayesian Non-Parametric Models

Here is a question I raised in my Feynman Notebook:

1. Will we learn about Gaussian Processes/Neural Networks in this course?
   - This is a type of Bayesian Non-parametric and we don't cover these in the specialization. However Abel Rodriguez, the instructor of the third course on mixture model has a [short course](https://users.soe.ucsc.edu/~abel/website/Teaching.html)
   - Herbert Lee wrote a [Bayesian Nonparametrics via Neural Networks](https://www.amazon.com/Bayesian-Nonparametrics-Networks-Statistics-Probability/dp/0898715636) on the subject.
   - [Athanasios Kottas](https://users.soe.ucsc.edu/~thanos/) of UCSC has made the following notes available on his website:   
    - Tutorial on [Nonparametric Bayesian density regression:
modeling methods and applications](https://users.soe.ucsc.edu/~thanos/BNPnet_tutorial_notes.pdf)
    - Short course on [Applied Bayesian Nonparametric Mixture Modeling](https://users.soe.ucsc.edu/~thanos/NPB_course_notes.pdf) with [references (16 pages)](https://users.soe.ucsc.edu/~thanos/NPB_course_references.pdf) with 52 of them being his own papers.


This is not available as a course on Coursera and isn't a part of the specialization which ended in the last course. So this notes are my own personal notes gathered from tutorials and courses I found on the web.


- Tamara Broderick's Gaussian Processes for Regression tutorials from 
  - 2025 [slides](https://tamarabroderick.com/tutorial_2016_mlss_cadiz.html) [video](https://www.youtube.com/watch?v=szuREe_brxw&ab_channel=AmstatVideos) and [code](https://github.com/tbroderick/gps_tutorial/tree/2025asa_cirs)
  - 2024 [slides](https://tamarabroderick.com/tutorial_2024_cps-fr.html) 
- Tamara Broderick Tutorial on the Dirichlet Process from MLSS 2016 ML the University of Cádiz in Cádiz, Spain [link](https://tamarabroderick.com/tutorial_2016_mlss_cadiz.html)

## Overview

- In this course we learn to:
  - [x] Demonstrate a wide range of skills and knowledge in Bayesian statistics.
  - [x] Explain essential concepts in Bayesian statistics.
  - [x] Apply what you know to real-world data.
- We will build the following skills:
  - Probability Distribution (Dirichlet, Beta)
  - Bayesian Statistics
- There are currently five modules planned in this course:
  1. **Gaussian Processes for Regression**: We will focus on Gaussian processes as a flexible prior distribution for regression problems, allowing us to capture complex relationships in the data.
      1. Gaussian process model [slides](https://tamarabroderick.com/files/broderick_2024_cps-fr_part_i.pdf)
      2. Gaussian process regression [slides](https://tamarabroderick.com/files/broderick_2024_cps-fr_part_ii.pdf)
      3. Squared exponential kernel and observation noise [slides](https://tamarabroderick.com/files/broderick_2024_cps-fr_part_iii.pdf)
      4. What uncertainty are we quantifying? [slides](https://tamarabroderick.com/files/broderick_2024_cps-fr_part_iv.pdf)
      5. A list of resources: [slide](https://tamarabroderick.com/files/broderick_2024_cps-fr_resources.pdf)
  2. **Dirichlet process**: We will explore the Dirichlet process as a prior distribution over probability measures, allowing for flexible modeling of unknown distributions.
    - The Beta distribution
    - The Dirichlet Distribution
    - Dirichlet process
    - Polya urn scheme
    - Stick breaking representation
    - Dirichlet process mixture models
    - Hierarchical Dirichlet processes
  3. **Chinese restaurant process**: We will introduce the Chinese restaurant process as a metaphor for the Dirichlet process, providing an intuitive understanding of how it works.
  4. **Indian buffet process**: We will discuss the Indian buffet process as a model for representing the distribution of features in a dataset, allowing for flexible and scalable modeling of complex data structures.
  5. **Pitman-yor process**: We will examine the Pitman-yor process as a generalization of the Dirichlet process, providing a more flexible framework for modeling distributions with power-law behavior.
  6. **Polya tree**: We will explore the Polya tree as a nonparametric prior distribution for modeling probability distributions, allowing for flexible and adaptive modeling of complex data structures.
  



## Prerequisite skill checklist  :spiral_notepad: 


:::: {.callout-note collapse="true"}
## Prerequisite skill checklist

### Bayesian Statistics
- [x] Interpret and specify the components of Bayesian statistical models: likelihood, prior, posterior.
- [x] Explain the basics of sampling algorithms, including sampling from
standard distributions and using MCMC to sample from non-standard
posterior distributions.
- [x] Assess the performance of a statistical model and compare competing
models using posterior samples.
- [x] Coding in R to achieve the above tasks.

### Mixture Models
- [x] Define mixture model.
- [x] Explain the likelihood function associated with a random sample
from a mixture distribution.
- [x] Derive Markov chain Monte Carlo algorithms for fitting mixture models.
- [x] Coding in R to achieve the above tasks.

### Time Series Analysis
- [x] Define time series and stochastic processes (univariate, discrete-time, equally-spaced)
- [x] Define strong and weak stationarity
- [x] Define the auto-covariance function, the auto-correlation function
(ACF), and the partial autocorrelation function (PACF)
- [x] Definition of the general class of autoregressive processes of order p.
:::

## Some References:

1. Gaussian Processes @rasmussen2006gaussian
2. Surrogates @gramacy2020Surrogates
3. A Tutorial on Bayesian Optimization @frazier2018tutorialbayesianoptimization
  - It builds a surrogate for the objective and quantifies the uncertainty in that surrogate using a Bayesian machine learning technique, Gaussian process regression, and then uses an acquisition function defined from this surrogate to decide where to sample
  - three common acquisition functions:
    - expected improvement
    - entropy search
    - knowledge gradient
4. Bayesian Nonparametrics via Neural Networks @lee2000bayesiannonparametrics
6. All of nonparametric bayesian statistics [@wasserman2006all]


So after going over the first two tutorials by Tamara Broderick, I feel like I have a good understanding of Gaussian Processes and the Dirichlet Process. This seems like a very good starting point for learning more. 

I listened felt kind of more comfortable to listen and read  Larry Wasserman's on this BNP and als FNPs. IT seems like it is also usefll to go over Frequents non-parametric methods as they are different from Bayesian non-parametric methods. (For parametric models, there is a good case that Bayesian and Frequentist methods are not only similar but if one uses a reference prior, they can lead to the same results. 
Wasserman makes a strong point when explaining non parametric CDF  that the Bayesian and Frequentist approaches are doing different things and that the distinction is interesting.


Papers - most of the work on BNP is covered in papers. 
- In fact in [@wasserman2006all] points out that he doesn't give proofs for many of the results and point us to the original papers.
- Tamara Broderick's tutorial also point out that there were two eras of research in BNP. The first in which there were many theoretical results and a second are after MCMC methods became strong enough to handle the computational complexity of BNP models. In the second era people focused more on using MCMC to do inference on many of the models developed in the first era.
- At this point I want to get good enough to do inference on some of these models and then to adapt them to a few problems I have in mind. Like Lewis signaling, Elasticity based Pricing, and use in Bayesian RL agents.
- So while I don't think these are easy reads I will
  1. first try to get a better understanding of the key concepts and ideas. 
  2. Try to do excercises in the notes and tutorials.
  3. Try to implement some of the models in R and Python.
  4. Try to use AI to breeze through the most important papers

So far [@ferguson1973bayesian] and [@Sudderth2008SharedSegmentation] seem the most intersting papers to start with for Dirichlet Processes.

Also the papers on De Finetti's theorem and exchangeability are important yet very challenging. Tamara Broderick's tutorial talkes about this result. On the other hand Larry Wasserman blurted out that you can't use Bayes theorem to do inference when the measure is not [sigma-finite](https://en.wikipedia.org/wiki/%CE%A3-finite_measure). So we need to be careful when using these models. This burst a bunch of bubbles. But like how I felt about [Pappus's hexagon theorem](https://en.wikipedia.org/wiki/Pappus%27s_hexagon_theorem) being correct in projective geometry, even when we discard the parallel postulate, I feel like this is a good thing. We see once again that Bayes theorem is not the result about which all of Bayesian statistics revolves around.
We see once again the power of conjugacy and the definition of Joint distributions as conditional probabilities are more fundamental. And we also see that MCMC can help us do inference in many cases were we can't use Bayes and where even Conjugacy breaks down. We can use sampling to get a good enough approximation to the posterior even when the measure we want to consider is not sigma-finite. Finally MCMC is also very useful for RL and one of my goals is to use BNP methods to make better RL agents.