
## Poisson distribution {#sec-poisson-distribution}

### Stories

::: {.callout-note}
#### Poisson Parametrization

The Poisson distribution arises when modeling the number of successes of independent and identically distributed (IID) events in a fixed interval of time or space, occurring at a constant rate $\lambda$. Let $X$ represent the count of the number of phone calls received at a call center in a given interval, such as an hour, with the parameter $\lambda$ corresponding to the average rate at which events occur in that interval. Then $X$ is said to have the Poisson distribution with parameter $\lambda$, and we denote this as $X \sim \mathrm{Pois}(\lambda)$.

Perhaps a better way to think about the Poisson distribution is as follow

We want to model the number of events occurring in a fixed interval of time or space. We can subdivide the interval and model each unit using a Bernoulli trial. As the number of subdivisions increases we should be better capture a unit in which there will only be at most one event occurring which is out main requirement. To facilitate this as we subdivide we need to decrease the probability of an event occurring in each subdivision such that the expected number of events in the entire interval np remains constant. When we go to the limit we end up with the Poisson distribution which now only has one parameter $\lambda$ which is the expected number of events in the interval i.e. the product of the number of subdivisions and the probability of an event occurring in each subdivision. 

We may think of the Poisson distribution as the limit of a Binomial distribution where the number of trials goes to infinity and the probability of success goes to zero such that the expected number of successes remains constant.
:::

$$
X \sim \mathrm{Pois}(\lambda) 
$$ {#eq-poisson-rv}

::: {#vid-geometric-distribution .column-margin .content-hidden when-format="pdf"}
{{< video https://youtu.be/yIPFA1sk5NA >}}

The Poisson Distribution
:::

### R.V. Checklist

-   Counts discrete events
    - Individual events are bernoulli trails     
    - Each event is independent of other events
    - There is only one event per sub-interval
-   Fixed amount of time or space in which the events can occur
-   Events occur at a constant rate $\lambda$ (events per interval)

### Examples

::: {#exm-poisson-emails}
The number of emails you receive in an hour. There are a lot of people who could potentially email you at that hour, but it is unlikely that any specific person will actually email you at that hour. Alternatively, imagine subdividing the hour into milliseconds. There are $3.6×106$ seconds in an hour, but in any specific millisecond, it is unlikely that you will get an email.
:::

::: {#exm-poisson-chocolate-chips}
The number of chips in a chocolate chip cookie. Imagine subdividing the cookie into small cubes; the probability of getting a chocolate chip in a single cube is small, but the number of cubes is large.
:::

::: {#exm-poisson-earthquakes}
The number of earthquakes in a year in some regions of the world. At any given time and location, the probability of an earthquake is small, but there are a large number of possible times and locations for earthquakes to occur over the course of the year.
:::

::: {#exm-poisson-failures}
Count of component failures per week
:::

::: {#exm-poisson-heart-valves}
Estimating the failure rate of artificial heart valves,
:::

::: {#exm-poisson-crime-prevalence}
Estimating the prevalence of violent crimes in different districts,
:::

::: {#exm-poisson-autism-prevalence}
Approximating the binomial which is, itself, being used to explain the prevalence of autism in the UK.
:::

### Moments

$$
\mathrm{E}(X) = \lambda
$$

$$
\mathrm{V}ar(X) = \lambda
$$



### Probability mass function (PMF)

$$
f(x \mid \lambda) = \frac{\lambda^x e^{-\lambda}}{x!}
$$ {#eq-poisson-PMF}

### Cumulative distribution function (CDF)

$$
F(x \mid \lambda) = \frac{\Gamma(\lfloor x+1\rfloor,\lambda)}{\lfloor x \rfloor !} \qquad \text{CDF}
$$ {#eq-poisson-cdf}

- where
    $\Gamma(u,v)=\int_{v}^{\infty}t^{u-1}e^{-t} \mathrm{d}t$ is the upper incomplete gamma function.
    $\lfloor x \rfloor$ is the floor function (rounds down reals to nearest smaller integer)
