
## Multinomial Distribution {#sec-multinomial-distribution}

The Multinomial distribution is a generalization of the Binomial. Whereas the Binomial distribution counts the successes in a fixed number of trials that can only be categorized as success or failure, the Multinomial distribution keeps track of trials whose outcomes can fall into multiple categories, such as excellent, adequate, poor; or red, yellow, green, blue.

### Story

Multinomial distribution. Each of N objects is independently placed into one of $k$ categories. An object is placed into category $j$ with probability $p_j$ ,P where the $p_j$ are non-negative and $\sum^k_{j=1} p_j = 1$. Let $X_1$ be the number of objects in category 1, $X_2$ the number of objects in category 2, etc., so that $X_1 + \dots + X_k = n$. Then $X = (X_1 , \dots , X_k )$ is said to have the Multinomial distribution with parameters $n$ and $p = (p_1 , \dots , p_k )$. 

We denote this as 

$$
X \sim \mathcal{Mult}_k(n, p)
$$ {#eq-multinomial-notation}

We call X a *random vector* because it is a vector of random variables. The joint PMF of X can be derived from the story.

### Examples

-   Blood type counts across n individuals
-   Numbers of people voting for each party in a sample

### Moments

$$
\mathrm{E}(X_i) = n p_i \text{, }\forall i
$$

$$
var(X_i) = n p_i (1-p_i) \text{, }\forall i
$$ 

$$
cov(X_i,X_j) = -n p_i p_j \text{, }\forall i\neq j
$$

### Probability Mass Function (PMF)

$$
f(x_1,x_2,\dots,x_d \mid n,p_1,p_2,\dots,p_d) = \frac{n!}{x_1 ! x_2 ! \dots x_d !} p_1^{x_1} p_2^{x_2}\dots p_d^{x_d}
$$