
## Hypergeometric distribution {#sec-hypergeometric-distribution}

::: {#vid-hyper-geometric-distribution .column-margin .content-hidden when-format="pdf"}
{{< video https://youtu.be/UgqQc6epZnc title="Hypergeometric Distribution" >}}

The Hypergeometric Distribution
:::

### Stories

::: {.callout-note}
### Story 1 - Urn Model

The beta-binomial distribution with parameters $\alpha$ success rate and $\beta$ failure and $n$ the number of trials can be motivated by an Pólya urn model.

Imagine a trial in which a ball is drawn without replacement from urn containing $\alpha$ white balls and $\beta$ black balls. If this is repeated n times, then the probability of observing x white balls follows a hypergeometric distribution with parameters $n$, $\alpha$ and $\beta$.


If the random draws are with simple replacement (no balls over and above the observed ball are added to the urn), then the distribution follows a binomial distribution and if the random draws are made without replacement, the distribution follows a hypergeometric distribution.
:::


### Examples

-   $k$ white balls from an in Urn without replacement
-   capture-recapture
-   Aces in a poker hand

### Story

Consider an urn with w white balls and b black balls. We draw n balls out of the urn at random without replacement, such that all w+b samples are equally likely. Let X be the number of white balls in n the sample. Then X is said to have the Hypergeometric distribution with parameters w, b, and n; we denote this by $X \sim \mathcal{HG}(w, b, n)$ or $X \sim \mathrm{HyperGeom}(w, b, n)$ or 