---
title: "Generalized (Moore-Penrose) Inverse"
subtitle: "Appendix"
description: "This appendix explains the Moore-Penrose inversion and the Cholesky decomposition, which are methods for solving linear equations efficiently using linear algebra."
categories: 
    - "numerical linear algebra"
keywords: 
    - "Moore-Penrose inversion"
    - "Cholesky decomposition"
    - "linear equations"
    - "matrix factorization"
    - "numerical stability"
    - "linear algebra"
---

The Moore-Penrose inversion and the Cholesky decomposition are two important methods in computational linear algebra for solving linear equations efficiently. They are widely used in various applications, including statistics, machine learning, and numerical analysis.

## Properties of transpose {#sec-linear-algebra-results}

transpose of a row vector is a column vector and vice versa:


$$
kA^{T} = {kA}^\top \qquad \text{scalar multiplication }
$$ {#eq-scalar-multiplication}


$$
(A^{T})^\top = A \qquad \text { involution }
$$ {#eq-transpose-of-transpose}

$$
(A+B)^{T} = A^\top + B^\top \qquad\text {  distributivity under addition }
$$ {#eq-distributivity-of-transpose}

$$
(AB)^\top = B^\top A^\top \qquad\text {   anti }
$$ {#eq-transpose-of-product}

note that we swap the order of the matrices in the product when taking the transpose.

if A is a square matrix, then the following are equivalent:
$$
Sq = A^\top*A = A*A^\top 
$$
where $Sq$ is a symmetric positive definite matrix.

$$
Sk = A^\top*A = A*A^\top
$$

## Full Rank {#sec-full-rank}

A matrix is said to be of full row rank if its rows are linearly independent, and it is of full column rank if its columns are linearly independent. A matrix is said to be of full rank if it is either of full row rank or full column rank.

## Generalized (Moore-Penrose) Inverse {#sec-moore-penrose}

The Moore-Penrose inversion is a method for computing the pseudoinverse of a matrix. The pseudoinverse is a generalization of the inverse of a matrix that can be used to solve linear equations when the matrix is rectangular, not-invertible or even singular.

::: {#def-moore-penrose-inverse-1}

## Definition of the Moore-Penrose Inverse 1

The Moore–Penrose inverse of the $m × n$ matrix $A$ is the $n × m$
matrix, denoted by $A^+$, which satisfies the conditions

$$
AA+ A = A
$$ {#eq-moore-penrose-1}

$$  
A^+AA^+ = A^+
$$ {#eq-moore-penrose-2}

$$
(AA^+ )' = AA^+ 
$$ {#eq-moore-penrose-3}

$$
(A^+A)' = A^+A
$$ {#eq-moore-penrose-4}

:::


An important features of the Moore–Penrose inverse, is that it is uniquely defined.


Corresponding to each m × n matrix A, one and only one n × m matrix $A^+$ exists satisfying conditions (@eq-moore-penrose-1)–(@eq-moore-penrose-4).

Definition @def-moore-penrose-inverse-1 is the definition of a generalized inverse given by Penrose (1955).

The following alternative definition, which we will find useful on some occasions, utilizes properties of the Moore–Penrose inverse that were first illustrated by Moore (1935).

::: {#def-moore-penrose-inverse-2}
## Definition of the Moore-Penrose Inverse 2

Let $A$ be an $m × n$ matrix. Then the Moore–Penrose inverse of $A$ is the unique $n × m$ matrix $A^+$ satisfying

$$
AA^+ = P_{R(A)}
$$ {#eq-moore-penrose-5}

$$
A^+ A = P_{R(A^+)}
$$ {#eq-moore-penrose-6}

where $P_{R(A)}$ and $P_{R(A^+)}$ are the projection matrices of the range spaces of $A$ and $A^+$, respectively.
:::


::: {#thm-properties-moore-penrose-inverse}
## Properties of the Moore-Penrose inverse 

Let A be an $m \times n$ matrix. Then:

a. $(\alpha_A)^+ = \alpha^{-1} A^+ , \text{ if } \alpha \ne 0 \text{ is a scalar}$
b. $(A^\top)^+ = (A^+)^\top$ 
c. $(A^+)^+ = A$
d. $A^+ = A^{-1} ,\text{if A is square and nonsingular}$
e. $(A^\top A)^+ = A^+ A^\top$ and $(AA^\top)^+ = A^\top A^+$
f. $(AA^+)^+ = AA^+$ and $(A^+ A)^+ = A^+ A$
g. $A^+ = (A^\top A)^+ A^\top = A^\top (AA^\top)^+$
h. $A^+ = (A^\top A)^{-1} A^\top$ and $A^+ A = I_n , \text{ if } rank(A) = n$
i. $A^+ = A^\top (AA^\top)^{-1}$ and $AA^+ = I_m , \text{ if } rank(A) = m$
j. $A^+ = A^\top$  if the columns of A are orthogonal, that is, $A^\top A = I_n$
:::


::: {#thm-rank}
##  Rank of Moore-Penrose Inverse

For any $m \times n$ matrix $A$, $\text{rank}(A) = \text{rank}(A^+) = \text{rank}(AA^+) = \text{rank}(A^+ A)$.
:::


::: {#thm-symmetric-moore-penrose-inverse}
##  Symmetric Moore-Penrose Inverse


Let A be an m × m symmetric matrix. Then

1. $A^+$ is also symmetric,
2. $AA^+$ = $A^+A,
3. $A^+$ = $A$, if $A$ is idempotent.
:::


<!-- add about use in MLE -->
The Moore-Penrose inverse is particularly useful in maximum likelihood estimation (MLE) for linear models. In MLE, we often need to solve linear equations of the form $Ax = b$, where $A$ is the design matrix and $b$ is the response vector. If $A$ is not full rank or is not square, we can use the Moore-Penrose inverse to find a solution that minimizes the residual sum of squares.

In the context of MLE, the Moore-Penrose inverse allows us to obtain parameter estimates even when the design matrix is singular or when there are more predictors than observations. This is achieved by projecting the response vector onto the column space of the design matrix, leading to a solution that is consistent and has desirable statistical properties.

we start with:

$$
y = \mathbf{X} \mathbf{\beta} + \mathbf{\varepsilon} \qquad \mathbf{\varepsilon} \sim \mathcal{N} (0, v\mathbf{I})
$$

we want MLE of $\mathbf{\beta}$, which is given by:
$$
\hat{\mathbf{\beta}}_{NKE} = (\mathbf{X}^\top \mathbf{X})^{-1} \mathbf{X}^\top y
$$

Also in the bayesian setting we can show that MLE is equivalent to minimizing the negative log-likelihood function, under a uniform prior on $\mathbf{\beta}$, which is equivalent to minimizing the residual sum of squares.

we can show that if we use least squares AKA l_2 norm minimization, we will end up with the Moore-Penrose inverse to find the solution:

we can write this explicitly as:

$$
\mathbb{E}_{l_2}(\mathbf{\beta}) = \frac{1}{2} \sum (y - \mathbf{\beta}^\top \mathbf{X})^2
$$
