## Structure of the Book

- [ ] Update the course files and so there is just lesson one per file
- [ ] each section should have a unique id starting with #sec
- [ ] update the navigation to reflect the new structure of the course.

## Goals tracking

- [ ] lessons should start with a goals section with links to the relevant sections in the notes.

which should look like this:

::: {.callout-note collapse="true"}
## Learning Objectives

-   [x] Perform maximum likelihood estimation[\#](#l1g1)
-   [x] Perform Bayesian inference [\#](#l1g1)

:::

with the goal demarcated as:

[text of the goal]{#l1g_1 .mark}

where l1 is the lesson number and g1 is the goal number.


## Code Blocks

- [ ] update each file so all code blocks have a unique label id starting with #lst unless the code generates a figure in which case it should start with #fig.
- [ ] if code blocks do many things better to split them up so that each code block does one thing.

## Figures

- [ ] Update the files so that the figures all have a unique id starting with #fig

## Profile Book Build

- [ ] profile book build so that it can be rendered quickly (some MCMC sims take a long time to run). The goal here is a render in less than 10 minutes!
- [ ] alternatively, I could split this into one book per course as it is likely to be 1000 pages long already.

## Docker Setup

- [ ] create a docker file that handles
    - [ ] installation of required R packages
    - [ ] installation of required Python packages
    - [ ] installing the quarto 
    - [ ] installing latex
    - [ ] cloning the repo 
    - [ ] doing a render of the book
    

## Bibliography

- [x] add more books on mixtures in A12.qmd
- [ ] non parametric methods - gaussian processes.