---
date: 2025-07-02
title: "Dirichlet Process"
subtitle: "Bayesian Statistics - Nonparametric Methods"
description: "Dirichlet Processes Tutorial"
categories:
  - Bayesian Statistics
  - Nonparametric Methods
keywords:
  - Dirichlet Processes

---

::: {.callout-note}
## Credit

The following material is based on the [Nonparametric Bayes Tutorial](https://https://tamarabroderick.com/tutorial_2016_mlss_cadiz.html) that took place in the 2016 ML the University of Cádiz in Cádiz, Spain. Which focuses primarily on the Dirichlet Process and related processes. There is so much material on BNP and non-parametric methods out there it is hard to get started. The speaker has a [blog](https://tamarabroderick.com/blog/) with more material on this and other topics. 

I find that MIT Tenured Professor, Tamara Broderick's explanations are very clear and accessible. She uses simple motivating examples, she shares the basis of how she has built her intuition for the topic. Most significantly she is very enthusiastic about the BNP which I find inspiring and contagious.

I found the videos hard to follow at times, as she is talking fast (a good thing). So I watched them a number of times at my leisure. Many times I found myself surprised by things she said. But each time I checked I not only learned something new but was able to put aside some of my misconceptions. 

I want to develop the generative and behavioral stories that help us connect the abstract stochastic processes to problems we might want to solve in the real world. Again this is something I have already stated on in earlier notes in course 1 and the appendices on distributions.
:::