{
  "hash": "9791659e47188a1d98e06e8c13351db6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ndate: 2024-11-04\ntitle: \"The AR($p$) process\"\nsubtitle: Time Series Analysis\ndescription: \"The AR($p$) process, its state-space representation, the characteristic polynomial, and the forecast function\"\ncategories: \n  - Bayesian Statistics\n  - Time Series\nkeywords: \n  - Autoregressive Models\n  - time series\n  - stability\n  - order of an AR process \n  - characteristic lag polynomial\n  - autocorrelation function\n  - ACF\n  - partial autocorrelation function\n  - PACF\n  - smoothing\n  - State Space Model\n  - ARMA process\n  - ARIMA\n  - moving average\n  - AR($p$) process  \n  - R code\n  - notes\n  - Coursera \n---\n\n::: {.callout-note}\n\n## Learning Objectives\n\n- [x]  Define an **AR($p$)**, or [autoregressive process of order p]{.mark} and use **R** to obtain samples from such process\n- [x] Define ARIMA (autoregressive moving average) models (honors)\n- [x] Perform posterior inference for the AR($p$) under the conditional likelihood and the reference prior\n- [x]   Perform a full data analysis in R using an AR($p$) including\n   - likelihood estimation,\n   - Bayesian inference,\n   - model order selection,\n   - forecasting.\n- [x]  Explain the relationship between the *AR characteristic polynomial*, *the forecast function*, *the ACF* and *the spectral density* in the case of an AR($p$)\n\n:::\n\n## AR($p$) Definition and State-space Representation  :movie_camera:  {#sec-arp-defn-state-space-rep}\n\n![AR($p$) process, characteristic polynomial, stability, stationarity and MA representation ](images/m2_0001.png){#fig-ar-p-state-space-representation .column-margin  group=\"slides\" width=\"53mm\"}\n\nThe under tildes used in the slides denote a vector or a matrix rather than a statistical property. They are usually denoted via bold fonts and not by under tildes which have other meanings too so for the sake of clarity I have replaced them with bold font in the outline. I provide detailed derivation in this section but there is a shorter outline in @sec-arp-review which may be easier to review once you know the derivations.\n\nIn this segment we will see two important representations of the **AR($p$)** process. \nYou can follow along in [@prado2000bayesian ch. 2]\n\n### AR($p$) definition {#sec-arp-definition}\n\n[**AR($p$)**, shorthand, for *Auto Regressive Process of order p* which generalizes the **AR(1)** process by defining the current time step in terms of the previous $p$ time steps. We denote the number of parameter required to characterize the current value as $p$, and call it the **order** of the autoregressive process. The order tells us how many *lags* we will be considering.]{.mark}. \n[**order p**]{.column-margin}\nTherefore the **AR(1)** process as a special case of the more general **AR($p$)** process with $p=1$.\n\n[**AR($p$)**]{.column-margin}\nWe will assume AR($p$) has the following structure:\n\n$$\n\\textcolor{red}{y_t} = \\textcolor{blue}{\\phi_1} \\textcolor{red}{y_{t-1}} + \\textcolor{blue}{\\phi_2} \\textcolor{red}{y_{t-2}} + \\ldots + \\textcolor{blue}{\\phi_p} \\textcolor{red}{y_{t-p}} + \\textcolor{grey}{\\varepsilon_t}, \\qquad \\textcolor{grey}{\\varepsilon_t} \\overset{\\text{iid}}{\\sim} \\mathcal{N}(0,v) \\quad \\forall t\n$$ {#eq-ar-p-annotated}\n\nwhere:\n\n-   $\\textcolor{red}{y_t}$ is the value of the time series at time t\n-   $\\textcolor{blue}{\\phi_{1:p}}$ are the AR coefficients\n-   $\\textcolor{grey}{\\varepsilon_t} \\overset{\\text{iid}}{\\sim} \\mathcal{N}(0,v) \\quad \\forall t$  is a **white noise process** with zero mean and constant variance $v$.\n\n\n### AR($p$) Characteristic Polynomial {#sec-arp-characteristic-polynomial}\n\nA central outcome of the autoregressive nature of the  **AR($p$)** is due to the properties the AR characteristic polynomial $\\Phi$. [$\\Phi$ AR characteristic polynomial]{.column-margin} This is defined as : \n\nrecall the backshift operator $B$ is defined as:\n\n$$\n\\operatorname{B} y_t = y_{t-1}\n$$ \n\nso that \n\n$$\n\\operatorname{B}^j y_t = y_{t-j}\n$$ \n\nWe now use the backshift operator to rewrite the **AR($p$)** as a inhomogeneous linear difference equation:\n$$\n\\begin{aligned}\n       y_t &= \\phi_1 y_{t-1} + \\phi_2 y_{t-2} + \\ldots + \\phi_p y_{t-p} + \\varepsilon_t  && \\text{(AR($p$) defn.)} \\newline\n       y_t &= \\phi_1 \\operatorname{B} y_t + \\phi_2 \\operatorname{B}^2 y_t + \\ldots + \\phi_p \\operatorname{B}^p y_t + \\varepsilon_t && \\text{(B defn.)} \\newline\n\\varepsilon_t &= y_t - \\phi_1 \\operatorname{B} y_t - \\phi_2 \\operatorname{B}^2 y_t - \\ldots - \\phi_p \\operatorname{B}^p y_t    && \\text{(rearranging)} \\newline\n\\varepsilon_t  &= (1- \\phi_1 \\operatorname{B} - \\phi_2 \\operatorname{B}^2 - \\ldots - \\phi_p \\operatorname{B}^p) y_t            && \\text{(factoring out $y_t$)}\n\\end{aligned}\n$$ {#eq-ar-poly-derivation}\n\n$$\n\\Phi(u) = 1 - \\phi_1 u - \\phi_2 u^2 - \\ldots - \\phi_p u^p \\qquad \\text{(Characteristic polynomial)}\n$$ {#eq-ar-poly}\n\nwhere:\n\n- $u \\in \\mathbb{C}$ i.e. complex-valued roots\n- $\\phi_j$ are the AR coefficients.\n\n\n::: {.callout-caution collapse=\"true\"}\n## Replacing the Backshift operator by Z {.unnumbered}\n\nAs far as the mathematics goes it isn't clear how we get from @eq-ar-poly-derivation to the characteristic polynomial $\\Phi(z)$ in @eq-ar-poly.\n\nAs far as I can tell we can justify it by saying we have done three things:\n\n1. We set $\\varepsilon_t = 0$ to study the homogeneous equation. This is not about minimizing residuals but about analyzing the underlying linear recurrence, which governs the dynamics of the AR process without noise.\n2. We assume $y_t \\neq 0$. Since $\\Phi(B)y_t = 0$, we can treat this as a linear operator equation. By analogy to polynomial equations, if $ab = 0$ and $b \\neq 0$, then $a = 0$. Thus, we analyze the operator polynomial $\\Phi(B) = 0$ as the condition for nontrivial solutions.\n3. We replace the backshift operator $B$ with a complex number $z$, leading to the characteristic polynomial $\\Phi(z)$:\n  - This is justified by assuming exponential solutions of the form $y_t = z^t$, a standard method in solving linear recurrences. Substituting into $\\Phi(B)y_t = 0$ yields $\\Phi(z^{-1}) = 0$, which we often rewrite as $\\Phi(z) = 0$ for convenience.\n  - Alternatively, we view $B$ as a placeholder in a polynomial ring of operators, and replacing $B$ by $z$ evaluates that polynomial. This is a standard algebraic move in analyzing recurrence relations or z-transforms.\n  - Another point is that the backshift operator $B$ is just a linear operator on the space of time series. I.e it can be viewed as a matrix that shifts the time series back by one step.  \n\n:::\n\nDiving a little deeper $\\operatorname{B}$ is represented by a nilpotent matrix, which is a matrix that shifts the time series back by one step. This is a standard algebraic move in analyzing recurrence relations or z-transforms.\n\n$$\nB = \\begin{pmatrix}\n0 & 0 & 0 & \\cdots & 0 \\\\\n1 & 0 & 0 & \\cdots & 0 \\\\\n0 & 1 & 0 & \\cdots & 0 \\\\\n\\vdots & \\vdots & \\vdots & \\ddots & \\vdots \\\\\n0 & 0 & 0 & \\cdots & 1\n\\end{pmatrix}\n$$ {#eq-ar-poly-b-matrix}\n\nThis matrix is nilpotent because if you multiply it by itself enough times, it will eventually become the zero matrix. This is a key property that allows us to define the characteristic polynomial in terms of the backshift operator.\n\nNote: that the above derivation wasn't presented in the slides but is my own attempt to clarify the steps involved I hope it is helpful not 100% sure it is correct.\n\n- [This polynomial and its roots tells us a lot about the process and its properties. One of the main characteristics is it allows us to think about things like **quasi-periodic behavior**, whether it's present or not in a particular **AR($p$)** process. ]{.mark}\n- It allows us to think about whether a process is **stationary or not**, depending on some properties related to this polynomial. \n- In particular, we are going to say that the process is **stable** if all the roots of the characteristic polynomial have a modulus greater than one. [stability condition]{.column-margin}\n\n\n> Why are we interested in this autoregressive lag polynomial? \n\n$$\n\\Phi(z) = 0 \\iff |z| > 1  \\qquad \\text{(stability condition)}\n$$ {#eq-arp-stability}\n\n- For any of the roots, it has to be the case that the modulus of that root, they have to be all outside the unit circle.\n\n- If a process is stable, it will also be stationary.\n\nWe can show this as follows:\n\n[If the AR($p$) has all the roots of its characteristic polynomial outside the unit circle, it is *stable* and *stationary* and can be written in terms of an infinite order *moving average* process:]{.mark}\n\n\n$$\ny_t = \\Psi(\\operatorname{B}) \\varepsilon_t = \\sum_{j=0}^{\\infty} \\psi_j \\varepsilon_{t-j} \\quad \\text {with} \\ \\psi_0 = 1 \\quad \\text{ and } \\sum_{j=0}^{\\infty} |\\psi_j| < \\infty\n$$ {#eq-ar-stationary}\n\nwhere:\n\n- $\\varepsilon_t$ is a white noise process with zero mean and constant variance $v$.\n- $\\operatorname{B}$ is the lag operator AKA the backshift operator defined by $\\operatorname{B} \\varepsilon_t = \\varepsilon_{t-1}$. \n  This need to be applied to a time series $\\varepsilon_t$ to get the lagged values.\n- $\\Psi(\\operatorname{B})$ is the infinite order polynomial in $\\operatorname{B}$ that represents a linear filter applied to the noise process.​\n- $\\psi_t = 1$ is the weight for the white noise at time $t$.\n- the constraint $\\psi_0 = 1$ ensures that the current shock contributes directly to $y_t$\n- the constraint on the weights $\\sum_{j=0}^{\\infty} |\\psi_j| < \\infty$ ensures that the weights decay sufficiently fast, so that the process does not explode making it is stable and therefore stationary.\n\n::: {.callout-caution collapse=\"true\"}\n### Notation Confusion {.unnumbered}\n\nthe notation with $\\psi$ a functional of operator $B$ and $\\psi_i$ as constants is confusing in both the reuse if the symbol and the complexity.\n:::\n\n\nWe can also rewrite the characteristic polynomial in terms of the reciprocal roots of the polynomial.\n\n\nThe zeros of the characteristic polynomial are the roots of the **AR($p$)** process.\n\n$$\n\\Phi(u) = \\prod_{j=1}^{p} (1 - \\alpha_j u) = 0  \\implies u = \\frac{1}{ \\alpha_j} \\qquad \\text{(reciprocal roots)}\n$$ {#eq-ar-p-reciprocal-roots}\n\nwhere: \n\n- $\\alpha_j$ are the reciprocal roots of the characteristic polynomial.\n\nHere, $u$ is any complex valued number. \n\n\n<!--\nPrado says we will show later .... where this roots have important properties.\n\nIt would be nice to state this explicitly and linked to the appropriate sections.\n -->\n\n\n### State Space Representation of AR($p$) {#sec-state-space-ar-p}\n\n![A state space representation of AR($p$)](images/m2_0002.png){#fig-ar-p-state-space .column-margin  group=\"slides\" width=\"53mm\"}\n\nThis material is covered in [@prado2000bayesian § 2.1.2]\n\n[Another important representation of the AR($p$) process, is based on a state-space representation of the process. This representation is useful because it allows us to study some important properties of the process.]{.mark} We will make some connections with these representations later when we talk about dynamic linear models, is given as follows for an AR($p$). \n\n\n$$\ny_t = \\operatorname{F}^\\top \\mathbf{x}_t \\qquad \\text{(observational equation)}\n$$ {#eq-state-space-observational-equation}\n\nwhere:\n\n- $\\operatorname{F}$ is a linear mapping from the state space into the state space, so it is just  vector of coefficients, specifically $F = (1, 0, \\ldots, 0)^\\top$ for the AR($p$) process. The rank for this operator is $p$ since it has to match the dimension of the state vector $\\mathbf{x}_t$.\n- $\\mathbf{x}_t$ is a vector with the state of the process at time $t$.\n\nTo demystify $\\operatorname{F}$, it is just picking the current state from vector $\\mathbf{x}_t$ with states for the p previous time steps.\n\n$$\n\\mathbf{x}_t = G \\mathbf{x}_{t-1} + \\mathbf{w}_t \\qquad \\text{(state equation)}\n$$ {#eq-state-space-state-equation}\n\nwhere:\n\n- $\\mathbf{x}_t$ is a vector of the current state of the process.\n- $G$ is a state transition matrix that describes the relationship between the current state and the previous state.\n- $\\mathbf{x}_{t-1}$ is a vector of the previous state of the process.\n- $\\mathbf{w}_t$ is a vector of *innovations* or noise at time $t$, which is assumed to be normally distributed with zero mean and constant variance. The first component is going to be the $\\varepsilon_t$ and the rest of the components are going to be zero and the dimension of this vector is going to be $p$.\n\n\\index{AR($p$)!state transition matrix}\nand state transition matrix G\n\nThe $G$ matrix in this representation is going to be a very important matrix, the first row is going to contain the AR parameters, the AR coefficients, and we have $p$ of those. In the block below this is an identity matrix, and a zero column on it's right.\n\n\n$$\nG = \\begin{pmatrix}\n\\phi_1 & \\phi_2 & \\phi_3 & \\dots & \\phi_{p-1} & \\phi_p \\\\\n1 & 0 & 0 & \\dots & 0 & 0 \\\\\n0 & 1 & 0 & \\dots & 0 & 0 \\\\\n\\vdots & \\ddots & \\ddots & \\ddots & & \\vdots \\\\\n0 & 0 & 0 & \\dots & 1 & 0\n\\end{pmatrix}.\n$$ {#eq-ar-p-state-space-g-matrix}\n\nThis state transition matrix $\\mathbf{G}$ is important because it is related to the characteristic polynomial, in particular, is related to the reciprocal roots representation of the characteristic polynomial that we discussed before. \nThe structure of this $\\mathbf{G}$ matrix is such that it captures the Markovian dynamics of the autoregressive process, wherein each $\\mathbf{x}_t$ is a function of $\\mathbf{x}_{t-1}$. \n\nThe eigenvalues of this matrix correspond precisely to the reciprocal roots of the characteristic polynomial. \n\nPrado points out that if you perform the matrix operations described in @eq-state-space-observational-equation and @eq-state-space-state-equation, you will recover the form of your autoregressive process from the definition in @eq-ar-p-annotated .\n\nSo we have given the state-space representation of an AR($p$). One advantage of working with this representation is that we can use with it some definitions that apply to dynamic linear models or state-space models. One such definition is the so-called forecast function.\n\n### The forecast function of AR($p$) {#sec-forecast-function-ar-p}\n\n\\index{AR($p$)!forecast function}\nThe forecast function, which we denote as $f_t(h)$ is a function $f$ that depends on the time $t$ that you're considering, and then you're looking at forecasting $h$ steps ahead in your time series. \nIf you have observations up to today and you want to look at what is the forecast function five days later, we will set $h=5$ there. The forecast function is just the expected value and we can just think of this as the expected value of $y_{t+h}.$ conditional on all the observations or all the information you have received up to time $t$. \n\n$$\n\\begin{aligned}\nf_t(h) &= \\mathbb{E}[y_{t+h} \\mid y_{1:t}] &\\text{(defn)}\\\\\n       &= \\mathbf{F}^\\top \\mathbb{E}[\\mathbf{x}_{t+h} \\mid y_{1:t}] &\\text{(observation eq.)} \\\\ \n       &= \\mathbf{F}^\\top \\mathbf{G} \\mathbb{E}[\\mathbf{x}_{t+h-1} \\mid y_{1:t}] &\\text{(state eq.)} \\\\\n       &= \\mathbf{F}^\\top \\mathbf{G}^h \\mathbb{E}[\\mathbf{x}_t\\mid y_{1:t}], & \\text{(repeat)} \\\\\n       &= \\mathbf{F}^\\top \\mathbf{G}^h \\mathbf{x}_t & h > 0, \\forall t \\ge p\n\\end{aligned}\n$$ {#eq-ar-p-forecast-function-derivation}\n\nwhere:\n\n- $y_{1:t}$ is the vector of all observations up to time $t$, \n- $\\mathbf{x}_t$ is the state vector at time $t$.\n- $\\mathbf{G}^h$ is the state transition matrix raised to the power $h$, which captures the dynamics of the AR process over $h$ steps ahead. The eigenvalues of this matrix are the reciprocal roots of the characteristic polynomial of the AR($p$) process.\n\n- In this derivation:\n  - We start with the expectation and rewrite it expectation using the state-space representation equations:\n  - We start using the observation equation, replacing $y_{t+h}$ with $F^T(\\mathbf x_{t+h})$ in that case. \n  - Next we apply the second (state) equation. \n    - This introduces $\\mathbf{G}$ \n    - and updates our expected value to the next time step, so we have $\\mathbf{X}_{t+h-1}$. \n    - Note: that since the $w_{t+h-1}$ terms are independent of the past observations, their expected value is zero, so we can leave them out.\n  - We repeat applying the state equation for all the lags until we get to time $t$, ending up with a product of $h$ $\\mathbf{G}$ matrices here, so we end up with $\\mathbf{G}^h$ and the each time we drop a lag in the expectation of $\\mathbf{X}_{t+h}$. \n  - We end up with the expected value of $\\mathbb{E}[\\mathbf{x}_t]$ which is just the vector $\\mathbf{x}_t$ the current state of the process.\n\nThis result is significant because it now allows us to make the connection of $\\mathbf{G}$ and its eigenstructure. One of the features of $\\mathbf{G}$ is that the eigenstructure is related to the reciprocal roots of the characteristic polynomial. So when we working with the case in which we have exactly p distinct roots. We can further simplify using by rewriting $\\mathbf{G}$ in terms of its eigendecomposition.\nWe can rewrite $\\mathbf{G}$  as $\\mathbf{E}$, a matrix $\\mathbf{\\Lambda}$ here, $\\mathbf{E}^{-1}$. \n\n$$\n\\mathbf{G}= \\mathbf{E} \\mathbf{\\Lambda} \\mathbf{E}^{-1} \\qquad \\text{(eigendecomposition)}\n$$ {#eq-ar-p-g-eigendecomposition}\n\nwhere:\n\n- $\\mathbf{\\Lambda} = \\operatorname{diag}(\\alpha_1, \\ldots, \\alpha_p)$ is a diagonal matrix consisting of the reciprocal roots $\\alpha_i$, from the reciprocal formulation of the characteristic polynomial in @eq-ar-p-reciprocal-roots. \n  - While the order of the roots doesn't matter but there is a tradition of order eigenvalues them in decreasing value and this can help us  to **identify our model**!\n- $\\mathbf{E}$ is a eigenvectors decomposition for the matrix $\\mathbf{G}$ \n  $E = [\\mathbf{e}_1 ; \\cdots ; \\mathbf{e}_p]$, where $\\mathbf{e}_i$ is the eigenvector corresponding to $\\alpha_i$.   \n  - Since each root is unique the eigenvectors are all different and linearly independent.\n  - Note that the eigendecomposition, i.e. the eigenvectors, has to follow the order set in $\\Lambda$ \n\nWe can now rewrite $\\mathbf{G}^h$ as:\n\n$$\n\\mathbf{G}^h= \\mathbf{E} \\mathbf{\\Lambda}^h \\mathbf{E}^{-1} \\qquad \\text{(eigendecomposition of G)}\n$$ {#eq-ar-p-gh-eigendecomposition}\n\n::: {.callout-caution collapse=\"true\"}\n### Why arn't the eigendecomposition powered up {.unnumbered}\n\nSo here is an easy answer \n\nif $\\mathbf{G}= \\mathbf{E} \\mathbf{\\Lambda} \\mathbf{E}^{-1}$\n\nif we multiply out the all the $E$ and $E^{-1}$ terms cancel out except the last and first.\n:::\n\n\nWhatever elements have in the matrix of eigenvectors $\\mathbf{E}$, they are now going to be functions of the reciprocal roots $u_i=\\frac{1}{\\phi_j}$. \nThe power that appears here, which is the number of steps ahead that you want to forecast in your time series for prediction,\n\n$$\nf_t(h) = E(y_{t+h} \\mid y_{1:t}) = F^\\top G^h x_t, \\quad h > 0, \\quad \\forall t \\ge p\n$$ {#eq-ar-p-forecast-function}\n\nwhere:\n\n- $c_t$ are constants that depend on the $E$ matrix.\n- $\\alpha_i^h$ are the reciprocal roots raised to the power $h$.\n\nWe can see from the form of @eq-ar-p-forecast-function that if the process is stable, i.e. all the  all the moduli of my reciprocal roots are going to be below one. So it is going to decay exponentially as a function of h. And this AR($p$) process is going to be stationary.\n\n::: {.callout-important}\n### Interpreting the forecast function {.unnumbered}\nI recall that in physics we often view the eigenvectors as resonances of the system's dynamics, and the eigenvalues as the corresponding resonant frequencies. This is a good analogy to think about the reciprocal roots of the AR($p$) process. The contribution of each of the roots $\\alpha_i$ to $f(t)$ depends on how close that modulus of that reciprocal root is to 1 or -1. For roots that have relatively large values of the modulus, then they are going to have more contribution in terms of what's going to happen in the future.\n\nDepending on whether those reciprocal roots $\\alpha_i$ are real-valued or complex-valued, you're going to have behavior here that may be quasiperiodic for complex-valued roots or just non-quasiperiodic for the real valued roots. \n:::\n\nIn the text book AR($p$) forecasting is covered in [@prado2000bayesian § 2.2] and the mean square errors can be estimated using an algorithm by [@brockwell1991time].\n\n\n<!-- TODO: summarize this transcript -->\n\n::: {.callout-note collapse=\"true\"}\n## Video Transcript\n\n### AR(p) process and its Order {.unnumbered}\n\n[We will now discuss the general autoregressive process of order p.]{.mark}\nAs in the AR1, we're going to think about expressing current values of the time series in terms of past values of the time series.\nIn this case, we're going to think about expressing the current time in terms of the past p-values of the time series process.\nThat's why it's called an autoregressive model of order p.\n[The order tells you how many lags you are going to be considering.]{.mark}\n\nWe're going to then assume a process that is going to have this structure.\nAgain, as I said, we are regressing on the past p-values.\nAs before, in this case, we're going to assume that the epsilon t's are independent identically distributed random variables with a normal distribution centered at zero and variance v.\nThis is the assumption that we are going to use here.\nAs you see now, the number of parameters has increased.\n\nWe had one coefficient before, now we're going to have p coefficients, and we're going to have also the variance of the process.\nOne thing that is very important used to characterize and understand the properties of autoregressive processes is the so-called characteristic polynomial.\nThe AR characteristic polynomial is a polynomial, I'm going to denote it like this, and it's going to be a function of the phi coefficients here.\nIt's going to look like a polynomial here, and is a polynomial of order p.\nHere, U is any complex valued number.\n\n### Characteristic Polynomial, Stationarity and Stability {.unnumbered}\n\nWhy do we study this polynomial? \n[This polynomial tells us a lot about the process and a lot about the properties of this process.]{.mark}\n\n[One of the main characteristics is it allows us to think about things like **quasi-periodic behavior**, whether it's present or not in a particular AR p process.]{.mark}\n[It allows us to think about whether a process is **stationary** or not, depending on some properties related to this polynomial.]{.mark}\nIn particular, we are going to say that the process is **stable** here.\n\nThis is the **stability condition.**\n[If all the roots of this polynomial have a modulus, that is that they all have modulus that are greater than one, if, I'm going to write it like this, Phi of U, this polynomial is zero for a root, so for any value of U such that this happens, then we say that the process is stable.]{.mark}\nFor any of the roots, it has to be the case that the modulus of that root, they have to be all outside the unit circle.\nWhen a process is stable, it's also going to be stationary.\nIn this case, if the process is stable, then we have a stationary process.\nThis is going to characterize also the stationarity of the process in terms of the roots of the characteristic polynomial.\n\n### Infinite Order Moving Average Representation {.unnumbered}\n\n[Once the process is stationary, and if all the roots of the characteristic polynomial are outside the unit circle, then we will be able to write this process in terms of an infinite order moving average process.]{.mark}\n\nIn this case, if the process is stable, then we are going to be able to write it like this.\nI'm sorry, this should be epsilon t.\nI am going to have an infinite order polynomial here on B, the backshift operator that I can write down just as the sum, j goes from zero to infinity.\nHere Psi_0 is one.\nThen there is another condition on the Psi's for this to happen.\n[We have to have finite sum of these on these coefficients.]{.mark}\nOnce again, [if the process is stable, then it would be stationary and we will be able to write down the AR as an infinite order moving average process here.]{.mark}\nIf you recall, B is the backshift operator.\nAgain, if I apply this to y_t, I'm just going to get y_t minus j.\nI can write down Psi of B, as 1 plus Psi_1 B, B squared, and so on.\nIt's an infinite order  process.\n\n### Reciprocal roots representation {.unnumbered}\n\n[The AR characteristic polynomial can also be written in terms of the reciprocal roots of the polynomial.]{.mark}\nSo instead of considering the roots, we can consider the reciprocal roots.\nIn that case, let's say the Phi of u for Alpha 1, Alpha 2, and so on.\nThe reciprocal roots.\n\nWhy do we care about all these roots? \nWhy do we care about this structure? \nAgain, [we will be able to understand some properties of the process based on these roots]{.mark} as we will see.\n\n\n### State-Space Representation {.unnumbered}\n\n[We will now discuss another important representation of the AR(P) process, one that is based on a state-space representation of the process.]{.mark}\nAgain, [we care about this type of representations because they allow us to study some important properties of the process.]{.mark}\n\nIn this case, our state-space or dynamic linear model representation, we will make some connections with these representations later when we talk about dynamic linear models, is given as follows for an AR(P).\nI have my y_t.\nI can write it as F transpose and then another vector x_t here.\nThen we're going to have x_t is going to be a function of x_t minus 1.\nThat vector there is going to be an F and a G.\nI will describe what those are in a second.\nThen I'm going to have another vector here with some distribution.\nIn our case, we are going to have a normal distribution also for that one.\nIn the case of the AR(P), we're going to have x_t to be y_t, y_t minus 1.\nIt's a vector that has all these values of the y_t process.\nThen F is going to be a vector.\nIt has to match the dimension of this vector.\nThe first entry is going to be a one, and then I'm going to have zeros everywhere else.\nThe w here is going to be a vector as well.\nThe first component is going to be the Epsilon t.\nThat we defined for the ARP process.\nThen every other entry is going to be a zero here.\nAgain, the dimensions are going to match so that I get the right equations here.\n\n#### G-matrix {.unnumbered}\n\nThen finally, [my G matrix in this representation is going to be a very important matrix, the first row is going to contain the AR parameters, the AR coefficients.]{ .mark }  \nWe have p of those.\nThat's my first row.\n[In this block, I'm going to have an identity matrix.]{.mark}\nIt's going to have ones in the diagonal and zeros everywhere else.\nI'm going to have a one here, and then I want to have zeros everywhere else.\n[In this portion, I'm going to have column vector here of zeros.]{.mark}\n\nThis is my G matrix.\nWhy is this G matrix important? \n[This G matrix is going to be related to the characteristic polynomial, in particular, is going to be related to the reciprocal roots of the characteristic polynomial that we discussed before.]{.mark}\nThe eigenvalues of this matrix correspond precisely to the reciprocal roots of the characteristic polynomial.\n\nWe will think about that and write down another representation related to this process.\nBut before we go there, I just want you to look at this equation and see that if you do the matrix operations that are described these two equations, you get back the form of your autoregressive process.\nThe other thing is, again, this is called a state-space representation because you have two equations here.\nOne, you can call it the observational level equation where you are relating your observed y's with some other model information here.\nThen there is another equation that has a Markovian structure here, where x_t is a function of x_t minus 1.\n\n[This is why this is a **state-space representation.**]{.mark}\n\n[One of the nice things about working with this representation is we can use some definitions that apply to dynamic linear models or state-space models, and one of those definitions is the so-called **forecast function**.]{.mark}\nThe forecast function, we can define it in terms of, I'm going to use here the notation f_t h to denote that is a function f that depends on the time t that you're considering, and then you're looking at forecasting h steps ahead in your time series.\nIf you have observations up to today and you want to look at what is the forecast function five days later, you will have h equals 5 there.\n[It's just the expected value.]{.mark}\nWe are going to think of this as the expected value of y_t plus h.\nConditional on all the observations or all the information you have received up to time t.\nI'm going to write it just like this.\n\nUsing the state-space representation, you can see that if I use the first equation and I think about the expected value of y_t plus h is going to be F transpose, and then I have the expected value of the vector x_t plus h in that case.\nI can think of just applying this, then I would have expected value of x_t plus h given y_1 up to t.\nBut now when I look at the structure of x_t plus h, if I go to my second equation here, I can see that x_t plus h is going to be dependent on x_t plus h minus 1, and there is a G matrix here.\n\nI can write this in terms of the expected value of x_t plus h, which is just G, expected value of x_t plus h minus 1, and then I also have plus expected value of the w_t's.\nBut because of the structure of the AR process that we defined, we said that all the Epsilon T's are independent normally distributed random variables center at zero.\nIn this case, those are going to be all zero.\nI can write down this as F transpose G, and then I have the expected value of x_t plus h minus 1 given y_1 up to t.\nIf I continue with this process all the way until I get to time t, I'm going to get a product of all these G matrices here, and because we are starting with this lag h, [I'm going to have the product of that G matrix h times.]{.mark}\nI can write this down as F transpose G to the power of h, and then I'm going to have the expected value of, finally, I get up to here.\nThis is simply is going to be just my x_t vector.\nI can write this down as F transpose G^h, and then I have just my x_t.\n\nAgain, why do we care? \n[Now we are going to make that connection with this matrix and the eigenstructure of this matrix.]{.mark}\nI said before, [one of the features of this matrix is that the eigenstructure is related to the reciprocal roots of the characteristic polynomial.]{.mark}\nIn particular, the eigenvalues of this matrix correspond to the reciprocal roots of the characteristic polynomial.\n\n[If we are working with the case in which we have exactly p different roots.]{.mark}\nWe have as many different roots as the order of the AR process.\nLet's say, p distinct.\n[We can write down then G in terms of its eigendecomposition.]{.mark}\nI can write this down as E, a matrix Lambda here, E inverse.\nHere, [Lambda is going to be a diagonal matrix, you just put the reciprocal roots, I'm going to call those Alpha 1 up to Alpha p.]{.mark}\nThey are all different.\nYou just put them in the diagonal and you can use any order you want.\nBut the eigendecomposition, the eigenvectors, have to follow the order that you choose for the eigenvalues.\nThen what happens is, regardless of that, you're going to have a unique G.\n\nBut here, [the E is a matrix of eigenvectors.]{.mark}\nAgain, why do we care?\nWell, if you look at what we have here, we have the power [G to the power of h.]{.mark}\nUsing that eigendecomposition, we can get to write this in this form.\nWhatever elements you have in the matrix of eigenvectors, they are now going to be functions of the reciprocal roots.\nThe power that appears here, which is the number of steps ahead that you want to forecast in your time series for prediction, I'm just going to have the Alphas to the power of h.\nWhen I do this calculation, [I can end up writing the forecast function just by doing that calculation as a sum from j equals 1 up to p of some constants.]{.mark}\n\nThose constants are going to be related to those **E matrices** but the important point is that what appears here is my Alpha to the power of h.\nWhat this means is I'm breaking this expected value of what I'm going to see in the future in terms of a function of the reciprocal roots of the characteristic polynomial.\nYou can see that [if the process is stable, is going to be stationary, all the moduli of my reciprocal roots are going to be below one.]{.mark}\nThis is going to decay exponentially as a function of h.\nYou're going to have something that decays exponentially.\n\n[Depending on whether those reciprocal roots are real-valued or complex-valued, you're going to have behavior here that may be quasiperiodic for complex-valued roots or just non-quasiperiodic for the real valued roots.]{.mark}\nThe other thing that matters is, if you're working with a stable process, are going to have moduli smaller than one.\nThe contribution of each of the roots to these forecasts function is going to be dependent on how close that modulus of that reciprocal root is to one or minus one.\n[For roots that have relatively large values of the modulus, then they are going to have more contribution in terms of what's going to happen in the future.]{.mark}\n[This provides a way to interpret the AR process.]{.mark}\n\n\n:::\n\n## Examples :movie_camera: \n\n\n### **AR(1) Process**\n\n![AR(1)](images/m2_0011.png){#fig-ar1-example .column-margin  group=\"slides\" width=\"53mm\"}\n\n\n\n* **State-space form**:\n  $X_t = \\phi X_{t-1} + \\omega_t$\n* **Forecast function**:\n  $\\mathbb{E}[y_{t+h} \\mid \\mathcal{F}_t] = c \\cdot \\phi^h$\n* **Behavior**:\n  Exponential decay (oscillatory if $\\phi < 0$), mimicking the autocorrelation function.\n* **Stability**:\n  $|\\phi| < 1$ (reciprocal root $1/\\phi$ has modulus > 1).\n\n### **AR(2) Process**\n\n![AR(2) two positive roots](images/m2_0012.png){#fig-ar2-two-positive-roots .column-margin  group=\"slides\" width=\"53mm\"}\n\n\n\n![AR(2) complex roots](images/m2_0013.png){#fig-ar2-complex-roots .column-margin  group=\"slides\" width=\"53mm\"}\n\n\n\n* **Characteristic polynomial**:  $1 - \\phi_1 z - \\phi_2 z^2$\n* **Three root types**:\n\n  1. **Two real distinct reciprocal roots**:\n     Forecast function:\n\n     $$\n     \\mathbb{E}[y_{t+h} \\mid \\mathcal{F}_t] = c_{t1} \\alpha_1^h + c_{t2} \\alpha_2^h\n     $$\n\n     Exponential decay, dominated by root with larger modulus.\n\n  2. **Two complex conjugate reciprocal roots**: Let roots be $r e^{\\pm i\\omega}\\$.\n     Forecast function:\n\n     $$\n     \\mathbb{E}[y_{t+h} \\mid \\mathcal{F}_t] = A_t r^h \\cos(\\omega h + \\delta_t)\n     $$\n\n     Behavior: *Quasiperiodic* with exponential envelope.\n\n  3. **Repeated reciprocal root (\\$\\alpha\\$ with multiplicity 2)**:\n     Forecast function:\n\n     $$\n     \\mathbb{E}[y_{t+h} \\mid \\mathcal{F}_t] = (\\alpha^h)(a_t + b_t h)\n     $$\n\n     Polynomial-exponential form due to root multiplicity.\n\n### Key Concepts\n\n* Forecast structure mirrors the **roots** of the characteristic polynomial.\n* Stability depends on **reciprocal roots** (modulus < 1).\n* Complex roots → sinusoidal terms; \n* Repeated roots → polynomial multipliers.\n\nThis analysis connects **forecast behavior** to the **algebraic properties** of AR model roots.\n\n\n<!-- TODO: summarize this transcript -->\n\n::: {.callout-note collapse=\"true\"}\n## Video Transcript\n\nNow, that we have discussed the characteristic polynomial and the state-space representation for a general AR(P) process, we are going to discuss a few examples just to try to understand what this means in particular cases of AR processes.\nOne of them is going to be, we're going to go back to the AR(1) and see what is the forecast function and how that relates to what we learned before.\nThe other example we are going to consider here is the AR(2), the autoregressive process of order 2.\nLet's begin with the first case, which is again the AR(1).\nIn the AR(1), we are assuming that as usual the model looks like this.\nNow if I think about the state-space representation for these process is going to be, remember we need to have something that looks like this X_t, X_t G X_t minus 1 and then plus Omega t.\nIn this case, because I have order 1, my X_t is going to be a one-dimensional scalar component, the same thing with F, and then G is going to be just my Phi.\nHere F is going to be one, X_t is going to be y_t, and then G is going to be Phi.\nIf you think about how we define the forecast function, we said the forecast function is just the suspected value of y_t plus h given everything that we have observed.\nI think about predicting h steps ahead given all the information I have up to time t.\nWe said that the state-space representation allows us to have something that looks like this.\nGiven that these are all scalars, what we are going to have is that we can write down the forecast function in terms of the reciprocals root of the characteristic polynomial.\nIn the case of the characteristic polynomial, I'm going to have for the AR(1), so before I write down the expression here, is going to be an order 1 polynomial.\nThis is the form of the polynomial.\nIf I want to find the roots of the characteristic polynomial and this implies that I have one over Phi.\nThat's my root of the characteristic polynomial.\nFor the process to be stable, I need this root to have modulus greater than one or the reciprocal root, which is going to be phi, to have modulus smaller than one.\nI have that this is, we are going to make here the assumption that we are working with processes that have Phi values that are between minus 1 and one.\nAgain, going back to the forecast function, since the G matrix is Phi, I can write these down as just something that is the power of Phi.\nIt's going to be, I'm going to have some constant here, whatever that is that comes from this expression.\nThen I'm going to have my Phi to the power of h.\nThat's the expression we get for the AR(1), and we can see that it has the same form that we discussed for the auto-correlation function of an AR process.\nIf you remember, the auto-covariance and the auto-correlation function of an AR process is decaying exponentially as a power of h just in the same form that this forecast function is decaying exponentially on Phi.\nIf the Phi negative, we're going to have an oscillatory decay.\nIf the Phi positive, we're just going to have an exponential decay.\nIt follows exactly the same structure as the auto-covariance function for the AR(1).\nThere is that correspondence and here we are just thinking about how we're going to predict the process h steps ahead.\nOur second example is just the AR(2) process.\nLet's think about what kind of structure we have for the forecast function of this process.\nIn an AR(2) we are going to regress on the first two values of the process.\nWe have to AR coefficients, Phi_1 and Phi_2.\nThe characteristic polynomial is going to be given another two polynomial in this case.\nThen again, if we think about stable processes, they are going to have characteristic roots that have moduli larger than 1 and the reciprocal roots have moduli smaller than 1.\nIf I think about finding the roots of this polynomial, this is the same as the just getting 2 squared plus Phi_1u minus 1 equals to 0.\nThen this is a quadratic polynomial.\nIf I want to find the roots, I can just think about this equation.\nLooking at this expression, we can think about three possible cases depending on what happens with the expression that is here in the square root.\nI can have values of Phi_1 and Phi_2 that make this expression different from zero and positive.\nIn that case, I'm going to have two different real reciprocal roots.\nI can think about having values of Phi_1 and Phi_2 that make this expression equal to 0.\nIn that case, we can again think about having a single reciprocal root with multiplicity 2.\nThen I can think about cases in which I'm going to have values that make this expression inside the square root negative.\nIn that case we are going to have complex-valued roots.\nLet's think about those cases.\nThe first case we can describe this the case in which Phi_1 squared plus 4 Phi_2 is greater than 0.\nIn that case, we are going to have two characteristic.\nThey are both real valued.\nI can write them down as u_1.\nIf I think now about the reciprocal roots, I'm going to have just these are real valued.\nI'm going to have Alpha 1 is going to be 2 Phi_2 over minus Phi_1.\nThen I'm going to have my Alpha_2 plus Phi_1.\nSo I have these two real-valued reciprocal roots.\nSo I can write down the forecast function again f_t(h), which is my expected value of y_t plus h, given all the observations up to time t, I can write it down.\nI'm going to have two components.\nOne is going to be related to the first reciprocal root, and the other one is going to be related to the second reciprocal root.\nI have a power of h here for both.\nThen I'm going to have to let's call it c_t1 and c_t2 here.\nThese are constants.\nAs you can see, I'm going to have two components in my forecast function.\nIf one root has a modulus that is larger than the other one, that one is going to have a larger contribution to the forecast function h steps ahead than the other one.\nAgain, we have an exponential decay assuming that the process is stable, but we have two components are contributing to the forecast function.\nThe second case I'm going to discuss in terms of the characteristic roots here is the case in which you have values of Phi_1 and Phi_2 that lead to negative values inside this square root.\nSo here we would have the case in which Phi_1 square plus 4.\nThis is a negative value.\nBecause we have something negative inside of the square root, what this means is we're going to have two complex valued roots and therefore two complex valued reciprocal roots.\nSince they are complex valued, they are going to appear as a pair of complex conjugates.\nWe can do the calculation so I can write down u1 and u2 and then think about the reciprocal of those.\nI'm just writing the reciprocal roots.\nIn this case we can write them like this over two.\nOnce you do all your calculations and take the reciprocals.\nThis is a pair of complex conjugates.\nOne root is a complex conjugate of the other one.\nThese are different reciprocal roots.\nBecause they are complex valued, we can write them in a different way.\nWe can write them as Alpha 1 r exponential of i Omega, let's call it, and Alpha 2 r exponential of minus i Omega.\nIf I write these in polar coordinates, I'm going to have a modulus.\nThe modulus is the same for each of these and then I'm going to have a frequency.\nThe modulus r the frequency is Omega here.\nOne is the complex pair of the other one and if you think about again, the form that this is going to have in the forecast function, we can write down the forecast function.\nAgain, we have the contribution.\nYou can think of this as a constant times Alpha 1 to the power of h and then plus another constant times Alpha 2 to the power of h.\nBut because they are complex conjugates, we can write down the expression in terms of sinusoidal form as follows.\nIf I just do this, this is what we were describing before.\nThere is an Alpha 2 to the power of h.\nUsing these here, we can rewrite everything and the fact that they are complex conjugates, also the eigenstructure is going to be like that.\nWe can write down in terms of something that looks like this.\nThis is the cosine of that frequency times h.\nh is the number of steps ahead, plus some random phase here that depends on the information up to time t.\nThen here for my amplitude, I'm going to have again, something that depends on the information I have up to time t, and then I have the modulus of the reciprocal root to the power of h.\nYou can see here, there is also some exponential decay, assuming that we are in the stable case where r is essentially between zero and one, because that's the modulus of the reciprocal root.\nThen I have an exponential decay as a power of h, but it's a sinusoidal.\nIt has a sinusoidal form.\nThis is just a cosine wave and it's going to be having this is what we call quasiperiodic behavior.\nThe periodicity here is given by this Omega.\nThere is a random phase and that's why we say that the form of the forecast function is quasiperiodic.\nWhen you have an ar(2) depending on the structure of the roots, you can also have a case in which you have a quasiperiodic process.\nThe final case for this is the case in which you have values of Phi 1 and Phi 2 that give you a zero here inside the square root.\nIn that case, you are going to have a single root with multiplicity two.\nYou can think about how many times the root repeats.\nWe did not write the general expression for the forecast function in the case where you have repeated roots with multiplicity higher than one, but you can show that the forecast function of this, in this particular case, when you have a repeated root, is going to be of the form.\nYou have your Alpha, which is that single reciprocal root that we have here to the power of h times a_t plus b_t times h.\nYou have here a polynomial of order one in h multiplied by that Alpha h.\nThis is the case of the process when you have a single root.\nIn practice, we always work with cases one and two, and we will see that in the examples.\n\n\n:::\n\n## ACF of the AR($p$)  :movie_camera: \n\n![ACF of the AR($p$)](images/m2_0021.png){#fig-acf-ar-p .column-margin  group=\"slides\" width=\"53mm\"}\n\n\n\nFor a **stationary AR($p$)** process, the **autocorrelation function (ACF)** satisfies a homogeneous linear difference equation whose solution is a sum of terms involving the **reciprocal roots** of the characteristic polynomial. Key points:\n\n* If there are $r$ distinct reciprocal roots $\\alpha_1, \\ldots, \\alpha_r$ with multiplicities $m_1, \\ldots, m_r$ such that $\\sum m_j = p$, the ACF has the general form:\n\n  $$\n  \\rho(h) = \\sum_{j=1}^r P_j(h)\\alpha_j^h,\n  $$\n\n  where each $P_j(h)$ is a polynomial of degree $m_j - 1$.\n\n* For **distinct reciprocal roots** (common case), all $m_j = 1$, so $\\rho(h)$ is a linear combination of powers of the roots.\n\n* **AR(1)**: ACF is $\\rho(h) = \\phi^h$, where $\\phi$ is the AR coefficient.\n\n* **AR(2)**: Three cases arise:\n\n  1. Two distinct real roots → exponential decay.\n  2. Complex conjugate roots → **damped sinusoidal** behavior $r^h \\cos(\\omega h + \\delta)$.\n  3. One real root with multiplicity 2 → decay with polynomial factor.\n\n* ACF decays **exponentially** if all reciprocal roots lie inside the unit circle.\n\n* The **Partial ACF (PACF)** of AR($p$) is **zero for all lags > p**.\n\n* PACF values can be computed recursively via the **Durbin–Levinson algorithm**, using sample autocorrelations.\n\n\n<!-- TODO: summarize this transcript -->\n\n::: {.callout-note collapse=\"true\"}\n## Video Transcript\n\nIn the case of an autoregressive process of order p, the autocorrelation function can be written then as the solution of a homogeneous difference equation.\nAgain, we are working with the stationary case.\nYou can recall the notation we were using.\nRho is a function of the lag here.\nFor an AR(P) we can write this difference equation.\nThe autocorrelation function has to satisfy this equation.\nYou can show that the solution of this equation is related to the characteristic roots of the AR polynomial.\nIn particular, if we think that the AR process that we are working with has r reciprocal roots.\nI'm going to call them Alpha_1 up to Alpha_r and they are all distinct.\nLet's assume that each of these roots has a specific multiplicity.\nThen, again, for each of these roots and their multiplicities, they have to satisfy that when we add them all we get the order of the model which is P.\nFor this case, we can write down the solution or the autocorrelation function as a function that is a sum of r components where each of those components is related to one of the roots.\nI'm going to have Alpha_1^h.\nEach of these p's here are polynomials on h.\nThe degree of the polynomial is going to depend on the multiplicity of the root.\nEach of the polynomials here on h is a polynomial of order, the multiplicity of the root minus 1, m_j minus 1.\nIn the case in which you have exactly P different reciprocal roots, so the number of different reciprocal roots you have in the AR characteristic polynomial is exactly P.\nEach root is going to have multiplicity 1.\nTherefore, each of these polynomials is going to be a polynomial of order 0 on h, so it's just going to be a constant.\nUsually we work with that case.\nI'm now going to talk about two examples that we have considered before.\nIn the case of the AR(1), we saw earlier that we can write down the autocorrelation function is just, has this form, is the form Phi^h, where Phi is the AR coefficient.\nThis form is consistent with this result.\nIn the case of a stationary AR 1, we can show that the reciprocal root of the characteristic polynomial is Phi.\nSo what we get here is we have a single root, multiplicity 1.\nWe have the root^h multiplied by a constant.\nIn this case, a constant is equal to 1.\nYou can show that that constant is equal to 1 just using properties of autocorrelations.\nIn the case of the AR 2, we're also going to have this form.\nWe discussed three cases in terms of the number of reciprocal roots you can have.\nYou can have two real valued different reciprocal roots, each with multiplicity 1.\nYou can have a pair of complex roots.\nThey are different.\nThey have a modulus and a frequency associated to them.\nYou also have the case of one single reciprocal rule, real valued with multiplicity 2.\nFor instance, if you have something that looks like this, so I have a pair of complex valued reciprocal roots, I can write them in this polar representation.\nR is the modulus of the reciprocal root and Omega here is the frequency.\nUsing this result because each has multiplicity 1, I'm going to again have that.\nI can write a constant times Alpha_1^h plus another constant times Alpha_2^h, given that these are complex reciprocal roots and they appear as complex conjugates.\nI can simplify this equation and then get something of the form plus aother constant.\nHere, c and d are constants.\nMy Omega is my frequency of the roots, r is the modulus.\nThen we can see again that in the case of stable, stationary processes, my modulus of the reciprocal root is smaller than one.\nWe are going to have an exponential decay multiplied by these cosine waves.\nso there is going to be this oscillatory behavior.\nIn this case again, we have exponential decay.\nWe can see that we can find the properties of the autocorrelation function.\nThey are related to the reciprocal roots of the characteristic polynomial.\nWe can also think about the partial autocorrelation function.\nFor the partial autocorrelation function is possible to use the Durbin Levinson recursion again to express the partial autocorrelation coefficients as functions of the autocovariance and the autocorrelation.\nIn the case of an AR(P), you can show that it has to be the case that after the lag of the order of the model, all the partial autocorrelation coefficients are going to be zero.\nThat's a property for the partial autocorrelation for the AR(P), it is zero after lag equal to the model order P.\nIn the case of the ACF, the autocorrelation function, we have that exponential decay assuming that all the roots have moduli smaller than one.\nIf we want to get the sample partial autocorrelation, we can also put the sample autocorrelations into the Durbin Levinson recursion and we can get the expressions for that.\n\n\n:::\n\n## Simulating data from an AR($p$)  :movie_camera: \n\nThis video goes through the code in the following sections, which simulates data from an AR($p$) process and plots the sample ACF and PACF.\n\n\n1. **Characteristic Roots from AR Coefficients**:\n\n   * Given AR coefficients (e.g. for AR(8)), compute characteristic roots using `polyroot()` on the reversed sign polynomial (first term 1, followed by negative AR coefficients).\n   * Reciprocal roots are obtained as $1/\\text{root}$.\n   * Use `Mod()` for modulus and $2\\pi / \\text{Arg}()$ for approximate periods of the reciprocal roots.\n\n2. **Example AR(8)**:\n\n   * Yields 4 complex-conjugate pairs.\n   * Most persistent: modulus ≈ 0.97, period ≈ 12.7.\n   * Others show lower modulus and shorter periods, contributing less to persistence.\n\n3. **Simulating AR(2) with Complex Roots**:\n\n   * Reciprocal root modulus 0.95, period 12 → converted to AR coefficients (≈ 1.65, -0.902).\n   * Simulated data shows quasi-periodic behavior.\n   * ACF: decaying sinusoidal pattern.\n   * PACF: significant at lags 1 and 2, then drops, consistent with AR(2).\n\n4. **Simulating AR(2) with Real Roots**:\n\n   * Roots: 0.95 and 0.5.\n   * AR coefficients derived from these.\n   * No quasi-periodic pattern in data; resembles damped random walk.\n   * ACF: smooth decay.\n   * PACF: only first two lags significant.\n\n5. **Simulating AR(3) with Complex + Real Root**:\n\n   * Complex root pair: modulus 0.95, period 12; real root: modulus 0.8.\n   * Three AR coefficients derived.\n   * Simulated series shows quasi-periodic behavior plus extra persistence.\n   * ACF: still shows decaying periodicity.\n   * PACF: more than two significant lags, consistent with *AR(3)*.\n\n**Key Insight**:\n\nThe modulus and type (real vs. complex) of reciprocal roots determine persistence and periodicity. The ACF reflects these traits, while the PACF helps identify AR order.\n\n\n## Computing the roots of the AR polynomial  :spiral_notepad:  $\\mathcal{R}$\n\nCompute AR reciprocal roots given the AR coefficients\n\n\n::: {.cell list-label='lst-compute-ar-p-reciprocal-roots' list-caption='Compute AR reciprocal roots given the AR coefficients'}\n\n```{.r .cell-code}\n# Assume the folloing AR coefficients for an AR(8)\nphi=c(0.27, 0.07, -0.13, -0.15, -0.11, -0.15, -0.23, -0.14)\nroots=1/polyroot(c(1, -phi)) # compute reciprocal characteristic roots\nr=Mod(roots) # compute moduli of reciprocal roots\nlambda=2*pi/Arg(roots) # compute periods of reciprocal roots\n\n# print results modulus and frequency by decreasing order\nprint(cbind(r, abs(lambda))[order(r, decreasing=TRUE), ][c(2,4,6,8),]) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             r          \n[1,] 0.9722428 12.731401\n[2,] 0.8094950  5.103178\n[3,] 0.7196221  2.987712\n[4,] 0.6606487  2.232193\n```\n\n\n:::\n:::\n\n\n\n<!-- TODO: summarize this transcript -->\n\n::: {.callout-note collapse=\"true\"}\n## Video Transcript\n\nIn this code, we will see how to compute the characteristic roots of the AR polynomial given a particular set of AR coefficients.\nI'm just going to work here with an example in which we have the AR coefficients of an AR(8).\nThis is just setting some values for these coefficients, the first line here is just keeping these in a vector.\nBased on these coefficients for these AR(8), we're going to compute the roots of the characteristic polynomial and the reciprocal roots in this case of the characteristic polynomial, so we're going to use the function polyroot to do that.\nBecause we want the reciprocals, is going to be one over the roots of the characteristic polynomial.\nFor the polyroots function, you just enter the AR coefficients here, remember you have the AR characteristic polynomial, the first coefficient is one, and then you have the negative values of the AR coefficients.\nJust doing that, if we now want to compute the moduli of the reciprocal roots, we can use a function Mod in R.\nIf we want to compute the periods of the reciprocal roots, we are going to use a function Arg, these gives me the arguments, but if I compute two times Pi over the argument of the reciprocal roots, I get the periods.\nWe can now bring the results in terms of modulus and frequency, and we're printing them by decreasing order.\nIf you look at the results down here, you're going to have an AR.\nAgain, an AR(8) for this particular set of AR coefficients, we are going to have exactly four pairs of complex reciprocal roots.\nThis here, the first line corresponds to the modulus and the period of the first root, so it's a very persistent modulus of 0.97.\nThen we have a period that is around 12.7.\nThen the rest of the roots are also complex valued, they are in decreasing moduli, so we can see that the second one has modulus around 0.81 With period around five, the third one 0.72 with period around three, and then the last 0.66 with period around 2.23.\nIf you remember, is going to matter in terms of the contribution to both, the autocorrelation function and to the forecast function of this process.\nNow, I'm just going to show you what we can do in terms of simulating from different AR processes of orders two and three, and then looking at the properties of those processes.\nHere, the first example I'm considering is an AR(2) that happens to have one pair of complex valued reciprocal roots the modulus 0.95 and the period is 12, so we just keep those, we transform to the Phi coefficients using the equations we have described, and then we get the AR coefficients.\nNow that we have the AR coefficients and this is my AR coefficient, the one corresponding to the first lag is about 1.65 and minus 0.902 for the second lag.\nWe can now generate data from an AR(2) use the function arima.sim.\nI'm setting the random seed first and then I'm going to select here the number of data points that I want to simulate, in this case is going to be 300 data points.\nThe variance of the process at the observational level here, so it's just the innovations standard deviation and variance is one, then I'm going to use the function and I'm going to say that I'm going to keep my data here in the yt object and I'm going to use the function arima.sim so it is 300 observations.\nThe model here is a pure auto-regressive model.\nThe first component here corresponds to the AR coefficients, so I just pass these as a vector containing the AR coefficients for this AR(2) and then I specify the standard deviation as well.\nOnce I do that, I can plot my simulated data is here and we can see that it has these quasi periodic behavior.\nThe quasi periodic behavior is consistent with these.\nReciprocal roots are complex valued with period 12 and a persistent modulus.\nThen if we look at properties of this process in terms of the autocorrelation function and partial autocorrelation function, we can plot them both, and if we zoom in here, just the first function that we're plotting here is the sample ACF, and we can see again, I'm just plotting the first 50 lags of the sample ACF.\nWe have that behavior that we expect for this type of process is process has a pair of complex valued roots with period 12.\nWe can see these quasi-periodicity appears in the ACF, and then there is a decay in the ACF coefficients in the sample ACF coefficients as the lag increases, which is consistent with the fact that the root has a modulus, that is, the reciprocal root has a modulus that is below one.\nIf we think about the partial ACF, remember for an autoregressive process of order p, the partial ACF, these are the sampled.\nPartial ACFs are going to be zero after the lag of the process.\nThis is the theoretical property here for the sample.\nWe can see that this is also the case.\nThe first two coefficients are significant and then the other ones are within the confidence bands provided by the R function.\nThis is for this particular example.\nI'm now going to simulate an AR(2) with two real reciprocal roots rather than having one pair of complex valued, reciprocal roots, we have two real reciprocal roots, one with modulus 0.95 and another one with modulus 0.5.\nIf we do the same here, we have the Phi coefficients, so we just transform the reciprocal roots to the AR coefficients.\nThese are now my two AR coefficients and I'm going to just do something similar to what I did before.\nI'm going to sample 300 data points using arima.sim function.\nThe standard deviation of the innovation continues to be one.\nI just changed the AR coefficients.\nThis is my yt, we can plot the simulated observations and we can see that the process is different.\nThe data set is different to what we had before, so it shows different characteristics.\nThere is no quasiperiodic behavior that is apparent in this particular plot.\nThere is this behavior that is almost similar, a little bit like a random walk type of behavior, which is consistent with the fact that we have, two real reciprocal roots and one of them is very persistent, is the modulus is 0.95.\nWhen we look at the ACF and the PACF of this data, so this is again the sample ACF and the sample PACF, just zooming in here.\nWe can see that for the sample ACF, we again have this decay as the lag decreases, we don't have any quasiperiodic behavior here.\nThis is a process that is just decaying over time.\nThen for the sample PACF, we have the first two coefficients that are significantly different from zero, and then the remaining coefficients are mostly within the confidence bands.\nThis is again consistent with what the characteristics of the process that we were expecting.\nThe next example is an AR(3).\nHere, I'm going to simulate from an autoregressive process of order 3.\nThere are different alternatives that we can have in terms of the complex or real reciprocal roots.\nIn this case, I'm going to assume that we have one pair of complex valued reciprocal roots and one real reciprocal root, the complex valued reciprocal root, I'm going to assume that that pair has modulus 0.95.\nAgain, it's fairly persistent and that period of 12, so in that sense is similar to the behavior that we had before when we considered the AR(2) with this particular root structure.\nBut now, in addition to that, we are going to have another root that has modulus 0.8 and that one is real valued.\nAgain, we use this function to obtain the Phis.\nIf you look at the Phi coefficients here now, we have three coefficients: Phi[1], Phi[2], and Phi[3].\nThey go with the past three values of the yts.\nWe are going to once again sample 300 data points using the arima.sim function to do that.\nWe have the same standard deviation as before and we can plot the process.\nYou can see here that this process has very many characteristics that are similar to what we observe with the first example with the AR(2).\nIt has that same roots structure for the complex valued root.\nBut in addition to that, we also have a real valued reciprocal root.\nIf we look at the ACF, the sample ACF and the sample PACF, we can see now, again, the behavior is similar to what we had before.\nThe only difference here is that we are going to have more structure.\nHere, we have that quasiperiodic behavior that is decaying also as a function of the lag and then for the partial ACF, we can see that it's indicating that maybe we have more than one lag, that is more than the first two lags that are significantly different from zero.\nThis is the case for an AR(3).\nAgain, the process is still dominated by the root that has the highest modulus, which in this case happens to be the complex valued root.\nBut there is an additional root here that changes a bit the structure of the process and it will change, therefore the ACF and the PACF.\n\n\n:::\n\n\n## Simulating data from an AR($p$) :spiral_notepad: $\\mathcal{R}$\n\n\\index{AR($p$)}\n\\index{ARIMA}\n\n1.  R code to simulate data from an AR(2) with one pair of complex-valued reciprocal roots and plot the corresponding sample ACF and sample PACF\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## simulate data from an AR(2)\nset.seed(2021)\n## AR(2) with a pair of complex-valued roots with modulus 0.95 and period 12 \nr=0.95\nlambda=12 \nphi=numeric(2) \nphi[1]<- 2*r*cos(2*pi/lambda) \nphi[2] <- -r^2\nphi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  1.645448 -0.902500\n```\n\n\n:::\n\n```{.r .cell-code}\nT=300 # number of time points\nsd=1 # innovation standard deviation\nyt=arima.sim(n=T, model = list(ar = phi), sd=sd)\n\npar(mfrow = c(3, 1), mar = c(3, 4, 2, 1), cex.lab = 1.5)\n## plot simulated data\nts.plot(yt)\n## draw sample autocorrelation function\nacf(yt, lag.max = 50,\n    type = \"correlation\", ylab = \"sample ACF\", \n    lty = 1, ylim = c(-1, 1), main = \" \")\n\n## draw sample partial autocorrelation function\npacf(yt, lag.ma = 50, main = \"sample PACF\")\n```\n\n::: {.cell-output-display}\n![](C4-L04_files/figure-pdf/ar-sim-complex-valued-roots-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n2.  R code to simulate data from an AR(2) with two different real-valued reciprocal roots and plot the corresponding sample ACF and sample PACF\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### Simulate from AR(2) with two real reciprocal roots (e.g., 0.95 and 0.5)\nset.seed(2021)\nrecip_roots=c(0.95, 0.5) ## two different real reciprocal roots\nphi=c(sum(recip_roots), -prod(recip_roots)) ## compute ar coefficients\nphi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  1.450 -0.475\n```\n\n\n:::\n\n```{.r .cell-code}\nT=300 ## set up number of time points\nsd=1 ## set up standard deviation\nyt=arima.sim(n=T,model = list(ar=phi),sd=sd) # generate ar(2)\n\npar(mfrow = c(3, 1), mar = c(3, 4, 2, 1),  cex.lab = 1.5, cex.main = 1.5)\n### plot simulated data \nts.plot(yt)\n### plot sample ACF\nacf(yt, lag.max = 50, type = \"correlation\",  main = \"sample ACF\")\n### plot sample PACF\npacf(yt, lag.max = 50, main = \"sample PACF\")\n```\n\n::: {.cell-output-display}\n![](C4-L04_files/figure-pdf/ar-sim-real-valued-roots-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n3.  R code to simulate data from an $AR(3)$ with one real reciprocal root and a pair of complex-valued reciprocal roots and plot the corresponding sample ACF and sample PACF\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### Simulate from AR(3) with one real root \n### and a pair of complex roots (e.g., r=0.95 and lambda = 12 and real root with\n### 0.8 modulus)\nset.seed(2021)\nr= c(0.95, 0.95, 0.8) ## modulus\nlambda=c(-12, 12) ## lambda\nrecip_roots=c(r[1:2]*exp(2*pi/lambda*1i), r[3]) ## reciprocal roots\nphi <- numeric(3) # placeholder for phi\nphi[1]=Re(sum(recip_roots)) # ar coefficients at lag 1\nphi[2]=-Re(recip_roots[1]*recip_roots[2] + recip_roots[1]*recip_roots[3] + recip_roots[2]*recip_roots[3]) # ar coefficients at lag 2\nphi[3]=Re(prod(recip_roots))\nphi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  2.445448 -2.218859  0.722000\n```\n\n\n:::\n\n```{.r .cell-code}\nT=300 # number of time points\nsd=1 # standard deviation\nyt=arima.sim(n=T,model = list(ar=phi), sd = sd) # generate ar(3)\n\npar(mfrow = c(3,1),  mar = c(3, 4, 2, 1), cex.lab = 1.5, cex.main = 1.5)\n### plot simulated data \nts.plot(yt)\n### plot sample ACF\nacf(yt, lag.max = 50, type = \"correlation\",  main = \"sample ACF\")\n### plot sample PACF\npacf(yt, lag.max = 50, main = \"sample PACF\")\n```\n\n::: {.cell-output-display}\n![](C4-L04_files/figure-pdf/ar-sim-ar3-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## The AR($p$): Review  :spiral_notepad:  {#sec-arp-review}\n\nThis section is based on material from the [handout](handouts/c4-arp_summary.pdf) but we also covered it in greater detail at the beginning of the lecture.\n\n### AR($p$): Definition, stability, and stationarity {#sec-arp-definition-stability-stationarity}\n\n::: {.callout-info}\n\n### AR($p$) {.unnumbered}\n\nA time series follows a zero-mean autoregressive process of order $p$, of AR($p$), if:\n\n$$\ny_t = \\phi_1 y_{t-1} + \\phi_2 y_{t-2} + \\ldots + \\phi_p y_{t-p} + \\varepsilon_t \\qquad\n$$ {#eq-ar-p}\n\nwhere $\\phi_1, \\ldots, \\phi_p$ are the AR coefficients and $\\varepsilon_t$ is a white noise process \n\nwith $\\varepsilon_t \\sim \\text{i.i.d. } N(0, v)$, for all $t$.\n\n:::\n\nThe AR characteristic polynomial is given by\n\n$$\n\\Phi(u) = 1 - \\phi_1 u - \\phi_2 u^2 - \\ldots - \\phi_p u^p,\n$$\n\nwith $u$ complex-valued.\n\nThe AR($p$) process is stable if $\\phi(u) = 0$ only when $\\|u\\| > 1$. In this case, the process is also stationary and can be written as\n\n$$\ny_t = \\psi(B) \\varepsilon_t = \\sum_{j=0}^{\\infty} \\psi_j \\varepsilon_{t-j},\n$$\n\nwith $\\psi_0 = 1$ and $\\sum_{j=0}^{\\infty} |\\psi_j| < \\infty$. Here $B$ denotes the backshift operator, so $B^j \\varepsilon_t = \\varepsilon_{t-j}$ and\n\n$$\n\\psi(B) = 1 + \\psi_1 B + \\psi_2 B^2 + \\ldots + \\psi_j B^j + \\ldots\n$$\n\nThe AR polynomial can also be written as\n\n$$\n\\Phi(u) = \\prod_{j=1}^{p} (1 - \\alpha_j u),\n$$\n\nwith $\\alpha_j$ being the reciprocal roots of the characteristic polynomial. For the process to be stable (and consequently stationary), $|\\alpha_j| < 1$ for all $j = 1, \\ldots, p$.\n\n### AR($p$): State-space representation {#sec-arp-state-space-representation}\n\nAn AR($p$) can also be represented using the following state-space or dynamic linear (DLM) model representation:\n\n$$\ny_t = F^{\\top} x_t,\n$$ {#eq-ar-p-state-space-y}\n\n$$\nx_t = G x_{t-1} + \\omega_t,\n$$ {#eq-ar-p-state-space-x}\n\nwith \n\n$$\nx_t = (y_t, y_{t-1}, \\dots, y_{t-p+1})^{\\top}\n$$ {#eq-ar-p-state-space-x-vector}\n\nwhere F is a mapping from the state vector to the observed variable:\n\n$$\nF = (1, 0, \\dots, 0)^{\\top}\n$$ {#eq-ar-p-state-space-f-vector}\n\n$$\n\\omega_t = (\\varepsilon_t, 0, \\dots, 0)^{\\top}\n$$ {#eq-ar-p-state-space-omega-vector}\n\n\\index{AR($p$)!state transition matrix}\nand state transition matrix G\n\n$$\nG = \\begin{pmatrix}\n\\phi_1 & \\phi_2 & \\phi_3 & \\dots & \\phi_{p-1} & \\phi_p \\\\\n1 & 0 & 0 & \\dots & 0 & 0 \\\\\n0 & 1 & 0 & \\dots & 0 & 0 \\\\\n\\vdots & \\ddots & \\ddots & \\ddots & & \\vdots \\\\\n0 & 0 & 0 & \\dots & 1 & 0\n\\end{pmatrix}.\n$$ {#eq-ar-p-state-space-g-matrix}\n\n\\index{AR($p$)!forecast function}\nUsing this representation, the expected behavior of the process in the future can be exhibited via the forecast function:\n\n$$\nf_t(h) = E(y_{t+h} \\mid y_{1:t}) = F^\\top G^h x_t, \\quad h > 0, \\quad \\forall t \\ge p\n$$ {#eq-ar-p-forecast-function}\n\nWhere $G^h$ is the $h$^-th^ power of the matrix $G$.\nThe eigenvalues of the matrix $G$ are the reciprocal roots of the characteristic polynomial.\n\n::: {.callout-note}\n### Eigenvalues {.unnumbered}\n\n-   The eigenvalues can be real-valued or complex-valued.\n-   If they are Complex-valued the eigenvalues/reciprocal roots appear in conjugate pairs.\n:::\n\nAssuming the matrix $G$ has $p$ distinct eigenvalues, we can decompose $G$ into $G = E \\Lambda E^{-1}$, with\n\n$$\n\\Lambda = \\text{diag}(\\alpha_1, \\dots, \\alpha_p),\n$$\n\nfor a matrix of corresponding eigenvectors $E$. Then, $G^h = E \\Lambda^h E^{-1}$ and we have:\n\n$$\nf_t(h) = \\sum_{j=1}^{p} c_{tj} \\alpha_j^h.\n$$\n\n### ACF of AR($p$) {#sec-arp-acf}\n\nFor a general AR($p$), the ACF is given in terms of the homogeneous difference equation:\n\n$$\n\\rho(h) - \\phi_1 \\rho(h-1) - \\ldots - \\phi_p \\rho(h-p) = 0, \\quad h > 0.\n$$\n\nAssuming that $\\alpha_1, \\dots, \\alpha_r$ denotes the characteristic reciprocal roots each with multiplicity $m_1, \\ldots, m_r$, respectively, with $\\sum_{i=1}^{r} m_i = p$. Then, the general solution is\n\n$$\n\\rho(h) = \\alpha_1^h p_1(h) + \\ldots + \\alpha_r^h p_r(h),\n$$\n\nwith $p_j(h)$ being a polynomial of degree $m_j - 1$.\n\n### Example: AR(1) {#sec-arp-example-ar1}\n\nWe already know that for $h \\ge 0$, $\\rho(h) = \\phi^h$. Using the result above, we have\n\n$$\n\\rho(h) = a \\phi^h,\n$$\n\nand so to find $a$, we take $\\rho(0) = 1 = a \\phi^0$, hence $a = 1$.\n\n### Example: AR(2) {#sec-arp-example-ar2}\n\nSimilarly, using the result above in the case of two complex-valued reciprocal roots, we have\n\n$$\n\\rho(h) = a \\alpha_1^h + b \\alpha_2^h = c r^h \\cos(\\omega h + d).\n$$\n\n\n### PACF of AR($p$) {#sec-arp-pacf}\n\n\\index{PACF}\n\\index{AR($p$)!PACF}\n\\index{Durbin-Levinson}\nWe can use the **Durbin-Levinson recursion** to obtain the PACF of an AR($p$). c.f. @sec-durbin-levinson.\n\nUsing the same representation but substituting the true **autocovariances** and **autocorrelations** with their sampled versions, we can also obtain the **sample PACF**.\n\nIt is possible to show that the PACF of an AR($p$) is equal to zero for $h > p$.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}