{
  "hash": "a979eab60e93bb409e8e346be60aba24",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Q&A from Bayesian Forecasting and Dynamic Models - Chapter 3\"\n---\n\n## Question from Chapter 3 \n\n::: {.callout-tip}\nUnless stated explicitly these exercises refer to a univariate time series $\\{Y_t\\}$ modelled by the closed regression DLM $\\{F_t , 1, V_t , W_t\\}$ of Definition 3.2 with known variances and/or known discount factor $\\delta$ as follows:\n\n- Observation equation: $Y_t = F_t \\theta_t + \\nu_t$, $\\nu_t \\sim \\mathcal{N}[0, V_t]$,\n- System equation: $\\theta_t = \\theta_{t-1} + \\omega_t$, $\\omega_t \\sim \\mathcal{N}[0, W_t]$,\n- Initial prior: $(\\theta_0 \\mid \\mathcal{D}_0) \\sim \\mathcal{N}[m_0 , C_0]$.\n:::\n\n:::: {#exr-ch3-ex01}\n### Bivariate Normal Distribution in DLM\n\nIn the DLM $\\{F_t , 1, 100, 0\\}$ suppose that the sequence $\\theta_t = \\theta$ is a\nprecisely known constant but that the regressor variable sequence $F_t$ is uncontrollable [**uncontrollable**]{.column-margin}. \nYou model $F_t$ as a sequence of independent normal random quantities, $F_t \\sim \\mathcal{N}[0, 400]$. \nGiven $\\mathcal{D}_{t-1}$, answer the following questions.\n\n(a) Prove that $Y_t$ and $F_t$ have a bivariate normal distribution and\nidentify its mean vector and variance matrix.\n\n(b) What is the correlation between $Y_t$ and $F_t$?\n\n(c) What is the regression coefficient of $F_t$ on $Y_t$?\n\n(d) What is the posterior distribution of $(F_t \\mid Y_t, \\mathcal{D}_{t-1})$?\n::::\n\n::: {#exr-ch3-ex02}\n### Regression DLM with Known $F_t$\n\nIn @exr-ch3-ex01 suppose that the sequence $\\theta_t$ is known but not constant. \nYou also adopt a random walk model for $F_t$, so that $F_t = F_{t-1} + \\varepsilon_t$ with independent $\\varepsilon_t \\sim \\mathcal{N}[0, U ]$. \nShow that your overall model is equivalent to the simple regression DLM $\\{\\theta_t , 1, 100, U \\}$ with regressor variable $\\theta_t$ and parameter $F_t$.\n:::\n\n\n::: {#exr-ch3-ex03}\n### First-order Polynomial DLM\n\nIn the DLM $\\{F_t , 1, V_t , W_t\\}$, suppose that $F_t \\neq 0$ for all $t$.\n\n(a) Show that the series $X_t = Y_t / F_t$ follows a first-order polynomial\n    DLM and identify it fully.\n\n(b) Verify that the updating equations for the regression DLM can be \n    deduced from those of the first-order polynomial DLM.\n\n(c) What happens if $F_t = 0$?\n:::\n\n\n::: {#exr-ch3-ex04}\n### Predictability Measure\nOne measure of the predictability of $Y_t$ at time $t-1$ is the modulus\n$1/2$ of the reciprocal of the coefficient of variation, given by $|f_t/Q_t|$\nExplore this measure as a function of $F_t \\in [-100, 100]$ for each of\nthe cases $R_t = 0, 10, 20, 50$, when $m_t = 10$, and $V_t = 100$.\n:::\n\n::: {#exr-ch3-ex05}\n### Optimal Design of Control Variable\n\nSuppose that $V_t$ is a known function of a control variable $F_t$. In\nparticular, let $V_t = V(a + |F_t|^p)$ for known quantities $V$, $a$ and $p$.\n\n(a) How should $F_t$ be chosen in order to maximise the posterior\nprecision $C_{t-1}$ subject to $|F_t| < k$ for some $k > 0$? What is the\noptimal design value of $F_t$ in the case $a = 8$, $p = 3$ and $k = 10$?\n\n(b) How does this problem change when $V$ is unknown and is\nestimated from the data?\n:::\n\n\n::: {#exr-ch3-ex06}\nFor the discount regression DLM in which $V_t$ is known for all $t$ and\n$R_t = C_{t-1} /\\delta$, show that the updating equations can be written as\n\n$$\nm_t = C_t \\, \\delta^{t} \\, C_{0}^{-1} m_0 + C_t\n\\sum_{j=0}^{t-1} \\delta^{j} F_{t-j} \\, V_{t-j}^{-1} \\, Y_{t-j}\n$$\n\nand\n\n$$\nC_{t}^{-1} = \\delta^{t} C_{0}^{-1} +\n\\sum_{j=0}^{t-1} \\delta^{j} F_{t-j}^{2} \\, V_{t-j}^{-1}.\n$$\n\nDeduce that as $t \\to \\infty$, $C_{t}^{-1} \\to 0$ and\n\n$$\nm_t \\to\n\\frac{\\sum_{j=0}^{t-1} \\delta^{j} F_{t-j} \\, V_{t-j}^{-1} \\, Y_{t-j}}\n{\\sum_{j=0}^{t-1} \\delta^{j} F_{t-j}^{2} \\, V_{t-j}^{-1}}.\n$$\n:::\n\n::: {#exr-ch3-ex07}\nConsider discount weighted regression applied to the estimation of\na parameter $\\theta_t$ by the value $m_t$. In DWR, the estimate $m_t$ is chosen\nto minimise the discounted sum of squares\n\n$$\nS(\\theta) = \\sum_{j=0}^{t-1} \\delta^{j} \\left(Y_{t-j} - F_{t-j}\\,\\theta\\right)^{2},\n$$\n\nwhere all quantities other than $\\theta$ are known.\n\n(a) Show that\n\n$$\nm_t = \\frac{\\sum_{j=0}^{t-1} \\delta^{j} F_{t-j} Y_{t-j}}{\\sum_{j=0}^{t-1} \\delta^{j} F_{t-j}^{2}}.\n$$\n\n(b) Generalising (a), suppose that\n\n$$\nY_t = F_t \\theta + \\nu_t, \\qquad \\nu_t \\sim \\mathcal{N}[0, V_t],\n$$\n\nand that $m_t$ is more appropriately chosen to minimise\n\n$$\nS(\\theta) = \\sum_{j=0}^{t-1} \\delta^{j} V_{t-j}^{-1} \\left(Y_{t-j} - F_{t-j}\\,\\theta\\right)^{2}.\n$$\n\nShow that\n\n$$\nm_t = \\frac{\\sum_{j=0}^{t-1} \\delta^{j} F_{t-j} V_{t-j}^{-1} Y_{t-j}}{\\sum_{j=0}^{t-1} \\delta^{j} F_{t-j}^{2} V_{t-j}^{-1}}.\n$$\n\n(c) Compare these results with those of the previous question to see that the estimates correspond to those from the discount DLM with the uninformative prior $C_0^{-1} = 0$.\n:::\n\n::: {#exr-ch3-ex08}\nSuppose that $V_t = V\\,k_t$, where $V = 1/\\phi$ is unknown and $k_t$ is a\nknown variance multiplier. Show how the analysis summarized in\nthe table in [Section 3.4.1] is modified.\n:::\n\n::: {#exr-ch3-ex09}\nConsider the simple regression DLM $\\{(-1)^t k, 1, V, W\\}$, in which\n$k > 0$ is a known constant.\n\n(a) By reference to the first-order polynomial constant DLM convergence \nresults or otherwise, prove that $\\lim_{t \\to \\infty} C_t = C$ exists.\nObtain $C$ and the limiting values of $Q_t$ and $|A_t|$.\n\n(b) Treating the limiting value $C$ as a function of $k$, verify that it\nis equal to $W$ when $k = V/(2W)$.\n:::\n\n::: {#exr-ch3-ex10} \nConsider the company sales/total market series in the example of\nSection 3.4.2. Perform similar analyses of this data using the same\nDLM but varying the discount factor over the range 0.6, 0.65, . . . , 1.\nExplore the sensitivity to inferences about the time trajectory of $\\theta_t$\nas the discount factor varies in the following ways:\n\n(a) Plot $m_t$ versus $t$, with intervals based on $C_t^{1/2}$\nto represent\nuncertainty, for each value of $\\delta$ and comment on differences\nwith respect to $\\delta$.\n\n(b) Compare the final estimates of observational variance $S_{42}$ as $\\delta$\nvaries. Do the same for prediction variances $Q_{42}$. Discuss the\npatterns of behaviour.\n\n(c) Use MSE, MAD and LLR measures to assess the predictive\nperformance of the models relative to the static model defined\nby $\\delta = 1$.\n:::\n\n\n::: {#exr-ch3-ex11}\nConsider a retrospective analysis in which inferences are made about\nhistorical parametric values based on the current data. \nIn particular, this question concerns inferences about $\\theta_{t-1}$ given $\\mathcal{D}_t$ for the\nDLM $\\{F_t, 1, V_t, W_t\\}$ with known variances.\n\n(a) Use the system equation directly to show that\n\n$$\nC[\\theta_t, \\theta_{t-1}\\mid \\mathcal{D}_{t-1}] = B_{t-1}\\,V[\\theta_t \\mid \\mathcal{D}_{t-1}],\n$$\n\nfor some $B_{t-1}$ lying between $0$ and $1$, and identify $B_{t-1}$.\n\n(b) Deduce that\n\n$$\nC[\\theta_{t-1}, Y_t \\mid \\mathcal{D}_{t-1}] = B_{t-1}\\,C[\\theta_t, Y_t \\mid \\mathcal{D}_{t-1}].\n$$\n\n(c) Hence identify the moments of the joint normal distribution\nof $(\\theta_{t-1}, \\theta_t, Y_t \\mid \\mathcal{D}_{t-1})$, and from this, those of the conditional\ndistribution of $(\\theta_{t-1} \\mid \\mathcal{D}_t)$ (by conditioning on $Y_t$ in addition to\n$\\mathcal{D}_{t-1}$). Verify that the regression coefficient of $\\theta_{t-1}$ on $Y_t$ is\n$B_{t-1} A_t$, where $A_t$ is the usual regression coefficient (adaptive\ncoefficient) of $\\theta_t$ on $Y_t$ given $\\mathcal{D}_{t-1}$.\n\n(d) Deduce that $(\\theta_{t-1} \\mid \\mathcal{D}_t)$ is normal with moments that can be\nwritten as\n\n$$\nE[\\theta_{t-1} \\mid \\mathcal{D}_t] = m_{t-1} + B_{t-1}\\big(E[\\theta_t \\mid \\mathcal{D}_t] - E[\\theta_t \\mid \\mathcal{D}_{t-1}]\\big)\n$$\n\nand\n\n$$\nV[\\theta_{t-1} \\mid \\mathcal{D}_t] = C_{t-1} - B_{t-1}^{2}\\,\\big(V[\\theta_t \\mid \\mathcal{D}_{t-1}] - V[\\theta_t \\mid \\mathcal{D}_t]\\big).\n$$\n:::\n\n::: {#exr-ch3-ex12}\nGeneralize the results of the previous exercise to allow retrospection\nback over time for more than one step, calculating the distribution\nof $(\\theta_{t-k} \\mid \\mathcal{D}_t)$ for any $k$, $(0 \\le k \\le t)$. Do this as follows:\n\n(a) Using the observation and evolution equations directly, show\nthat for any $r \\ge 1$,\n$$\nC[\\theta_{t-k}, Y_{t-k+r} \\mid \\mathcal{D}_{t-k}] \\;=\\; B_{t-k}\\, C[\\theta_{t-k+1}, Y_{t-k+r} \\mid \\mathcal{D}_{t-k}],\n$$\nwhere for any $s$, $B_s = C_s / R_{s+1}$ lies between $0$ and $1$.\n\n(b) Writing $X_t(k) = (Y_{t-k+1}, \\ldots, Y_t)$, deduce from (a) that\n$$\nC[\\theta_{t-k}, X_t(k) \\mid \\mathcal{D}_{t-k}] \\;=\\; B_{t-k}\\, C[\\theta_{t-k+1}, X_t(k) \\mid \\mathcal{D}_{t-k}].\n$$\n\n(c) Hence identify the moments of the joint normal distribution of\n$(\\theta_{t-k}, \\theta_{t-k+1}, X_t(k) \\mid \\mathcal{D}_{t-k})$,\nand from this those of the conditional distributions of $(\\theta_{t-k} \\mid \\mathcal{D}_t)$\nand $(\\theta_{t-k+1} \\mid \\mathcal{D}_t)$ (by conditioning on $X_t(k)$ in addition to $\\mathcal{D}_{t-k}$ and noting that $\\mathcal{D}_t = \\{X_t(k), \\mathcal{D}_{t-k}\\}$). \nUsing (b), verify that\nthe regression coefficient vector of $\\theta_{t-k}$ on $X_t(k)$ is $B_{t-k}$ times\nthat of $\\theta_{t-k+1}$ on $X_t(k)$.\n\n(d) Deduce that $(\\theta_{t-k} \\mid \\mathcal{D}_t)$ is normal with moments that can be\nwritten as\n$$\nE[\\theta_{t-k} \\mid \\mathcal{D}_t] \\;=\\; m_{t-k} + B_{t-k}\\big(E[\\theta_{t-k+1} \\mid \\mathcal{D}_t] - E[\\theta_{t-k+1} \\mid \\mathcal{D}_{t-k}]\\big)\n$$\nand\n$$\nV[\\theta_{t-k} \\mid \\mathcal{D}_t] \\;=\\; C_{t-k} - B_{t-k}^{2}\\,\\big(V[\\theta_{t-k+1} \\mid \\mathcal{D}_{t-k}] - V[\\theta_{t-k+1} \\mid \\mathcal{D}_t]\\big).\n$$\n\n(e) Let the above moments be denoted by $a_t(-k)$ and $R_t(-k)$,\nso that $(\\theta_{t-k} \\mid \\mathcal{D}_t) \\sim \\mathcal{N}[a_t(-k), R_t(-k)]$. Verify that the above,\nretrospective updating equations provide these moments back-\nwards over time for $k = t - 1, t - 2, \\ldots, 0$ via\n$$\na_t(-k) = m_{t-k} + B_{t-k}\\,[a_t(-k + 1) - a_{t-k+1}]\n$$\nand\n$$\nR_t(-k) = C_{t-k} - B_{t-k}^{2}\\,[R_t(-k + 1) - R_{t-k+1}]\n$$\nwith $a_s = m_{s-1}$ and $R_s = C_{s-1} + W_s$ for all $s$, and initial values\n$a_t(0) = m_t$ and $R_t(0) = C_t$.\n:::\n\n\n:::: {#exr-ch3-ex13}\nIn the last two questions, employing the discount regression model\n$\\{F_t , 1, V, W_t\\}$, where $W_t = C_{t-1} (\\delta^{-1} - 1)$, show that for $k \\ge 0$,\n$B_{t-1} = \\delta$, $a_t (-k) = a_{t-1} (-k + 1) + \\delta^{k} A_t e_t$\nand\n$R_t (-k) = R_{t-1} (-k + 1) - \\delta^{2k} A_t^{2} Q_t$.\nThis provides for neat and simple updating of the retrospective means and variances.\n::::\n\n:::: {#exr-ch3-ex14}\nSuppose the yield $Y_t$ of the $t$th batch of a manufacturing plant is truly represented by\n\n$$\n\\begin{aligned}\nY_t &= 70 - (X_t - 3)^{2} + \\eta_t, && \\eta_t &\\sim \\mathcal{N}[0, V], \\\\\nX_t &\\sim \\{F_t , 1, V, W\\}, && (\\theta_0 \\mid \\mathcal{D}_0) & \\sim \\mathcal{N}[1, V].\n\\end{aligned}\n$$\n\nInitially, the setting $F_1 = 3$ is optimal in the sense of maximising the expected yield.\n\n(a) If $F_t$ is kept constant at 3, or if from any other speciﬁed time it\nis kept constant at its then perceived optimal value, what are\nthe consequences?\n\n(b) Plant managers have production targets to meet and dislike\nchanging operating conditions, fearing a drop in yield. If you\nwere the production director would you approve this attitude\nor would you introduce a policy encouraging plant managers\nto make regular small experimental variations about the then\nperceived optimal value of $F_t$?\n::::\n\n::: {#exr-ch3-ex15}\nThe following data set refers to an internationally famous canned product. \nThe objective is to establish a relationship between market share and price \nto make short-term pricing decisions. \nThe observation series $Y_t$ is the percentage market share for quarter $t$\nminus $42\\%$, and $F_t$ is a linear function of the real price.\n\n|Qtr. t|  1  |  2   |  3  | 4|5|6|7|8|9|10|11|12|\n|---   |---  |---   |---  |---  |---  |---  |---  |---  |---  |---  |---  |---  |\n|$Y_t$ | 0.45| 0.83 | 1.45| 0.88|-1.43|-1.50|-2.33|-0.78| 0.58| 1.10| ?| ?\n|$F_T$ |-0.50|-1.30 |-1.50|-0.84|-0.65|-1.19|2.12|0.46|-0.63|-1.22|-2.00|2.00|\n\nAdopt the simple discount regression DLM $\\{F_t , 1, V, W_t \\}$ with\n$\\delta = 0.975$.\n\n(a) Carry out sequential forecasting with known variance $V = 0.2$ and $\\theta_0 \\sim \\mathcal{N}[0, 1]$. Either by hand or computer prepare a calculation table that produces $R_t , A_t , f_t , Q_t , e_t , m_t$ and $C_t$ for each $t$. What are your final inferences about the price elasticity $\\theta_{10}$ ?\nWhat is your forecast for the market share in the next two quarters?\n\n(b) Repeat the analysis and inference when $V$ is an unknown constant variance starting with $n_0 = 1$ and $S_0 = 0.2$.\n:::\n\n\n::: {.solution}\n\n\nHere are elementary solutions in python and R that. \n\n### Update equations {.unnumbered .unlisted}\n\nThe updates equations are:\n\n**Known $V$:**\n\n$$\n\\begin{aligned}\na_t&=m_{t-1} & \\text{(prior mean)}\\\\\nR_t&=\\tfrac{C_{t-1}}{\\delta} & \\text{(prior var, discount)}\\\\\nf_t&=F_t a_t,\\quad e_t=Y_t-f_t & \\text{(forecast \\& error)}\\\\\nQ_t&=F_t^2R_t+V & \\text{(forecast var)}\\\\\nA_t&=\\tfrac{R_tF_t}{Q_t} & \\text{(gain)}\\\\\nm_t&=a_t+A_te_t & \\text{(posterior mean)}\\\\\nC_t&=(1-A_tF_t)R_t & \\text{(posterior var)}\n\\end{aligned}\n$$\n\n**Unknown $V$ (NIG, “starred” form):**\n\n$$\n\\begin{aligned}\na_t&=m_{t-1},\\quad R_t^*=\\tfrac{C_{t-1}^*}{\\delta} \\\\\nf_t&=F_t a_t,\\quad e_t=Y_t-f_t \\\\\nq_t^*&=F_t^2R_t^*+1,\\quad A_t=\\tfrac{R_t^*F_t}{q_t^*} \\\\\nm_t&=a_t+A_te_t,\\quad C_t^*=(1-A_tF_t)R_t^* \\\\\nn_t&=n_{t-1}+1,\\quad S_t=\\frac{n_{t-1}S_{t-1}+e_t^2/q_t^*}{n_t}\n\\end{aligned}\n$$\n\nForecast $h$-ahead: mean \n\n$$\n\\begin{aligned}\n    F_{t+h}m_t \\text{, var } F_{t+h}^2\\,C_t/\\delta^h+V && \\text{(known V)} \\\\\n    S_t q_{t+h}^* \\text{ with }  q_{t+h}^*=F_{t+h}^2(C_t^*/\\delta^h)+1 && \\text{(unknown V)}\n\\end{aligned}\n$$\n\n\n:::: {.panel-tabset}\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Compute tables for Exercise ch3-ex15 parts (a) and (b) and save as CSVs\nimport pandas as pd\nimport numpy as np\nimport math\n\ndelta = 0.975\nV_known = 0.2\nm0 = 0.0\nC0 = 1.0\n\nY = [0.45, 0.83, 1.45, 0.88, -1.43, -1.50, -2.33, -0.78, 0.58, 1.10]  # t=1..10\nF = [-0.50, -1.30, -1.50, -0.84, -0.65, -1.19, 2.12, 0.46, -0.63, -1.22, -2.00, 2.00]  # t=1..12\n\ndef run_known_variance(Y, F, m0, C0, delta, V):\n    rows = []\n    m_prev = m0\n    C_prev = C0\n    for t in range(1, 11):  # t=1..10\n        Ft = F[t-1]\n        yt = Y[t-1]\n        a_t = m_prev\n        R_t = C_prev / delta\n        f_t = Ft * a_t\n        Q_t = Ft*Ft * R_t + V\n        e_t = yt - f_t\n        A_t = R_t * Ft / Q_t\n        m_t = a_t + A_t * e_t\n        C_t = (1 - A_t * Ft) * R_t\n        rows.append({\n            \"t\": t, \"Ft\": Ft, \"Yt\": yt, \"R_t\": R_t, \"A_t\": A_t, \"f_t\": f_t, \"Q_t\": Q_t, \"e_t\": e_t, \"m_t\": m_t, \"C_t\": C_t\n        })\n        m_prev, C_prev = m_t, C_t\n    # forecasts for t=11 and t=12 without new data\n    forecasts = []\n    C_t = C_prev\n    m_t = m_prev\n    for h in [1,2]:\n        Ft = F[10 + h - 1]  # F_11, F_12\n        R_h = C_t / (delta**h)\n        f_h = Ft * m_t\n        Q_h = Ft*Ft * R_h + V\n        forecasts.append({\"h\": h, \"Ft\": Ft, \"f\": f_h, \"Q\": Q_h, \"sd\": math.sqrt(Q_h),\n                          \"Share_mean_%\": 42.0 + f_h})\n    return pd.DataFrame(rows), {\"m10\": m_prev, \"C10\": C_prev}, pd.DataFrame(forecasts)\n\ndef run_unknown_variance(Y, F, m0, C0_star, delta, n0, S0):\n    rows = []\n    m_prev = m0\n    C_prev = C0_star\n    n = n0\n    S = S0\n    for t in range(1, 11):\n        Ft = F[t-1]; yt = Y[t-1]\n        a_t = m_prev\n        R_t = C_prev / delta  # starred\n        f_t = Ft * a_t\n        q_t = Ft*Ft * R_t + 1.0  # starred\n        e_t = yt - f_t\n        A_t = R_t * Ft / q_t\n        m_t = a_t + A_t * e_t\n        C_t = (1 - A_t * Ft) * R_t\n        n_new = n + 1\n        S_new = (n * S + (e_t**2) / q_t) / n_new\n        rows.append({\n            \"t\": t, \"Ft\": Ft, \"Yt\": yt, \"R_t*\": R_t, \"A_t\": A_t, \"f_t\": f_t, \"q_t*\": q_t, \"e_t\": e_t, \n            \"m_t\": m_t, \"C_t*\": C_t, \"n_t\": n_new, \"S_t\": S_new\n        })\n        m_prev, C_prev, n, S = m_t, C_t, n_new, S_new\n    forecasts = []\n    for h in [1,2]:\n        Ft = F[10 + h - 1]\n        R_h = C_prev / (delta**h)\n        q_h = Ft*Ft * R_h + 1.0\n        var = S * q_h\n        mean = Ft * m_prev\n        forecasts.append({\"h\": h, \"Ft\": Ft, \"f\": mean, \"q*\": q_h, \"S\": S, \"Q\": var, \"sd\": math.sqrt(var),\n                          \"Share_mean_%\": 42.0 + mean})\n    return pd.DataFrame(rows), {\"m10\": m_prev, \"C10*\": C_prev, \"n10\": n, \"S10\": S}, pd.DataFrame(forecasts)\n\n# Run both parts\ndf_known, state10_known, fc_known = run_known_variance(Y, F, m0, C0, delta, V_known)\ndf_u, state10_u, fc_u = run_unknown_variance(Y, F, m0, 1.0, delta, 1, 0.2)\n\n# Save CSVs\ndf_known.to_csv('exr-ch3-ex15_partA_knownV_filter.csv', index=False)\nfc_known.to_csv('exr-ch3-ex15_partA_knownV_forecasts.csv', index=False)\ndf_u.to_csv('exr-ch3-ex15_partB_unknownV_filter.csv', index=False)\nfc_u.to_csv('exr-ch3-ex15_partB_unknownV_forecasts.csv', index=False)\n\n# Show compact summaries\nstate10_known, state10_u, fc_known.round(4), fc_u.round(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n({'m10': -0.6355690433103104, 'C10': 0.01650248358749487}, {'m10': -0.6045867145935548, 'C10*': 0.07849015335007685, 'n10': 11, 'S10': 0.9760333998940381},    h   Ft       f       Q      sd  Share_mean_%\n0  1 -2.0  1.2711  0.2677  0.5174       43.2711\n1  2  2.0 -1.2711  0.2694  0.5191       40.7289,    h   Ft       f      q*      S       Q      sd  Share_mean_%\n0  1 -2.0  1.2092  1.3220  0.976  1.2903  1.1359       43.2092\n1  2  2.0 -1.2092  1.3303  0.976  1.2984  1.1395       40.7908)\n```\n\n\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## exr-ch3-ex15 — discount regression DLM in base R\n## Part (a): known V; Part (b): unknown V via NIG (starred) recursions.\n## References: Prado, Ferreira & West (2023), Ch.3 discount regression.\n\nY <- c(0.45, 0.83, 1.45, 0.88, -1.43, -1.50, -2.33, -0.78, 0.58, 1.10) # t=1..10\nFv <- c(-0.50, -1.30, -1.50, -0.84, -0.65, -1.19, 2.12, 0.46, -0.63, -1.22, -2.00, 2.00) # t=1..12\ndelta <- 0.975\n\nkstep_R <- function(C, delta, h) C / (delta^h)\n\n## ---------- Part (a): KNOWN V ----------\ndlm_knownV <- function(Y, Fv, delta, V, m0=0, C0=1) {\n  stopifnot(length(Y) == 10L, length(Fv) >= 12L)\n  n <- length(Y)\n  rows <- vector(\"list\", n)\n  m <- m0; C <- C0\n  for (t in seq_len(n)) {\n    Ft <- Fv[t]; yt <- Y[t]\n    a  <- m\n    R  <- C / delta\n    f  <- Ft * a\n    Q  <- Ft*Ft * R + V\n    e  <- yt - f\n    A  <- R * Ft / Q\n    m  <- a + A * e\n    C  <- (1 - A * Ft) * R\n    rows[[t]] <- data.frame(t=t, Ft=Ft, Yt=yt, R_t=R, A_t=A, f_t=f, Q_t=Q, e_t=e, m_t=m, C_t=C)\n  }\n  filt <- do.call(rbind, rows)\n\n  ## 1- and 2-step forecasts (t=11,12) using last (m,C)\n  fcast <- lapply(1:2, function(h) {\n    Ft <- Fv[10 + h]\n    R_h <- kstep_R(C, delta, h)\n    f_h <- Ft * m\n    Q_h <- Ft*Ft * R_h + V\n    data.frame(h=h, Ft=Ft, f=f_h, Q=Q_h, sd=sqrt(Q_h),\n               Share_mean_pct = 42 + f_h,\n               Share_L95 = 42 + (f_h - qnorm(0.975)*sqrt(Q_h)),\n               Share_U95 = 42 + (f_h + qnorm(0.975)*sqrt(Q_h)))\n  })\n  fcast <- do.call(rbind, fcast)\n\n  list(filter=filt, state=list(m10=m, C10=C), forecast=fcast)\n}\n\n## ---------- Part (b): UNKNOWN V (NIG; starred) ----------\ndlm_unknownV <- function(Y, Fv, delta, n0=1, S0=0.2, m0=0, C0_star=1) {\n  stopifnot(length(Y) == 10L, length(Fv) >= 12L)\n  n <- length(Y)\n  rows <- vector(\"list\", n)\n  m <- m0; C <- C0_star; ndf <- n0; S <- S0\n  for (t in seq_len(n)) {\n    Ft <- Fv[t]; yt <- Y[t]\n    a   <- m\n    R   <- C / delta                   # starred\n    f   <- Ft * a\n    qst <- Ft*Ft * R + 1               # q_t^*\n    e   <- yt - f\n    A   <- R * Ft / qst\n    m   <- a + A * e\n    C   <- (1 - A * Ft) * R\n    ndf_new <- ndf + 1\n    S_new   <- (ndf*S + (e^2)/qst) / ndf_new\n    rows[[t]] <- data.frame(t=t, Ft=Ft, Yt=yt, R_t_star=R, A_t=A, f_t=f,\n                            q_t_star=qst, e_t=e, m_t=m, C_t_star=C,\n                            n_t=ndf_new, S_t=S_new)\n    ndf <- ndf_new; S <- S_new\n  }\n  filt <- do.call(rbind, rows)\n\n  ## Forecasts (t=11,12): Student-t with df = n_t, mean = Ft*m, var = S * q*_h\n  tcrit <- function(df) qt(0.975, df=df)\n  fcast <- lapply(1:2, function(h) {\n    Ft <- Fv[10 + h]\n    R_h <- kstep_R(C, delta, h)\n    qh  <- Ft*Ft * R_h + 1\n    mean <- Ft * m\n    var  <- S * qh\n    sd   <- sqrt(var)\n    df   <- ndf\n    mL   <- mean - tcrit(df)*sd\n    mU   <- mean + tcrit(df)*sd\n    data.frame(h=h, Ft=Ft, f=mean, q_star=qh, S=S, Q=var, sd=sd, df=df,\n               Share_mean_pct = 42 + mean,\n               Share_L95 = 42 + mL,\n               Share_U95 = 42 + mU)\n  })\n  fcast <- do.call(rbind, fcast)\n\n  list(filter=filt, state=list(m10=m, C10_star=C, n10=ndf, S10=S),\n       forecast=fcast)\n}\n\n## ---------- Run both parts ----------\nres_a <- dlm_knownV(Y, Fv, delta, V=0.2, m0=0, C0=1)\nres_b <- dlm_unknownV(Y, Fv, delta, n0=1, S0=0.2, m0=0, C0_star=1)\n\n## Save tables if desired:\n# write.csv(res_a$filter, \"exr-ch3-ex15_partA_knownV_filter.csv\", row.names=FALSE)\n# write.csv(res_a$forecast, \"exr-ch3-ex15_partA_knownV_forecasts.csv\", row.names=FALSE)\n# write.csv(res_b$filter, \"exr-ch3-ex15_partB_unknownV_filter.csv\", row.names=FALSE)\n# write.csv(res_b$forecast, \"exr-ch3-ex15_partB_unknownV_forecasts.csv\", row.names=FALSE)\n\n## ---------- Print key answers ----------\ncat(\"Part (a): known V=0.2\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPart (a): known V=0.2\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"theta_10 mean=%.4f, Var=%.5f, SE=%.4f\\n\",\n            res_a$state$m10, res_a$state$C10, sqrt(res_a$state$C10)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntheta_10 mean=-0.6356, Var=0.01650, SE=0.1285\n```\n\n\n:::\n\n```{.r .cell-code}\nci_a <- res_a$state$m10 + c(-1,1)*qnorm(0.975)*sqrt(res_a$state$C10)\ncat(sprintf(\"95%% CI for theta_10: [%.4f, %.4f]\\n\\n\", ci_a[1], ci_a[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for theta_10: [-0.8873, -0.3838]\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(res_a$forecast, row.names=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n h Ft         f         Q        sd Share_mean_pct Share_L95 Share_U95\n 1 -2  1.271138 0.2677025 0.5173997       43.27114  42.25705  44.28522\n 2  2 -1.271138 0.2694385 0.5190746       40.72886  39.71149  41.74623\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nPart (b): unknown V (n0=1, S0=0.2)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPart (b): unknown V (n0=1, S0=0.2)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"theta_10 mean=%.4f, Var|V = S10*C10* = %.5f, SE=%.4f, n10=%d\\n\",\n            res_b$state$m10, res_b$state$S10*res_b$state$C10_star,\n            sqrt(res_b$state$S10*res_b$state$C10_star), res_b$state$n10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntheta_10 mean=-0.6046, Var|V = S10*C10* = 0.07661, SE=0.2768, n10=11\n```\n\n\n:::\n\n```{.r .cell-code}\ntcrit10 <- qt(0.975, df=res_b$state$n10)\nci_b <- res_b$state$m10 + c(-1,1)*tcrit10*sqrt(res_b$state$S10*res_b$state$C10_star)\ncat(sprintf(\"95%% t CI for theta_10: [%.4f, %.4f]\\n\\n\", ci_b[1], ci_b[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% t CI for theta_10: [-1.2138, 0.0046]\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(res_b$forecast, row.names=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n h Ft         f   q_star         S        Q       sd df Share_mean_pct\n 1 -2  1.209173 1.322011 0.9760334 1.290327 1.135926 11       43.20917\n 2  2 -1.209173 1.330268 0.9760334 1.298386 1.139467 11       40.79083\n Share_L95 Share_U95\n  40.70902  45.70933\n  38.28288  43.29878\n```\n\n\n:::\n\n```{.r .cell-code}\n## ------- Expected numeric (sanity, should match ±1e-3):\n## Part (a): theta_10 ≈ -0.6356, Var ≈ 0.01650\n## Q11 mean share ≈ 43.271, Q12 ≈ 40.729\n## Part (b): theta_10 ≈ -0.6046, Var|V ≈ 0.0766, n10=11\n## Q11 mean share ≈ 43.209, Q12 ≈ 40.791\n```\n:::\n\n\n::::\n\n\nHere’s the full sequential fit and the forecasts.\n\n### (a) Known $V=0.2$, $\\delta=0.975$, $\\theta_0\\sim\\mathcal N(0,1)$\n\n* Final posterior for price elasticity at $t=10$:\n  $\\hat\\theta_{10}= -0.6356,\\quad \\mathrm{Var}(\\theta_{10})=0.01650$ $\\Rightarrow$ s.e. $=0.1285$.\n  95% CI: $[-0.8874,\\,-0.3838]$.\n* One- and two-step forecasts (market share = $42\\%+Y$):\n\n  * Q11: $\\mathbb E[\\text{share}]=43.27\\%$, 95% PI $[42.26,\\,44.29]\\%$.\n  * Q12: $\\mathbb E[\\text{share}]=40.73\\%$, 95% PI $[39.71,\\,41.75]\\%$.\n\nCalc table (per $t=1{:}10$) with $R_t,A_t,f_t,Q_t,e_t,m_t,C_t$:\n[part A filter (CSV)](exr-ch3-ex15_partA_knownV_filter.csv) · [part A forecasts (CSV)](exr-ch3-ex15_partA_knownV_forecasts.csv)\n\n---\n\n### (b) Unknown $V$ with $n_0=1,\\,S_0=0.2$ (standard NIG DLM; starred form, $\\delta=0.975$)\n\n* Final posterior for price elasticity at $t=10$:\n  $\\hat\\theta_{10}= -0.6046,\\quad \\mathrm{Var}(\\theta_{10}\\mid V)=S_{10}C_{10}^*=0.9760\\times0.07849=0.0766$ $\\Rightarrow$ s.e. $=0.2768$, $n_{10}=11$.\n  95% $t_{11}$ CI: $[-1.2138,\\,0.0046]$.\n* Forecasts (wider, since $V$ unknown):\n\n  * Q11: $\\mathbb E[\\text{share}]=43.21\\%$, 95% PI $[40.71,\\,45.71]\\%$.\n  * Q12: $\\mathbb E[\\text{share}]=40.79\\%$, 95% PI $[38.28,\\,43.30]\\%$.\n\nCalc table (per $t=1{:}10$) with $R_t^*,A_t,f_t,q_t^*,e_t,m_t,C_t^*,n_t,S_t$:\n[part B filter (CSV)](exr-ch3-ex15_partB_unknownV_filter.csv) · [part B forecasts (CSV)](sandbox:/exr-ch3-ex15_partB_unknownV_forecasts.csv)\n\n---\n\nNotes: Discount-regression recursions as in *Prado, Ferreira & West (2023),* ch. 3. For (b), starred forms use $q_t^*=F_t^2 R_t^*+1$, $A_t=R_t^*F_t/q_t^*$, $C_t^*=(1-A_tF_t)R_t^*$, and $S_t=(n_{t-1}S_{t-1}+e_t^2/q_t^*)/n_t$; predictive variances are $S_t q_{t+h}^*$.\n:::\n\n::: {.callout-note}\n \n## Overthinking Elasticity\n\nSo this is not a typical price elasticity calculation. The usual definitions are due to Alfred Marshall text Principles of Economics cica 1890.\n\n$$\nE_d = \\frac {\\Delta Q/Q}{\\Delta P/P}  \\qquad \\text{(elasticity)}\n$$ {#eq-elasticity}\n\n$$\nE_d = \\frac {\\left({\\frac {P_{1}+P_{2}}{2}}\\right)}{\\left({\\frac {Q_{d_{1}}+Q_{d_{2}}}{2}}\\right)}}\\times {\\frac {\\Delta Q_{d}}{\\Delta P}}={\\frac {P_{1}+P_{2}}{Q_{d_{1}}+Q_{d_{2}}}}\\times {\\frac {\\Delta Q_{d}}{\\Delta P}}  \\qquad \\text{(arc elasticity)}\n$$ {#eq-arc-elasticity}\n\nwhere $Q$ is quantity sold, $P$ is price, and $E_d$ is the elasticity.\n\n$$\nE_d= \\frac{\\partial Q}{\\partial P} \\cdot \\frac{P}{Q} \\qquad \\text{(point elasticity)}\n$$ {#eq-point-elasticity}\n\nHere we need to know the arc elasticity function and to be able to differentiate it.\n\nAnother subtlety is due to the distinction between Marshallian and Hicksian  demand. The latter includes income effects due to ratio of a budget (a function of income) to the price can be substantial, possibly dominating  the price effect e.g. for Giffen Goods)\n\nWe usually look at % unit sold \n\nTo estimate elasticity, we need to know the price at which the market share is measured. In this case, the price is not given in the data, but it is implied by the values of $F_t$. The elasticity can be interpreted as the percentage change in market share for a 1% change in price.\n\n\n:::\n\n",
    "supporting": [
      "C4-QA-HW-ch3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}