---
title: "Kalman Filter"
subtitle: "Appendix"
description: "This appendix explains the Kalman Filter, a mathematical method for estimating the state of a dynamic system from a series of noisy measurements."
categories: 
    - "Probability and Statistics"
keywords: 
    - "Kalman Filter"
    - "state estimation"
    - "linear algebra"
---

<!-- TODO move this to its own specilization ASAP -->

## Kalman Filter - (extra curricular) circa 1960 {#sec-kf-1.1.1-introduction}

The Kalman Filter arises in the filtering equations of the NDLM in the course on Bayesian time series.

One of the mysteries of the NDLM is how the Matrix $G$ takes it form. This is not explained very well in the course that carries on as if the Kalman filter does not exist. However most of what student find difficult to understand in the NDLM is explained by a quick introduction to the the Kalman filter.

This appendix is adapted from :

- 95% the material for [Gregory Plett's](http://mocha-java.uccs.edu/) Kalman filter bootcamp. (Occasional I made minor changes) as well as my own insights from the NDLM. also see [Lecture notes and recordings for ECE5550: Applied Kalman Filtering](http://mocha-java.uccs.edu/ECE5550/index.html)
- Insights relating DLM and Kalman filters  from [@petris2009dynamic], 
- I plan to will likely also add some insights from [@särkkä2013bayesian]
- Once I complete the bootcamp I be better able to reduced the material further or migrate it to a separate tome!


Note: KF requires a good understanding of linear algebra, matrix operations, and probability theory. If you are not familiar with these concepts, it is recommended to review them before diving into the Kalman filter.



- Linear algebra:
  - Vectors and matrices are used to represent the state of a dynamic system.
  - Eigenvalue decomposition is used to analyze the dynamics of the system.
  - The matrix exponential is used to solve the state space model.
  - Jordan form may be needed if the dynamics matrix is not diagonalizable.
  - The Toeplitz matrices and Vandermonde matrices are used in some derivations of the Kalman filter.
- State space vector representation of dynamic systems.
- Laplace transforms are used for the state space model.
- Convolution operation 
