---
title: "Lesson 1.1.1 Kalman Filter"
subtitle: "Kalman Filter Boot Camp (and State Estimation)"
description: "This appendix explains the Kalman Filter, a mathematical method for estimating the state of a dynamic system from a series of noisy measurements."
categories: 
    - "Probability and Statistics"
keywords: 
    - "Kalman Filter"
    - "state estimation"
    - "linear algebra"
---

## Kalman Filter - circa 1960 {#sec-kf-1.1.1-introduction}


::: {.callout-note}
## Prerequisites
The KF requires a good understanding of linear algebra, matrix operations, and probability theory. 
If you are not familiar with these concepts, it is recommended to review them before diving into the Kalman filter.
:::

- Linear algebra:
  - Vectors and matrices are used to represent the state of a dynamic system.
  - Eigenvalue decomposition is used to analyze the dynamics of the system.
  - The matrix exponential is used to solve the state space model.
  - Jordan form may be needed if the dynamics matrix is not diagonalizable.
  - The Toeplitz matrices and Vandermonde matrices are used in some derivations of the Kalman filter.
- State space vector representation of dynamic systems.
- Laplace transforms are used for the state space model.
- Convolution operation 

::: {.callout-note}
## Kalman Filter - Minimum
 
The course instructor points out that you can learn the Kalman filter in a couple of lessons and that it is not a difficult topic.

This is true, but he goes into the details of the derivation and the mathematical background, which is important for a deep understanding of the topic.
Also there are many variations of the Kalman filter, and understanding the derivation can help you understand how to modify the filter for different applications.
:::

One fascinating connection is that of the Kalman filter to the [Bellman equation](https://en.wikipedia.org/wiki/Bellman_equation) in Reinforcement Learning. 
The Kalman filter can be seen as a special case of the Bellman equation, where the state transition and observation models are linear and Gaussian.
