---
title: "Lesson 1.1.6: Where to from here?"
subtitle: "Kalman Filter Boot Camp (and State Estimation)"
description: "This appendix explains the Kalman Filter, a mathematical method for estimating the state of a dynamic system from a series of noisy measurements."
categories: 
    - "Probability and Statistics"
    - "Kalman Filter"
keywords: 
    - "Kalman Filter"
    - "state estimation"
    - "linear algebra"
---

## Where to from here {#sec-kf-1.1.6-where-to-from-here}

::: {.callout-tip}
## TL-DR; -- KF Applications.

{{< lipsum 1 3 >}}
:::

### Summary of this week

- At the end of every week, we quickly summarize progress
made during the week and preview upcoming topics.

- This week, we introduced the purpose and basic features of Kalman filters.

   - You learned that the purpose of a KF is to estimate the state of a dynamic system.
   -  You learned that the KF requires a model of system dynamics and noises.
   -  You learned that the KF repeatedly performs two steps: prediction and correction.
   -  You learned that the output of a KF is an estimate of the model’s state as well as the uncertainty of the estimate.
   - You learned some example application categories that use KF.

## Where to from here?

- You are now ready to study the background topics that are
necessary to be able to understand more deeply how a KF
works, and to implement it for your application.

- Next week, we focus on learning about state-space models.
   - Why do we need to know about them?
   - What are some example model types that we might want touse for some applications?
   -  How do we think about the time-domain response of a state-space model?
   - How do we convert a continuous-time model to a discrete-time model, and how do we simulate them?
   - Can the model tell us if it is even possible for a KF to estimate its state?