---
title: "Lesson 1.2.8: Where to from here?"
subtitle: "Kalman Filter Boot Camp (and State Estimation)"
description: "This lesson summarizes the key concepts covered in the first week of the Kalman Filter Boot Camp and provides guidance on how to proceed with the specialization."
categories: 
    - "Probability and Statistics"
keywords: 
    - "Kalman Filter"
    - "state estimation"
    - "linear algebra"
---

## Where to from here? {#sec-kf-1.2.8-where-to-from-here}

### Summary of this week

- How is the boot camp going? Are you getting stronger?
- This week, you learned a lot of new concepts regarding state space models of dynamic systems.
- You learned how they are defined, both for continuous-time and discrete-time
systems.
    - You learned NCP, NCV, and CT example models that are useful for tracking.
    - You learned how to understand and simulate dynamic response.
    - You learned how to convert from a continuous-time to a discrete-time model.
    - You learned how to determine whether the system is observable, and why that
matters.

### Where to from here?

- How is the boot camp going? Are you getting stronger?
- This week, you learned a lot of new concepts regarding state-space models of dynamic systems.
- You learned how they are defined, both for continuous-time and discrete-time
systems.
    - You learned NCP, NCV, and CT example models that are useful for tracking.
    - You learned how to understand and simulate dynamic response.
    - You learned how to convert from a continuous-time to a discrete-time model.
    - You learned how to determine whether the system is observable, and why that matters.
