---
title: "1.4.6: Where to from here?"
description: "In this lesson, we will summarize what you have learned in this week’s lessons, and we will discuss where to from here."
date: "2026-04-22"
---

## Summary of this week

- Congratulations for completing the Kalman-filter Boot Camp!
- This week, you learned the steps of the Kalman filter.
- You learned how to prepare a system model for use by a Kalman filter.
- You learned how to implement that model in Octave code, and how to implement a Kalman filter in Octave code.
- You saw some examples that demonstrated the robustness of the Kalman filter to uncertain initial states, and how it outperforms open-loop predictors.
- You also saw some conditions that can cause a Kalman filter to fail.

---

## Where to from here?

- Is it possible to overcome these failure conditions? Yes!
- But, to do so, you will need to learn how the KF is derived to see where the derivation assumptions are being violated.
- Then, we will be able to modify the derivation for special cases where we need to implement different assumptions.

### Course 2: *Linear Kalman Filter Deep Dive*

- You will learn how to derive the KF equations.
- You will learn how to overcome failure conditions.
- You will learn additional applications of the KF and how to simplify the KF steps in some cases.
- You will learn how to implement a target-tracking application with KF.
