{
  "hash": "50f04c05654e3411f7d01c2da2e05741",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework on ANOVA - M3L8HW1\"\nsubtitle: \"Bayesian Statistics: Techniques and Models\"\ncategories:\n  - Bayesian Statistics\nkeywords:\n  - Conditional Probability\n  - ANOVA\n  - Homework\n---\n\n::::: {.content-visible unless-profile=\"HC\"}\n\n::: {.callout-caution}\nSection omitted to comply with the Honor Code\n:::\n\n:::::\n\n::::: {.content-hidden unless-profile=\"HC\"} \n\n::: {#exr-ANOVA-1}\n[ANOVA]{.column-margin} Which of the following variables qualifies as a \"factor\" variable?\n:::\n\n::: {.solution  .column-screen-inset-right .callout-tip collapse=\"true\"}\n#### Solution:\n\n-   [ ] Weight of a patient reported in kilograms\n-   [ ] Pre-treatment temperature reported in degrees Celsius\n-   [ ] Patient age in years\n-   [x] Treatment with either an experimental drug or a control placebo\n\nThis is a categorical predictor.\n:::\n\n::: {#exr-ANOVA-2}\n[ANOVA]{.column-margin} In an ANOVA model for a single factor with four levels, there are multiple ways we can parameterize our model for $\\mathbb{E}[y]$). These include the cell means model or a linear model with a baseline mean and adjustments for different levels. Regardless of the model chosen, what is the maximum number of parameters we use to relate this factor with $\\mathbb{E}[y]$ in a linear model and still be able to uniquely identify the parameters?\n:::\n\n\\index{model!ANOVA} \\index{model!cell means} \\index{model!baseline}\n\n::: {.solution  .column-screen-inset-right .callout-tip collapse=\"true\"}\n#### Solution:\n\n4\n\nIf we use any more than four parameters to describe E(y), there will be infinitely many values of the parameters that produce a given E(y) for a given set of predictor values.\n:::\n\nQuestion 3\n\nFor Questions [@exr-ANOVA-3 through @exr-ANOVA-8], refer to the plant growth analysis from the lesson.\n\nRe-fit the JAGS model on plant growth from the lesson with a separate variance for each of the three groups. To do so, modify the model code to index the precision in the normal likelihood by group, just as we did with the mean. Use the same priors as the original model (except in this case it will be three independent priors for the variances).\n\n::: {#exr-ANOVA-3}\n[ANOVA]{.column-margin} Compare the estimates between the original lesson model and this model with the summary function. Notice that the posterior means for the three μ parameters are essentially unchanged. However, the posterior variability for these parameters has changed. The posterior for which group's mean was most affected by fitting separate group variances?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"rjags\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"PlantGrowth\")  # load the data set\n#?PlantGrowth\nmod1_string = \" model {\n    for (i in 1:length(y)) {\n        y[i] ~ dnorm(mu[grp[i]], prec)\n    }\n    \n    for (j in 1:3) {\n        mu[j] ~ dnorm(0.0, 1.0/1.0e6)\n    }\n    \n    prec ~ dgamma(5/2.0, 5*1.0/2.0)\n    sig = sqrt( 1.0 / prec )\n} \"\n\nset.seed(82)\n#str(PlantGrowth)\ndata1_jags = list(y=PlantGrowth$weight, grp=as.numeric(PlantGrowth$group))\n\nparams = c(\"mu\", \"sig\")\n\ninits1 = function() {\n    inits = list(\"mu\"=rnorm(3,0.0,100.0), \"prec\"=rgamma(1,1.0,1.0))\n}\n\nmod1 = jags.model(textConnection(mod1_string), data=data1_jags, inits=inits1, n.chains=3)\nupdate(mod1, 1e3)\n\nmod1_sim = coda.samples(model=mod1, variable.names=params, n.iter=5e3)\nmod1_csim = as.mcmc(do.call(rbind, mod1_sim)) # combined chains\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"PlantGrowth\")  # load the data set\n\nmod2_string = \" model {\n    for (i in 1:length(y)) {\n        y[i] ~ dnorm(mu[grp[i]], prec[grp[i]])\n    }\n    for (j in 1:3) {\n        mu[j] ~ dnorm(0.0, 1.0/1.0e6)\n        prec[j] ~ dgamma(5/2.0, 5*1.0/2.0)\n        sig[j] = sqrt( 1.0 / prec[j] )\n    }\n} \"\n\nset.seed(82)\ndata2_jags = list(y=PlantGrowth$weight, grp=as.numeric(PlantGrowth$group))\nparams = c(\"mu\", \"sig\")\ninits2 = function() {\n    inits = list(\"mu\"=rnorm(3,0.0,100.0), \"prec\"=rgamma(3,1.0,1.0))\n}\n\nmod2 = jags.model(textConnection(mod2_string), data=data2_jags, inits=inits2, n.chains=3)\nupdate(mod2, 1e3)\n\nmod2_sim = coda.samples(model=mod2, variable.names=params, n.iter=5e3)\nmod2_csim = as.mcmc(do.call(rbind, mod2_sim)) # combined chains\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod1_csim)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nIterations = 1:15000\nThinning interval = 1 \nNumber of chains = 1 \nSample size per chain = 15000 \n\n1. Empirical mean and standard deviation for each variable,\n   plus standard error of the mean:\n\n        Mean     SD  Naive SE Time-series SE\nmu[1] 5.0328 0.2265 0.0018496      0.0018189\nmu[2] 4.6626 0.2280 0.0018614      0.0018614\nmu[3] 5.5272 0.2283 0.0018645      0.0018645\nsig   0.7114 0.0913 0.0007455      0.0008155\n\n2. Quantiles for each variable:\n\n        2.5%    25%    50%    75%  97.5%\nmu[1] 4.5868 4.8813 5.0331 5.1832 5.4795\nmu[2] 4.2087 4.5127 4.6616 4.8136 5.1166\nmu[3] 5.0776 5.3760 5.5287 5.6804 5.9737\nsig   0.5596 0.6466 0.7023 0.7647 0.9204\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod2_csim)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nIterations = 1:15000\nThinning interval = 1 \nNumber of chains = 1 \nSample size per chain = 15000 \n\n1. Empirical mean and standard deviation for each variable,\n   plus standard error of the mean:\n\n         Mean     SD Naive SE Time-series SE\nmu[1]  5.0346 0.2578 0.002105       0.002013\nmu[2]  4.6656 0.2945 0.002405       0.002405\nmu[3]  5.5220 0.2380 0.001943       0.001943\nsig[1] 0.8003 0.1637 0.001337       0.001475\nsig[2] 0.9251 0.1914 0.001563       0.001639\nsig[3] 0.7356 0.1505 0.001229       0.001317\n\n2. Quantiles for each variable:\n\n         2.5%    25%    50%    75% 97.5%\nmu[1]  4.5098 4.8709 5.0366 5.2017 5.537\nmu[2]  4.0755 4.4790 4.6656 4.8553 5.248\nmu[3]  5.0472 5.3691 5.5246 5.6768 5.998\nsig[1] 0.5555 0.6847 0.7749 0.8872 1.190\nsig[2] 0.6352 0.7905 0.8962 1.0286 1.379\nsig[3] 0.5117 0.6293 0.7128 0.8147 1.091\n```\n\n\n:::\n:::\n\n\nCompare the estimates between the original lesson model and this model with the summary function. Notice that the posterior means for the three μ parameters are essentially unchanged. However, the posterior variability for these parameters has changed. The posterior for which group's mean was most affected by fitting separate group variances??\n:::\n\n::: {.solution  .column-screen-inset-right .callout-tip collapse=\"true\"}\n#### Solution:\n\n-   [ ] Group 1: control\n-   [x] Group 2: treatment 1.\n-   [ ] Group 3: treatment 2\n-   [ ] The effect on the marginal posterior was the same for all three groups.\n\nSD of group 2 mean increased from 0.23035 to 0.2988 that a 0.07 change\n\nGroup 2 has the highest variation in plant weight, which results in less confidence in our posterior mean estimate. The posterior standard deviation of μ has increased the most for this group.\n:::\n\n::: {#exr-ANOVA-4}\n[ANOVA]{.column-margin} Compute the deviance information criterion (DIC) for each of the two models and save the results as objects dic1 (for the original model) and dic2 (for the new model). Wha is the difference: DIC1 - DIC2?.\n\\index{model selection!DIC}\n\n\nHint: You can compute this directly with the following code: dic1−dic2.\n:::\n\n::: {.solution  .column-screen-inset-right .callout-tip collapse=\"true\"}\n#### Solution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(dic1 = dic.samples(mod1,1e5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean deviance:  58.99 \npenalty 4.114 \nPenalized deviance: 63.11 \n```\n\n\n:::\n\n```{.r .cell-code}\n(dic2 = dic.samples(mod2,1e5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean deviance:  61.22 \npenalty 5.763 \nPenalized deviance: 66.99 \n```\n\n\n:::\n\n```{.r .cell-code}\ndic1-dic2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference: -3.878537\nSample standard error: 1.641327\n```\n\n\n:::\n:::\n\n\n-3.892918\n:::\n\n::: {#exr-ANOVA-5}\n[ANOVA]{.column-margin} Based on the DIC calculations for these competing models, what should we conclude?\n:::\n\n\\index{model selection!DIC}\n\n::: {.solution  .column-screen-inset-right .callout-tip collapse=\"true\"}\n#### Solution:\n\n-   [ ] The DIC is higher for the new model, indicating preference for the model with separate variances across groups.\n-   [x] The DIC is lower for the original model, indicating preference for the model with one common variance across groups.\n-   [ ] The DIC is higher for the original model, indicating preference for the model with one common variance across groups.\n-   [ ] The DIC is lower for the new model, indicating preference for the model with separate variances across groups.\n\nThis suggests we should stay with the original model (if our objective is good prediction).\n:::\n\n::: {#exr-ANOVA-6}\n[ANOVA]{.column-margin} Use the original model (single variance) to calculate a 95% interval of highest posterior density (HPD) for $\\mu_3−\\mu_1$. Which of the following is closest to this interval?\n:::\n\n::: {.solution  .column-screen-inset-right .callout-tip collapse=\"true\"}\n#### Solution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq5 = as.mcmc( cbind(mod1_csim,mudif=mod1_csim[,3]-mod1_csim[,1]) )  #<1>\nsummary((q5))                                                       #<2>\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nIterations = 1:15000\nThinning interval = 1 \nNumber of chains = 1 \nSample size per chain = 15000 \n\n1. Empirical mean and standard deviation for each variable,\n   plus standard error of the mean:\n\n        Mean     SD  Naive SE Time-series SE\nmu[1] 5.0328 0.2265 0.0018496      0.0018189\nmu[2] 4.6626 0.2280 0.0018614      0.0018614\nmu[3] 5.5272 0.2283 0.0018645      0.0018645\nsig   0.7114 0.0913 0.0007455      0.0008155\nmudif 0.4944 0.3205 0.0026169      0.0026169\n\n2. Quantiles for each variable:\n\n         2.5%    25%    50%    75%  97.5%\nmu[1]  4.5868 4.8813 5.0331 5.1832 5.4795\nmu[2]  4.2087 4.5127 4.6616 4.8136 5.1166\nmu[3]  5.0776 5.3760 5.5287 5.6804 5.9737\nsig    0.5596 0.6466 0.7023 0.7647 0.9204\nmudif -0.1376 0.2819 0.4947 0.7048 1.1311\n```\n\n\n:::\n:::\n\n\n1.  add a parameter called `mudiff` by calculate $\\mu_3-\\mu_1$ for each sample\n2.  use the summary to get quantiles and read 2.5% and 97.5% for `mudiff`\n\n-   [ ] (-0.20, 1.19)\n-   [ ] (-1.01, 0.25)\n-   [ ] (0.22, 1.49)\n-   [x] (-0.14, 1.13)\n\nThe interval contains 0, indicating that the data lack strong (at least at the 95% level) evidence for $\\mu_3\\ne\\mu_1$. In the lesson, the posterior probability that $\\mu_3>\\mu_1$ was 0.94.\n:::\n\n::: {#exr-ANOVA-7}\n[ANOVA]{.column-margin} What is the correct interpretation of $\\mu_3−\\mu_1$ in the context of the plant growth analysis?\n:::\n\n::: {.solution  .column-screen-inset-right .callout-tip collapse=\"true\"}\n#### Solution:\n\n-   [ ] It is the effect (change) of treatment 2 with respect to the control in mean plant weight.\n-   [ ] It is the mean range of plant weight across the three treatment groups.\n-   [ ] It is the difference in plant weight between treatment 2 and control.\n-   [x] It is the effect (change) of treatment 2 with respect to the control in plant weight.\n\nMCMC algs are based on a process guaranteeing convergence to a stationary distribution.\n:::\n\n::: {#exr-ANOVA-8}\n[ANOVA]{.column-margin} The linear model with a baseline mean and group effects is the default in R. However, we can also fit the cell means model in R using the following code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_cm = lm(weight ~ -1 + group, data=PlantGrowth)\nsummary(mod_cm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = weight ~ -1 + group, data = PlantGrowth)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.0710 -0.4180 -0.0060  0.2627  1.3690 \n\nCoefficients:\n          Estimate Std. Error t value Pr(>|t|)    \ngroupctrl   5.0320     0.1971   25.53   <2e-16 ***\ngrouptrt1   4.6610     0.1971   23.64   <2e-16 ***\ngrouptrt2   5.5260     0.1971   28.03   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6234 on 27 degrees of freedom\nMultiple R-squared:  0.9867,\tAdjusted R-squared:  0.9852 \nF-statistic: 665.5 on 3 and 27 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nwhere the −1 in the model formula tells R to drop the intercept. Because we used fairly noninformative priors for the $μ$ parameters in the analysis with JAGS, the results are very similar.\n\nIn addition to allowing different prior specifications, what is one advantage of posterior sampling with JAGS over fitting the reference model in R?\n:::\n\n::: {.solution  .column-screen-inset-right .callout-tip collapse=\"true\"}\n#### Solution:\n\n-   [ ] We can obtain posterior mode estimates for each mean (or coefficient).\n-   [ ] We can obtain posterior standard deviations (standard errors) for each mean (or coefficient).\n-   [ ] We can estimate the proportion of the variation in plant weight attributable to the treatment group assignment.\n-   [x] We can use the posterior samples to obtain simulated posterior distributions of any function of the parameters that may interest us (e.g., $μ_3−μ_1$).\n\nThe outer edges of the distribution are sampled less frequently and therefore susceptible to changes between simulations. The **Raftery and Lewis** diagnostic can help you decide how many iterations you need to reliably estimate outer quantiles of the target distribution..\n:::\n\n:::::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}