---
title: "Component Assignment Problem"

---


Consider a mixture of three Gaussian distribution with common identity covariance matrix and means $\mu_1 =(0,0)'$
 mu, start subscript, 1, end subscript, equals, left parenthesis, 0, comma, 0, right parenthesis, prime, $\mu_2`=(1/3,1/3)'$
$\mu3 =(−2/3,1/3)'$


For an observation $x_i =(31,−23)$, the probability of the observation being generated by the second component (rounded to three decimal places)?


is given by

- 0.98
- 1.00
- 0.97

This is correct.  The following code computes the value of interest.  Note that the calculations have been done in the log-likelihood scale.  Working in the original likelihood scale in this case leads to a wrong answer rather than an error.

So I could eyeball it and it has to be 0>0.3 and less than 1.0.  So the answer is 0.97.  The other two options are not possible.  I could have also used the `round` function to round it to three decimal places.

However we can also use the following based on material from the course to compute the value of interest.  


```{r}
library(mvtnorm)

mu1 = c(0, 0)
mu2 = c(1/3, 1/3)
mu3 = c(-2/3, 1/3)
x = c(31, -23)
Sigma = diag(1,2)

l1 = dmvnorm(x, mu1, Sigma, log=T)
l2 = dmvnorm(x, mu2, Sigma, log=T)
l3 = dmvnorm(x, mu3, Sigma, log=T)

exp(l2 - max(l1,l2,l3))/(exp(l1 - max(l1,l2,l3)) + exp(l2 - max(l1,l2,l3)) + exp(l3 - max(l1,l2,l3)))
```
