{
  "hash": "2d1dec3d5c7d949124e334e56ce42e1b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework Regression - M4L12HW1\"\nsubtitle: \"Bayesian Statistics: From Concept to Data Analysis\"\ncategories:\n  - Bayesian Statistics\nkeywords:\n  - Exponential Distribution\n  - Homework\n---\n\n::::: {.content-visible unless-profile=\"HC\"}\n\n::: {.callout-caution}\nSection omitted to comply with the Honor Code\n:::\n\n:::::\n\n::::: {.content-hidden unless-profile=\"HC\"} \n\n\nFor [@exr-regression-golf-1]--[@exr-regression-golf-6] consider the following:\n\n\\index{dataset!golf}\nThe data found at [pgalpga2008.dat](http://www.stat.ufl.edu/~winner/data/pgalpga2008.dat) consist of season statistics for individual golfers on the United States LPGA and PGA tours. The first column reports each player's average driving distance in yards. The second column reports the percentage of the player's drives that finish in the fairway, measuring their accuracy. The third and final column has a 1 to denote a female golfer (on the LPGA tour), and a 2 to denote a male golfer (on the PGA tour).\n\nLoad these data into R or Excel. In Excel, once you paste the data into a new worksheet, you may need to separate the data into columns using the \"Text to Columns\" feature under the \"Data\" menu.\n\nIf you wish to separate the LPGA and PGA data, one way in R is to use the subset function:\n\nwhere \"dat\" is the name of the original data set (replace \"dat\" with whatever you named this data set), \"FM\" is the name of the third column (replace \"FM\" with whatever you named this column), and select=1:2 means to include columns 1 and 2 in the new data set \"datF\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat=read.table(\"data/pgalpga2008.dat.txt\", header=T)\n# Note that attaching this masks T which is originally TRUE\nattach(dat)\ncolnames(dat) <- c('distance','accuracy','gender')\nsummary(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    distance        accuracy         gender     \n Min.   :224.8   Min.   :49.00   Min.   :1.000  \n 1st Qu.:247.9   1st Qu.:61.10   1st Qu.:1.000  \n Median :276.7   Median :65.60   Median :2.000  \n Mean   :269.6   Mean   :65.23   Mean   :1.558  \n 3rd Qu.:287.7   3rd Qu.:69.50   3rd Qu.:2.000  \n Max.   :315.1   Max.   :80.40   Max.   :2.000  \n```\n\n\n:::\n\n```{.r .cell-code}\ndatM <- subset(dat, gender==2, select=1:2)\ndatF <- subset(dat, gender==1, select=1:2)\n\nhead(datM)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    distance accuracy\n157    290.3     59.5\n158    302.1     54.7\n159    287.1     62.4\n160    282.7     65.4\n161    299.1     52.8\n162    300.2     51.1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(datM)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    distance        accuracy    \n Min.   :261.4   Min.   :49.00  \n 1st Qu.:282.0   1st Qu.:59.50  \n Median :287.0   Median :63.10  \n Mean   :287.6   Mean   :63.36  \n 3rd Qu.:293.3   3rd Qu.:66.90  \n Max.   :315.1   Max.   :80.40  \n```\n\n\n:::\n\n```{.r .cell-code}\nhead(datF)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  distance accuracy\n1    254.5     70.1\n2    253.1     59.3\n3    228.1     70.4\n4    240.8     69.5\n5    244.0     69.0\n6    257.9     66.3\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(datF)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    distance        accuracy    \n Min.   :224.8   Min.   :49.30  \n 1st Qu.:240.8   1st Qu.:64.45  \n Median :246.3   Median :68.35  \n Mean   :246.8   Mean   :67.59  \n 3rd Qu.:253.1   3rd Qu.:71.33  \n Max.   :269.5   Max.   :79.80  \n```\n\n\n:::\n:::\n\n\n::: {#exr-regression-golf-1}\n[**Golf**]{.column-margin} Create two scatter plots with average drive distance on the x-axis and percent accuracy on the y-axis, one for female golfers and one for male golfers. What do you observe about the relationship between these two variables?\n\n:::: {.solution  .column-screen-inset-right .callout-tip collapse=\"true\"}\n#### Solution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(datM$distance, datM$accuracy, main=\"Scatterplot\", xlab=\"distance (yards)\", ylab=\"accuracy(pct)\", pch=19)\nabline(lm(datM$accuracy~datM$distance), col=\"red\") # regression line (y~x)\nlines(lowess(datM$accuracy,datM$distance), col=\"blue\") # lowess line (x,y)\n```\n\n::: {.cell-output-display}\n![](C1-L12-Ex1_files/figure-html/C1-L12-Ex1-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(datF$distance, datF$accuracy, main=\"Scatterplot\", xlab=\"distance (yards)\", ylab=\"accuracy(pct)\", pch=19)\nabline(lm(datF$accuracy~datF$distance), col=\"red\") # regression line (y~x)\nlines(lowess(datF$accuracy,datF$distance), col=\"blue\") # lowess line (x,y)\n```\n\n::: {.cell-output-display}\n![](C1-L12-Ex1_files/figure-html/C1-L12-Ex1-2-2.png){width=672}\n:::\n:::\n\n\n::::\n:::\n\n::: {#exr-regression-golf-2}\n[**Golf**]{.column-margin}\n\nFit a linear regression model to the female golfer data only with drive distance as the explanatory variable $x$ and accuracy as the response variable $y$. Use the standard reference (non-informative) prior.\n\nRecall that in a linear regression, we are modeling $E(y)=b_0+b_1x$\n\nIn this particular model, the intercept term is not interpretable, as we would not expect to see a 0-yard drive (but it is still necessary). Predictions should generally be made only within the range of the observed data.\n\nReport the posterior mean estimate of the slope parameter $b$ relating drive distance to accuracy.\n\n:::: {.solution  .column-screen-inset-right .callout-tip collapse=\"true\"}\n#### Solution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- lm(accuracy ~ distance, data=datF)\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = accuracy ~ distance, data = datF)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-23.6956  -2.6812   0.9755   3.6835  10.2227 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 130.9995    10.9663  11.946  < 2e-16 ***\ndistance     -0.2569     0.0444  -5.786  3.9e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.262 on 154 degrees of freedom\nMultiple R-squared:  0.1786,\tAdjusted R-squared:  0.1732 \nF-statistic: 33.48 on 1 and 154 DF,  p-value: 3.903e-08\n```\n\n\n:::\n:::\n\n\n::::\n:::\n\n::: {#exr-regression-golf-3}\n[**Golf**]{.column-margin}\n\nThe posterior mean estimate of the slope from [@exr-regression-golf-2] is about five standard errors below 0. Hence, the posterior probability that this slope is negative is near 1.\n\nSuppose the estimate is $b$. How do we interpret this value?\n\n:::: {.solution  .column-screen-inset-right .callout-tip collapse=\"true\"}\n#### Solution:\n\n-   [ ] If x is the driving distance, we expect the percentage accuracy to be $100bx$.\n\n-   [ ] If x is the driving distance, we expect the percentage accuracy to be $bx$.\n\n-   [x] For each additional yard of driving distance, we expect to see a decrease in percentage accuracy of $∣b∣$.\n\n-   [ ] For each additional yard of driving distance, we expect to see an increase in percentage accuracy of $∣b∣$.\n::::\n\n:::\n\n::: {#exr-regression-golf-4}\n[**Golf**]{.column-margin}\n\nUse the posterior mean estimates of the model coefficients to obtain a posterior predictive mean estimate of driving accuracy for a new female golfer whose average driving distance is x=260 yards. Round your answer to one decimal place.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict.lm(mod1,data.frame(distance=260))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n64.21029 \n```\n\n\n:::\n:::\n\n:::\n\n::: {#exr-regression-golf-5}\n[**Golf**]{.column-margin}\n\nWhich of the following gives a 95% posterior predictive interval for the driving accuracy of a new female golfer whose average driving distance is $x=260$ yards?\n\nHint: Modify the code provided with this lesson under \"prediction interval.\"\n\n:::: {.solution  .column-screen-inset-right .callout-tip collapse=\"true\"}\n#### Solution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#64.21029  -  0.03631 * qt(.975,195-2)\n#64.21029  +  0.03631 * qt(.975,195-2)\n#predict.lm(mod1,data.frame(distance=260),interval=\"confidence\", level=0.95)\npredict.lm(mod1,data.frame(distance=260),interval=\"prediction\", level=0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr     upr\n1 64.21029 53.71819 74.7024\n```\n\n\n:::\n:::\n\n\n(53.7, 74.7)\n\nThis is\n\n$$\n\\hat{y}^* \\pm t_{n-2}^{-1}(0.975) \\cdot se_r \\cdot \\sqrt{1 + \\frac{1}{n} + \\frac{(260-\\bar{x})^2}{(n-1)s_x^2}}\n$$ \n\nwhere:\n\n-   $\\hat{y}^*$ is the prediction mean found in [@exr-regression-golf-4],\n-   $t_{n-2}^{-1}(0.975)$ is the 0.975 quantile of a standard t distribution with n−2 degrees of freedom,\n-   $n$ is the number of data points,\n-   $se_r$ is the residual standard error (estimate of $\\sigma$)\n-   $\\bar{x}$ is the sample mean of driving distance, and\\\n-   $s_x^2$ is the sample variance of driving distance.\n::::\n:::\n\n::: {#exr-regression-golf-6}\n[**Golf**]{.column-margin}\n\nWhat is the interpretation of the interval found in [@exr-regression-golf-5]?\n\n:::: {.solution  .column-screen-inset-right .callout-tip collapse=\"true\"}\n#### Solution:\n\n-   [ ] If we select a new female golfer who averages 260 yards per drive, we are 95% confident that the posterior mean for her accuracy would be in the interval.\n-   [ ] For all female golfers who average 260 yards per drive, our probability is $.95$ that the mean of their driving accuracy is in the interval.\n-   [x] If we select a new female golfer who averages 260 yards per drive, our probability that her driving accuracy will be in the interval is .95.\n-   [ ] For all female golfers who average 260 yards per drive, we are 95% confident that all their driving accuracies will be in the interval.\n\nWhy is this the correct answer:\n\n1.  A Predictive interval does not predict a posterior mean.\n2.  It predicts a new observation.\n::::\n\n:::\n\n:::::",
    "supporting": [
      "C1-L12-Ex1_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}