---
title: "Course Introduction"
subtitle: "Measure Theoretic Probability - Jem Corcoran"
---

Almost from the second lesson of the first course covered here I wanted to cover measure based probability in my notes to provide a more solid mathematical foundation for the statistics courses. I did my first take in the appendix. 

The very first course I took on probability covered measure theory and in great depth following the instructors adaptation of material by Billingsley. However it was such a long time ago that a refresher course was in order. I recently took a couple of courses by Jem Corcoran on Coursera and when I came across her online course on measure based probability, I decided to focus on it.

The material in this course is dense and abstract, but Jem Corcoran does a great job of making it accessible and engaging. I highly recommend it to anyone interested in learning about measure based probability. Not the least for her ability to deliver rigorous proofs but to also a perchance for dial back the formality and provide intuition and motivation for the concepts being covered.

Probability theory as presented in this course transcends the divide of frequentist and bayesian statistics, rather providing a theoretical foundation for both.

Besides proving a great deal of theorems and lemmas, the course also provides a lot of visual intuition and motivation for the concepts being covered.

### Course content

So far I've covered the first 6 lessons and I inted to cover the rest of the course as well as a second course by the same instructor on markov chains and queing theory.
---

## Books

Jem Corcoran's course refernces  Billingsley's "Probability and Measure" for some prrofs of stronger results. But she also suggest using a more accessible book for the material.  

- Paul R. Halmos "Measure Theory and Probability" by 
- Billingsley, Patrick. (2012). Probability and measure. John Wiley & Sons