---
title: "Mixture of two Gaussian distributions"
categories: ['assignment','sim']
---

Enter code to sample 200 random numbers from a mixture of 3 Poisson distributions with means 1, 2 and 6 and weights 0.7, 0.2 and 0.1, respectively. 

```{r}
#| label: simulation
# Generate n observations from a mixture of two Gaussian 
# distributions

set.seed(452) # Ensure simulation is reproducible
#n     = 50           # Size of the sample to be generated
n = 200 # sample size
#w     = c(0.6, 0.4)  # Weights
w = c(0.7,0.2,0.1) # weights
# mu    = c(0, 5)      # Means
# sigma = c(1, 2)      # Standard deviations
lambda = c(1,2,6) # lambda params (mean,variation)
# cc    = sample(1:2, n, replace=T, prob=w)
cc = sample(1:3,n, replace=T, prob=w)

# x     = rnorm(n, mu[cc], sigma[cc])
x = rpois(n,lambda=lambda[cc]) # simulate an cc mixture component n times



```

```{r}
#| label: fig-plot-sample
# Plot f(x) along with the observations 
# just sampled


empirical_feqs = table(factor(x, levels=seq(0, max(x))))/n

empirical_dist = empirical_feqs /n # convert frequencies to probabilities

barplot(empirical_dist,xlab="counts",ylab="probability",main="Empirical poisson mixture")


```